### ISSUE TITLE
Loading JSON file using RowFileInputReader

### ISSUE THREAD

**Issue by theredmoose** [streamthoughts/kafka-connect-file-pulse#102]
I am trying to stream a JSON file into Kafka using RowFileInputReader and I get a status as failed.  The JSON file has one JSON record per line and is gz.  My setup (kafka using docker) is as described in "Streaming data into Kafka S01/E03 — Loading JSON file".   Here is my config file.  

I am wondering if the error occurs because there is no source object such as "message".
"filters.ParseJSON.source":"message"

```
Config File
{
        "connector.class":"io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector",
        "fs.scan.directory.path":"/tmp/kafka-connect/examples/",
        "fs.scan.interval.ms":"10000",
        "fs.scan.filters":"io.streamthoughts.kafka.connect.filepulse.scanner.local.filter.RegexFileListFilter",
        "file.filter.regex.pattern":"part.*\\.gz$",
        "task.reader.class": "io.streamthoughts.kafka.connect.filepulse.reader.RowFileInputReader",
        "offset.strategy":"name",
        "skip.headers": "1",
        "topic":"mytest",
        "internal.kafka.reporter.bootstrap.servers": "broker:29092",
        "internal.kafka.reporter.topic":"connect-file-pulse-status",
        "fs.cleanup.policy.class": "io.streamthoughts.kafka.connect.filepulse.clean.DeleteCleanupPolicy",
        "filters": "ParseJSON",
        "filters.ParseJSON.type":"io.streamthoughts.kafka.connect.filepulse.filter.JSONFilter",
        "filters.ParseJSON.source":"message",
        "filters.ParseJSON.merge":"true",
        "filters.ParseJSON.explode.array":"true",
        "tasks.max": 1
        }

Sample JSON 
> My file has many more fields but this is an example.  Note that there is no parent level JSON fields.  Just one JSON message per line.

{"City":"Los Angeles","Continent":"North America","Country":"United States","Time":"1606159099.764","Timezone":"America/Los_Angeles","Version":"Windows 10","event_platform":"Win"}
{"City":"Los Angeles","Continent":"North America","Country":"United States","Time":"1606159099.764","Timezone":"America/Los_Angeles","Version":"Windows 10","event_platform":"Win"}
```

**Comment by theredmoose** [comment]
I tried producing the message without it being compressed and it worked.  So it has something to do with the .gz.  However, I read FilePulse should check for the compression by default correct?

**Comment by theredmoose** [comment]
Sorry I am not sure if this is the right place to ask these questions but I wanted to clarify what the options below should be if I am using RowFileInputReader for parsing JSON files.  

"filters.ParseJSON.source":"message",  > this value seems to work even though there is no "message" JSON field.
"filters.ParseJSON.explode.array":"false",  > I believe in my example above this is not relevant since each line is a separate record.  There is no array to expand.
"filters.ParseJSON.target":"mytarget",   > I can't seem to figure out how this is used. My JSON output doesn't contain this field when I use it in the config file.

If you have an example for parsing JSON using RowFileInputReader please share.  Thank you.

**Comment by fhussonnois** [comment]
Hi @theredmoose, currently FilePulse supports the following content-types: 
* `application/x-tar`
* `application/x-gzip`
* `application/x-zip-compressed`
* `application/zip`

You should first to check if one of these type match your file.

The `RowFileInputReader` will create a `Struct` object for each row with the a field `message` containing the data.
You can then use the `JSONFilter` to parse that field. The `target` property is used to define the field that should contain the parsed object.But most of the time this property is not used.

The configuration below should be sufficient: 
```
        "filters": "ParseJSON, ExcludeFieldMessage",
        "filters.ParseJSON.type":"io.streamthoughts.kafka.connect.filepulse.filter.JSONFilter",
        "filters.ParseJSON.source":"message",
        "filters.ParseJSON.merge":"true",
        "filters.ExcludeFieldMessage.type":"io.streamthoughts.kafka.connect.filepulse.filter.ExcludeFilter",
        "filters.ExcludeFieldMessage.fields":"message",
```

**Comment by theredmoose** [comment]
Thank you
