### ISSUE TITLE
Controlling the interval for streaming data

### ISSUE THREAD

**Issue by sbanga** [streamthoughts/kafka-connect-file-pulse#103]
Hi!

While reading data from a CSV file and streaming it, I would like to set the time interval (say, 1ms or 10s) for reading each line of data and streaming it. This would allow me to create a truly real time streaming effect for IoT data. I did explore tweaking the read.max.wait.ms parameter, but apparently that parameter has a different purpose.

Is there an easy way to accomplish what I'm trying to do? 

Thanks!

**Comment by fhussonnois** [comment]
Hi @sbanga, the `read.max.wait.ms` config property is used to wait fore more data when the task has reached the end of file. Currently, there is no mechanism to wait before sending next records.

If this is only for testing purpose you can write a simple bash script that sleep for 1 sec before writing a new record to a CSV file.

**Comment by sbanga** [comment]
Thanks @fhussonnois. The approach you outlined is what I have currently implemented.
