### ISSUE TITLE
Document separation character for bootstrap servers

### ISSUE THREAD

**Issue by hirsche** [streamthoughts/kafka-connect-file-pulse#113]
I'd suggest that you document for the json install configuration schema (@ https://streamthoughts.github.io/kafka-connect-file-pulse/docs/developer-guide/configuration/), that multiple brokers in

internal.kafka.reporter.bootstrap.servers

need to be specified with space as separation character instead of comma. This I guess would be helpful for others.

Best
Eduard

**Comment by OneCricketeer** [comment]
Unless it's split, and reassembled, I don't think spaces are correct

Config should be made a list, though

https://github.com/streamthoughts/kafka-connect-file-pulse/blob/master/connect-file-pulse-plugin/src/main/java/io/streamthoughts/kafka/connect/filepulse/config/CommonConfig.java#L86
