### ISSUE TITLE
Is it possible to determine beginning/end of file based on the first/last rows in the file? 

### ISSUE THREAD

**Issue by dmarupov** [streamthoughts/kafka-connect-file-pulse#115]
For example, if I have the following file content:
```
"Operation": "Start Of File"
"Record 1" : "This is the data for this row" 
"Record 2" : "This is the data for this row" 
"Record 3" : "This is the data for this row" 
"Operation": "End Of File"
```

Is it possible to use `"Operation": "End Of File"` to mark it as file `COMPLETED`?
If there is a filter or some feature that would allow this? If not, would it be possible to implement this through some code change?

Thank you very much for your help.

**Comment by fhussonnois** [comment]
Hi @dmarupov, currently I don't think you can mark a file `COMPLETED` using filter. 

However, you can implement a custom [FileInputReader](https://github.com/streamthoughts/kafka-connect-file-pulse/blob/v1.6.3/connect-file-pulse-api/src/main/java/io/streamthoughts/kafka/connect/filepulse/reader/FileInputReader.java) and the JAR to the classpath of Kafka Connect Worker.
