### ISSUE TITLE
Connector gets slowers over time when processing large CVS file

### ISSUE THREAD

**Issue by m4nuC** [streamthoughts/kafka-connect-file-pulse#125]
We try to process a CSV file with half a million rows, the first 1k rows are pretty fast then it gets slower and slower and eventually never finishes. Memory usage also increases over time. Any ideas on what could be the cause of this? FYI our pipeline handles much larger loads when using different sources.

The currrent configuration looks like this: 

```
connector.class=io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector
skip.headers=1
tasks.max=5
filters.ParseLine.extractColumnName=headers
fs.scan.directory.path=/bigfiletest
fs.recursive.scan.enable=false
transforms.validioHeader.type=com.validio.kafka.connect.smt.ValidioHeaders
fs.scan.interval.ms=60000
offset.strategy=path+name
internal.kafka.reporter.topic=filepusle-connector-internal
min.read.records=1000
```

**Comment by fhussonnois** [comment]
Hi @m4nuC , thank you for reporting this issue. So far we have not noticed any problems. I will run some tests with big files.

Did you monitor the JVM and Garbage Collector ?

**Comment by m4nuC** [comment]
Hi @fhussonnois, thanks for looking into this. I saw that you are implementing GCS and other storages which would be very handy for us.
Here is a [ sample file](https://storage.googleapis.com/validio_public_files/rand_data%20(1).csv) for a test. I did not monitor the JVM and Garbage collector, as I am not sure how to go about that (I am not a Java developer)

**Comment by fhussonnois** [comment]
Hi @m4nuC, thank you for the sample file. I've made some test with it and I've run the connector with 1000 copies of your file. Everything seems to work as expected. Also, I didn't noticed any memoryleak by profiling the JVM (HEAP 2GB). 

I also test with a 250MB file containing 10M rows and I didn't meet any issues.

So I have no idea where your problem lies. Have you allocated enough memory to your worker ?

**Comment by m4nuC** [comment]
Hi @fhussonnois, thanks for running the tests. I don't think it's a memory issue on the worker as we have been ingesting larger files with other connectors, also that issue was reproduced in 2 different environments. It is reassuring that you did not get the issue though, so I will keep digging and update if I find anything.

**Comment by m4nuC** [comment]
@fhussonnois Could you by any chance share the connector settings that you used in your tests?

**Comment by bwinchester** [comment]
@m4nuC , your connect server's memory setting is quite important for this connector to work effectively. You don't need specialized settings, but you do need to set the JVMs memory and GC settings for any connectors to work well.

https://docs.confluent.io/platform/current/kafka/deployment.html#jvm

**Comment by bwinchester** [comment]
we process GB + files with hundreds of millions of records in them and don't see issues with the producer keeping up. You could also have bad topic replication and min insync replica settings. The high availability topic settings from Confluent are 3 replicas and 2 min insync replicas, but the Max availability settings are 3 replicas and 1 min insync replica.

**Comment by bwinchester** [comment]
@m4nuC tasks.max=5 will only work if you are trying to parallelize reading many files at once.

**Comment by m4nuC** [comment]
Thank you @bwinchester. That is valuable info. I will be running some tests and update once I put my finger on the issue

**Comment by m4nuC** [comment]
After some monitoring of the JVM memory seems fine, it peaks but eventually gets garbage collected. 
However monitoring the JMX metrics, the `batch-size-max` on the producer seems to increase linearly until it gets larger than the allowed max. At that point, the task dies and doesn't restart (but the connector keeps on pooling).
 @fhussonnois @bwinchester would that help to point to a potential cause?

**Comment by m4nuC** [comment]
Issues solve. Came down to few configuration adjustments but what made the biggest improvement was to not modify the event headers inside an SMT.

**Comment by fhussonnois** [comment]
Hi @m4nuC, finally is your issue was related to Connect FilePulse ? This is to know if we need to investogate additional improvements ? Thanks

**Comment by m4nuC** [comment]
@fhussonnois, somewhat yes, for some reason, when adding an SMT that modifies the event headers, then the speed decay behaviour shows up. I've tested with quite a few other connectors and that did not happen. 


For info, here a simplified version of the SMT:

```
public class ValidioHeaders<R extends ConnectRecord<R>> implements Transformation<R> {

  public static final String OVERVIEW_DOC =
          "Insert routing headers";

  private static final String PURPOSE = "adding stream UUID to record headers";

  private String streamUUID;
  private String streamUUIDKey;

  @Override
  public void configure(Map<String, ?> props) {
    final SimpleConfig config = new SimpleConfig(CONFIG_DEF, props);
    streamUUID = config.getString(ConfigName.STREAM_UUID);
    streamUUIDKey = config.getString(ConfigName.STREAM_UUID_KEY);
  }


  @Override
  public R apply(R record) {
    return applySchemaless(record);
  }

  private R applySchemaless(R record) {
    ConnectHeaders newHeaders = new ConnectHeaders();
    newHeaders.addString("uuid", streamUUID);
    newHeaders.forEach(h -> record.headers().add(h));
    return record;
  }


  @Override
  public ConfigDef config() {
    return CONFIG_DEF;
  }
  @Override
  public void close() {
  }
}



```

**Comment by fhussonnois** [comment]
Thank you for you answer. This is quite strange as the management of SMTs is not tied to the connector itself and is managed directly by the Kafka Connect framework. So I don't see why there would be a loss of performance over time. The only thing is that FilePulse also adds headers but before executing the SMTs chain.
