### ISSUE TITLE
DelimitedRowFilter unable to parse some CSV files

### ISSUE THREAD

**Issue by WaasimTawali** [streamthoughts/kafka-connect-file-pulse#126]
Hello , 
i tried to parse a CSV file with DelimitedRowFilter but all my attempts failed , i tried all kinds of regular expressions without any results , 
this is the header of the CSV file : DATE/TIME,Request,Response,/Air:GetFaFList_3.0:In,/Air:UpdateFaFList_3.0:In,/Air:GetAllowedServiceClasses_3.0:In,/Air:UpdateServiceClass_3.0:In
is there a regex expression that i could use in the configuration file in order to parse the CSV file correctly ?
Thanks in advance

**Comment by fhussonnois** [comment]
Hi @WaasimTawali, I'm sorry for the delay.  Are you getting an exception ? For example, the field `DATE/TIME` is not valid as Avro field name so you will not beable to generate an Avro schema from that header line.

One solution is to remove invalid characters such has `:` and `/`. For this, you can used the ConnectFilePulse `AppendFilter` before the `DelimitedRowFilter`.

For example:

```
filters=TransformHeaders, ParseDelimitedRow
filters.TransformHeaders.field="$value.header"
filters.TransformHeaders.value="{{ lowercase(replace_all(extract_array($value.header,0), '(:|/)', '')) }}"
filters.TransformHeaders=type="io.streamthoughts.kafka.connect.filepulse.filter.AppendFilter"
filters.ParseDelimitedRow.extractColumnNam="header"
filters.ParseDelimitedRow.separator="\\|"
filters.ParseDelimitedRow.trimColumn="true"
filters.ParseDelimitedRow.type="io.streamthoughts.kafka.connect.filepulse.filter.DelimitedRowFilter"
```

**Comment by WaasimTawali** [comment]
Hello @fhussonnois  , thank you for the help
