### ISSUE TITLE
Need to add metadata to ouptut

### ISSUE THREAD

**Issue by gvdonovan** [streamthoughts/kafka-connect-file-pulse#131]
I need to ingest a CSF file that will be processed by consumers when the file is fully ingested.  Assuming I have the following file foo.csv:

first_name, last_name
Biff,Tannen
Foo,Bar

How can I add metada to the output so that what ultimately gets written to a db is:
[
{file_name: "foo.csv", file_date: 14134131341341, first_name: "Biff", last_name: "Tannen"},
{file_name: "foo.csv", file_date: 14134131341341, first_name: "Foo", last_name: "Bar"}
]

I see that I have $metadata.name and $metadata.lastModified - but how do I configure the connector so that these fields are added to the payload that ultimately gets loaded downstream (i.e. into a db).

Thanks!

**Comment by fhussonnois** [comment]
Hi @gvdonovan, you can use the filter chain mechanism of Connect FilePulse to add headers to payload using the  [AppendFilter](https://streamthoughts.github.io/kafka-connect-file-pulse/docs/developer-guide/filters/#appendfilter).

Here is an example : 
```
filters=AppendHeaderFileName
filters.AppendHeaderFileName
filters.AppendHeaderFileName.type=io.streamthoughts.kafka.connect.filepulse.filter.AppendFilter
filters.AppendHeaderFileName.field="$value.file_name"
filters.AppendHeaderFileName.value="{{ $metadata.name }}"
```

**Comment by gvdonovan** [comment]
adding this now:
filters.AppendHeaderFileName.type=io.streamthoughts.kafka.connect.filepulse.filter.AppendFilter
filters.AppendHeaderFileName.field="$value.file_name"
filters.AppendHeaderFileName.value="{{ $metadata.name }}"

**Comment by gvdonovan** [comment]
docker run --tty --network=host edenhill/kafkacat:1.6.0 kafkacat         -b localhost:9092         -t musics-filepulse-csv-99         -C -J -q -o-1 -s key=s -s value=avro -r http://localhost:8081 | jq .payload.ConnectDefault

results in:
parse error: Invalid numeric literal at line 1, column 2

I'm literally just appending to your blog

**Comment by gvdonovan** [comment]
OK - I see that my initial curl statement had the wrong topic - had csv-01 instead of csv-xx.  When I corrected that I get the output when running the above but the filename is not present:

$ docker run --tty --network=host edenhill/kafkacat:1.6.0 kafkacat -b localhost:9092 -t musics-filepulse-csv-xx -C -J -q -o-1 -s key=s -s value=avro -r http://localhost:8081 | jq .payload.ConnectDefault
{
  "title": {
    "string": "Zoo Station" 
  },
  "album": {
    "string": "Achtung Baby"
  },
  "duration": {
    "string": "04:36"
  },
  "release": {       
    "string": "1991" 
  },
  "artist": {        
    "string": "U2"   
  },
  "type": {
    "string": "Rock" 
  }
}

**Comment by gvdonovan** [comment]
I created another connector with the following:

curl \
    -i -X PUT -H "Accept:application/json" \
    -H  "Content-Type:application/json" http://localhost:8083/connectors/source-csv-filepulse-aa/config \
    -d '{
        "connector.class":"io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector",
        "fs.scan.directory.path":"/tmp/kafka-connect/examples/",
        "fs.scan.interval.ms":"10000",
        "fs.scan.filters":"io.streamthoughts.kafka.connect.filepulse.scanner.local.filter.RegexFileListFilter",
        "file.filter.regex.pattern":".*\\.csv$",
        "task.reader.class": "io.streamthoughts.kafka.connect.filepulse.reader.RowFileInputReader",
        "offset.strategy":"name",
        "skip.headers": "1",
        "topic":"musics-filepulse-csv-aa",
        "internal.kafka.reporter.bootstrap.servers": "broker:29092",
        "internal.kafka.reporter.topic":"connect-file-pulse-status",
        "fs.cleanup.policy.class": "io.streamthoughts.kafka.connect.filepulse.clean.LogCleanupPolicy",
        "tasks.max": 1,
        "filters":"ParseLine",
        "filters.ParseLine.extractColumnName": "headers",
        "filters.ParseLine.trimColumn": "true",
        "filters.ParseLine.separator": ";",
        "filters.ParseLine.type": "io.streamthoughts.kafka.connect.filepulse.filter.DelimitedRowFilter",
        "filters":"AppendHeaderFileName",
        "filters.AppendHeaderFileName.type":"io.streamthoughts.kafka.connect.filepulse.filter.AppendFilter",
        "filters.AppendHeaderFileName.field": "$value.file_name",
        "filters.AppendHeaderFileName.value":"{{ $metadata.name }}"
    }'

docker run --tty --network=host edenhill/kafkacat:1.6.0 kafkacat -b localhost:9092 -t musics-filepulse-csv-xx -C -J -q -o-1 -s key=s -s value=avro -r http://localhost:8081 | jq .payload.ConnectDefault

{
  "message": {
    "string": "Zoo Station;Achtung Baby;04:36;1991;U2;Rock"
  },
  "headers": {
    "array": [
      {
        "string": "title;album;duration;release;artist;type"
      }
    ]
  },
  "file_name": {
    "string": "musics-dataset-00.csv"
  }
}


**What I was expecting:**

{
  "title": {
    "string": "Zoo Station" 
  },
  "album": {
    "string": "Achtung Baby"
  },
  "duration": {
    "string": "04:36"       
  },
  "release": {
    "string": "1991"
  },
  "artist": {
    "string": "U2"
  },
  "type": {
    "string": "Rock"
  },
  "file_name": {
    "string": "musics-dataset-00.csv"
  }
}

**Comment by gvdonovan** [comment]
OK @fhussonnois  - I got it.... had to change the "filters" definition in the curl statement to
```
curl \
    -i -X PUT -H "Accept:application/json" \
    -H  "Content-Type:application/json" http://localhost:8083/connectors/source-csv-filepulse-ee/config \
    -d '{
        "connector.class":"io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector",
        "fs.scan.directory.path":"/tmp/kafka-connect/examples/",
        "fs.scan.interval.ms":"10000",
        "fs.scan.filters":"io.streamthoughts.kafka.connect.filepulse.scanner.local.filter.RegexFileListFilter",
        "file.filter.regex.pattern":".*\\.csv$",
        "task.reader.class": "io.streamthoughts.kafka.connect.filepulse.reader.RowFileInputReader",
        "offset.strategy":"name",
        "skip.headers": "1",
        "topic":"musics-filepulse-csv-ee",
        "internal.kafka.reporter.bootstrap.servers": "broker:29092",
        "internal.kafka.reporter.topic":"connect-file-pulse-status",
        "fs.cleanup.policy.class": "io.streamthoughts.kafka.connect.filepulse.clean.LogCleanupPolicy",
        "tasks.max": 1,
        "filters":"ParseLine, AppendHeaderFileName",                
        "filters.ParseLine.extractColumnName": "headers",
        "filters.ParseLine.trimColumn": "true",
        "filters.ParseLine.separator": ";",
        "filters.ParseLine.type": "io.streamthoughts.kafka.connect.filepulse.filter.DelimitedRowFilter",
        "filters.AppendHeaderFileName.type":"io.streamthoughts.kafka.connect.filepulse.filter.AppendFilter",
        "filters.AppendHeaderFileName.field": "$value.file_name",
        "filters.AppendHeaderFileName.value":"{{ $metadata.name }}"
    }'
```

Now on to figuring out how to get this in the db.
