### ISSUE TITLE
Failed to convert record field when loading XML, Types do not match STRUCT<>ARRAY

### ISSUE THREAD

**Issue by itoprover** [streamthoughts/kafka-connect-file-pulse#132]
io.streamthoughts.kafka.connect.filepulse.data.DataException: Failed to convert record field 'PartNumber' to connect data. Types do not match STRUCT<>ARRAY\n\tat io.streamthoughts.kafka.connect.filepulse.source.internal.ConnectSchemaMapper.toConnectStruct(ConnectSchemaMapper.java:209)

Trying to load the following XML:

`<?xml version="1.0" encoding="UTF-8"?>
		<FormName RevMonth="06" RevYear="2019">
			<PartNumber>1
				<DetailRow>1
					<PartDetails ECFRNumber="10">676</PartDetails>
					<PartDetails ECFRNumber="20">35073</PartDetails>
					<PartDetails ECFRNumber="30">Oakville North--Burlington</PartDetails>
					<PartDetails ECFRNumber="40">2019-09-11</PartDetails>
					<PartDetails ECFRNumber="50">2019-10-21</PartDetails>
					<PartDetails ECFRNumber="60">GG</PartDetails>
					<PartDetails ECFRNumber="70">Your</PartDetails>
					<PartDetails ECFRNumber="80"/>
					<PartDetails ECFRNumber="90">C</PartDetails>
					<PartDetails ECFRNumber="100">Your</PartDetails>
					<PartDetails ECFRNumber="110"/>
					<PartDetails ECFRNumber="120">Y</PartDetails>
				</DetailRow>
			</PartNumber>
			<PartNumber>6-b
				<DetailRow>1
					<PartDetails ECFRNumber="260">19</PartDetails>
					<PartDetails ECFRNumber="270">Mary jones</PartDetails>
					<PartDetails ECFRNumber="280">400.00</PartDetails>
					<PartDetails ECFRNumber="290">2</PartDetails>
				</DetailRow>
			</PartNumber>
		</FormName>
`

my config 
`{
        "connector.class":"io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector",
        "fs.scan.directory.path":"/tmp/kafka-connect/examples/",
        "fs.scan.interval.ms":"10000",
        "fs.scan.filters":"io.streamthoughts.kafka.connect.filepulse.scanner.local.filter.RegexFileListFilter",
        "file.filter.regex.pattern":".*\\.xml$",
        "task.reader.class": "io.streamthoughts.kafka.connect.filepulse.reader.XMLFileInputReader",
		"offset.strategy":"name",
        "topic":"testtopic",
        "internal.kafka.reporter.bootstrap.servers": "broker:29092",
        "internal.kafka.reporter.topic":"connect-file-pulse-status",
        "fs.cleanup.policy.class": "io.streamthoughts.kafka.connect.filepulse.clean.LogCleanupPolicy",
        "tasks.max": 1
}`

**Comment by fhussonnois** [comment]
Hi @itoprover, could you try to add this property to you configuration : `"force.array.on.fields": "PartNumber"` ?
