### ISSUE TITLE
The examples link in the documentation is broken.

### ISSUE THREAD

**Issue by ahmedalami** [streamthoughts/kafka-connect-file-pulse#134]
The examples link in the overview documentation (Where should I go next?
 section) is unfortunately broken.

Thanks in advance for fixing it.

**Comment by ahmedalami** [comment]
Thank you.
Still the url is not correct in the page https://streamthoughts.github.io/kafka-connect-file-pulse/docs/overview/filepulse/

It's also the case for the "Getting Started" link.

**Comment by fhussonnois** [comment]
Thank you for reporting this issue. Links have been fixed.
