### ISSUE TITLE
Submit the latest release of the connector in Confluent hub

### ISSUE THREAD

**Issue by ahmedalami** [streamthoughts/kafka-connect-file-pulse#135]
Can you please update the connector confluent hub with the latest version : [1.6.3](https://github.com/streamthoughts/kafka-connect-file-pulse/releases/tag/v1.6.3).
[1.5.0](https://www.confluent.io/hub/streamthoughts/kafka-connect-file-pulse) is the last registered version in Confluent Hub.

**Comment by fhussonnois** [comment]
Hi @ahmedalami, FilePulse 1.6.3 is now available on ConfluentHub: https://www.confluent.io/hub/streamthoughts/kafka-connect-file-pulse
