### ISSUE TITLE
define charsets for UTF8

### ISSUE THREAD

**Issue by kbegrow** [streamthoughts/kafka-connect-file-pulse#143]
Hi, 
its rather a question than an actual bug, 
but is there any way to define the charset for the csv files the connector is going to import in the connectors configuration?
Also is there any filter which could remove doubles quotes from the whole files?

Both can be done indeed before in other ways but I am pretty sure the connector is a way more powerful and I just don't use it.

Thank you in advance

**Comment by fhussonnois** [comment]
Hi @kbegrow 

Which version of FilePulse are you using ? 

You should be able to configure the property `file.encoding` which is used to configure the [`RowFileInputReader`](https://github.com/streamthoughts/kafka-connect-file-pulse/blob/v1.6.3/connect-file-pulse-plugin/src/main/java/io/streamthoughts/kafka/connect/filepulse/reader/RowFileInputReaderConfig.java). 

By default, the encoding is UTF-8.

You can use the [`AppendFilter`](https://streamthoughts.github.io/kafka-connect-file-pulse/docs/archives/v1.3.x/developer-guide/filters/#appendfilter) to remove double-quote before parsing the line.

**Comment by kbegrow** [comment]
I using the version 1.6.3.
The 3rd party CSVs I get are unfortunately in windows-1252 so I had some issues regarding some special characters.

I will check out the AppendFilter for the removing then. Thank you

**Comment by kbegrow** [comment]
@fhussonnois sorry for bother you, can I also delete a specific line in a CSV file using AppendFilter?

**Comment by fhussonnois** [comment]
HI @kbegrow, you can chain multiple filters with FilePulse. 

For removing some line you can use the [DropFilter](https://streamthoughts.github.io/kafka-connect-file-pulse/docs/developer-guide/filters/#dropfilter). In addition, to convert/cast field to float you can use the `AppendFilter` with an expression using the built-in function `convert`: https://streamthoughts.github.io/kafka-connect-file-pulse/docs/developer-guide/accessing-data-and-metadata/#builtin-functions

**Comment by kbegrow** [comment]
Hi @fhussonnois;
thank you. Yes the drop filter I've figured out in the meanwhile. 
For the convert function I might doing something wrong but I guess the convert has the same issue as the standard STM from connect because it seems to fail to transform a STRING to FLOAT since it expects a "." instead of "," which is caused by the customers local which ends up comma separated numbers in the CSVs. 

Either I can also configure the locale somewhere or I might need to replace the commas with a dot using AppendFilter.

**Comment by fhussonnois** [comment]
Hi @kbegrow, if you use Connect FilePulse 2.0.0 the connector automatically replace `,` with `.`. Otherwise, Yes you can use the AppendFilter for doing the replacement.

**Comment by kbegrow** [comment]
Hi @fhussonnois, last time I have checked, 2.0.0 was still a release candidate. 
Is there any release date set? I'll also interested in the azure blob storage so I would switch to version 2.0.0 as soon as its stable.

**Comment by fhussonnois** [comment]
@kbegrow : 2.0 is Released!

https://github.com/streamthoughts/kafka-connect-file-pulse/releases/tag/v2.0.0 
https://streamthoughts.github.io/kafka-connect-file-pulse/blog/2021/06/10/connect-filepulse-2.0-is-available/

**Comment by kbegrow** [comment]
Thank you @fhussonnois 
So in version 2.0.0 I could do following and it would convert STRING "9,00" into a FLOAT 9.00, correct?

           ```
            "filters.Converter1.type"        : "io.streamthoughts.kafka.connect.filepulse.filter.ConvertFilter",
            "filters.Converter1.field"       : "purchase_price",
            "filters.Converter1.to"          : "FLOAT",
            "filters.Converter2.type"        : "io.streamthoughts.kafka.connect.filepulse.filter.ConvertFilter",
            "filters.Converter2.field"       : "reduced_price",
            "filters.Converter2.to"          : "FLOAT",
            "filters.Converter3.type"        : "io.streamthoughts.kafka.connect.filepulse.filter.ConvertFilter",
            "filters.Converter3.field"       : "sales_price_after_sum_discount",
            "filters.Converter3.to"          : "FLOAT",
            "filters.Converter4.type"        : "io.streamthoughts.kafka.connect.filepulse.filter.ConvertFilter",
            "filters.Converter4.field"       : "sales_price",
            "filters.Converter4.to"          : "FLOAT",
```

**Comment by fhussonnois** [comment]
Hi @kbegrow, Yes with `filters=Converter1,Converter2,Converter3,Converter4`

**Comment by kbegrow** [comment]
@fhussonnois it seems that the 2.0.0 file pulse connector has issues getting loaded on connect 5.5.3. I copied the zip in the plugin path location, unzipped it and its not even recognized by connect after restarting. the same procedure works fine with 1.6.3.
As it seems 2.0.0. is not yet on confluent hub too.

So I might need to upgrade my connect version?

**Comment by kbegrow** [comment]
@fhussonnois the 2.0.0 version only works with connect 6.x , correct?
It seems like its getting completely ignored with my connect 5.5.3 / 5.5.4 cluster

**Comment by fhussonnois** [comment]
@kbegrow, I think the 2.0.0 should work with connect 5.x, but it's possible the connector is not yet available on confluent-hub. did you try to install it directly from the zip archive available on the GitHub Releases page ?

**Comment by kbegrow** [comment]
@fhussonnois I did actually both - the zip archive into plugin path as well as using confluent hub install (if you use latest there, it installs 2.0.0). 
Result is the same in both cases, the connector gets not loaded.
With 1.6.3 it works fine:

```
curl -sX GET http://localhost:8083/connector-plugins | jq
  {
    "class": "io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector",
    "type": "source",
    "version": "1.6.3"
  },
```

**Comment by kbegrow** [comment]
@fhussonnois I updated today our whole STAGING cluster for connect as well as brokers. And as you said, the plugin loads without issues. I check if everything else is running before role it out to production indeed.
I will check the file pulse configs with the filters tomorrow and let you know. The connector and the new features looks very promising and should fit to our needs. :-)

Its might be a good idea to mention that v2.0.0 needs at least connect 6.x in the documentation

Sorry for keeping you busy here. ;-)
