### ISSUE TITLE
Status topics have not removed

### ISSUE THREAD

**Issue by AzamAhmadloo** [streamthoughts/kafka-connect-file-pulse#166]
Hi every body 
I created some connectors and deleted them, but topics that created for connector status has remained and I cannot delete them. 

I tried to delete topics from zookeepers and remove kafka log directories but topics created again. 

This is my connector config:

{
    "name": "ALL",
    "config": {
        "connector.class": "io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector",
        "task.reader.class": "io.streamthoughts.kafka.connect.filepulse.reader.XMLFileInputReader",
        "tasks.max": "1",
        "fs.scan.directory.path": "/data/ALLRecieved/",
        "fs.scan.interval.ms": "10000",
        "xpath.expression": "//BuyData",
        "offset.strategy": "name",
        "internal.kafka.reporter.topic": "online.data.status",
        "fs.cleanup.policy.class": "io.streamthoughts.kafka.connect.filepulse.clean.LogCleanupPolicy",
        "fs.scan.filters": "io.streamthoughts.kafka.connect.filepulse.scanner.local.filter.RegexFileListFilter",
        "topic": "online.data",
        "internal.kafka.reporter.bootstrap.servers": "kafka-1:9092,kafka-2:9092,kafka-3:9092",
        "file.filter.regex.pattern": ".*.xml$"
    }
}

**Comment by fhussonnois** [comment]
Hi @AzamAhmadloo, which topics are you talking about exactly? Topics -config, -offset and -status are automatically created by Kafka Connect framework. Which version of the connector are you using ?

**Comment by AzamAhmadloo** [comment]
Thanks for your reply.
Every created connector has two topics, one for data and another one for status that the topics are specifying in connector config. And these are my example topics:
"internal.kafka.reporter.topic": "online.data.status",
"topic": "online.data",

I'm using confluent-6.1.1 for kafka connect service. 

I removed connectors and try to remove related topics. Data topic ( in my sample `online.data`) deleted successfully but the other one which was for connector status has remained ( in my sample `online.data.status` ).
I can't find the relation between remaining topics and connectors. Also I try to remove topics from zookeeper and kafka logis manually, but they created again after a short time.
