### ISSUE TITLE
Reproduce Tombstone messages from CSV

### ISSUE THREAD

**Issue by jciombalo** [streamthoughts/kafka-connect-file-pulse#167]
We need to parse a CSV file where the fist column is de action performed (`C` = changed, `D` = deleted) in that row.

Eg.:
```
action;id;attribute_1;attribute_2
C;123;foo;bar
D;456;foo;baz
```

I have a first filter that sets the message key and it's working properly:
```
    "filters.SetKey.type": "io.streamthoughts.kafka.connect.filepulse.filter.AppendFilter",
    "filters.SetKey.field": "$key",
    "filters.SetKey.value": "$value.id",
```

Now I'm trying to apply another filter to empty the value from the messages when its action = 'D' to simulate Tombstone messages, so the down streams can update their internal KTables by removing that Key from them.

My first attempt was to use the `AppendFilter` to set `null` in the `value`:
```
    "filters.Tombstone.type": "io.streamthoughts.kafka.connect.filepulse.filter.AppendFilter",
    "filters.Tombstone.if": "{{ equals($value.action, 'E') }}",
    "filters.Tombstone.field": "$value",
    "filters.Tombstone.value": "{{null}}",
    "filters.Tombstone.overwrite": true
```
But it throwed the following exception:
```
WorkerSourceTask{id=connect-file-pulse-quickstart-csv-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask)
io.streamthoughts.kafka.connect.filepulse.expression.accessor.AccessException: Cannot set property 'value' to 'InternalFilterContext' on target type InternalFilterContext : class java.lang.String cannot be cast to class io.streamthoughts.kafka.connect.filepulse.data.TypedStruct (java.lang.String is in module java.base of loader 'bootstrap'; io.streamthoughts.kafka.connect.filepulse.data.TypedStruct is in unnamed module of loader org.apache.kafka.connect.runtime.isolation.PluginClassLoader @c8e99)
```

In another attempt I've tried to use the `ExcludeFilter` to exclude the entire `$value`:
```
    "filters.Tombstone.type": "io.streamthoughts.kafka.connect.filepulse.filter.ExcludeFilter",
    "filters.Tombstone.if": "{{ equals($value.action, 'E') }}",
    "filters.Tombstone.fields": "$value"
```
But I suppose, based in the docs, that this filter didnt work with  ScEL. It didnt produced any exception, but didnt touched the message content anyway.

My last attempt was to to use the `ExcludeFilter` and remove every fields from the message:
```
    "filters.Tombstone.type": "io.streamthoughts.kafka.connect.filepulse.filter.ExcludeFilter",
    "filters.Tombstone.if": "{{ equals($value.action, 'E') }}",
    "filters.Tombstone.fields": "action,id,attribute_1,attribute_2"
```
But then the message still have an object without fields:
```
{}
```

Is there another way to solve this issue that I'm missing out? If not, I think it would be a nice feature to support.

**Comment by fhussonnois** [comment]
Hi @jciombalo, thank you very much for this issue.  It will now be possible to set a record-value to null using your given example : 

```
"filters.Tombstone.type": "io.streamthoughts.kafka.connect.filepulse.filter.AppendFilter",
"filters.Tombstone.if": "{{ equals($value.action, 'E') }}",
"filters.Tombstone.field": "$value",
 "filters.Tombstone.value": "{{ null }}",
```

There was a problem with the interpretation of the expression `{{ null }}`. In addition, the `AppendFilter` has been improved to support that behavior.
