### ISSUE TITLE
DelimitedRowFilter different length in first line

### ISSUE THREAD

**Issue by mohai-kafka** [streamthoughts/kafka-connect-file-pulse#171]
My usecase is I want to read .csv file but in that file first line contain less comma separate values than remaining lines like

first line : a,b,c
second line : x,y,z,a
third line : s,d,f,g

When i use RowFileInputReader with DelimitedRowFilter, i am getting following error

 **Error occurred while executing filter 'DelimitedRowFilter' on record='[name: message, type: STRING, value: 1,2,3,4, name: headers, type: ARRAY, value: [a,b,c]]' (io.streamthoughts.kafka.connect.filepulse.filter.DefaultRecordFilterPipeline:180)**

May i know how to handle this situation?

**Comment by mohai-kafka** [comment]
Below my config.

{
  "name": "test123",
  "config": {
    "cleaner.output.failed.path": "/mnt/nexus-kafka-connect/platform/archive",
    "cleaner.output.succeed.path": "/mnt/nexus-kafka-connect/platform/archive",
    "connector.class": "io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector",
        "filters": "DelimitedRowFilter",
    "fs.cleanup.policy.class": "io.streamthoughts.kafka.connect.filepulse.clean.MoveCleanupPolicy",
    "fs.scan.directory.path": "${XXXX:/opt/kafka/confluent/secret/filepulse.properties:mount.base.dir}/platform",
    "fs.scan.filters": "io.streamthoughts.kafka.connect.filepulse.scanner.local.filter.RegexFileListFilter",
    "fs.scan.interval.ms": 300000,
    "fs.scanner.class": "io.streamthoughts.kafka.connect.filepulse.scanner.local.LocalFSDirectoryWalker",
    "internal.kafka.reporter.bootstrap.servers": "${XXXX:/opt/kafka/confluent/secret/filepulse.properties:bootstrap.servers}",
    "internal.kafka.reporter.consumer.sasl.jaas.config": "${XXXX:/opt/kafka/confluent/secret/filepulse.properties:sasl.jaas.config}",
    "internal.kafka.reporter.consumer.sasl.mechanism": "${XXXX:/opt/kafka/confluent/secret/filepulse.properties:sasl.mechanism}",
    "internal.kafka.reporter.consumer.security.protocol": "${XXXX:/opt/kafka/confluent/secret/filepulse.properties:security.protocol}",
    "internal.kafka.reporter.consumer.ssl.endpoint.identification.algorithm": "${XXXX:/opt/kafka/confluent/secret/filepulse.properties:identification.algorithm}",
    "internal.kafka.reporter.id": "test123",
    "internal.kafka.reporter.producer.sasl.jaas.config": "${XXXX:/opt/kafka/confluent/secret/filepulse.properties:sasl.jaas.config}",
    "internal.kafka.reporter.producer.sasl.mechanism": "${XXXX:/opt/kafka/confluent/secret/filepulse.properties:sasl.mechanism}",
    "internal.kafka.reporter.producer.security.protocol": "${XXXX:/opt/kafka/confluent/secret/filepulse.properties:security.protocol}",
    "internal.kafka.reporter.producer.ssl.endpoint.identification.algorithm": "${XXXX:/opt/kafka/confluent/secret/filepulse.properties:identification.algorithm}",
    "internal.kafka.reporter.topic": "devc-connect-file-pulse-status",
    "offset.strategy": "name+hash+lastModified",
    "skip.headers": 1,
    "task.reader.class": "io.streamthoughts.kafka.connect.filepulse.reader.RowFileInputReader",
    "tasks.max": 1,
    "topic": "sampleTopic",
        "filters.DelimitedRowFilter.autoGenerateColumnNames": false,
    "filters.DelimitedRowFilter.extractColumnName": "headers",
    "filters.DelimitedRowFilter.separator": ",",
    "filters.DelimitedRowFilter.trimColumn": true,
    "filters.DelimitedRowFilter.type": "io.streamthoughts.kafka.connect.filepulse.filter.DelimitedRowFilter",
        "file.filter.regex.pattern":".*\\.csv$"
        }
}

**Comment by fhussonnois** [comment]
The complete error is `Error while reading delimited input row. Too large number of fields (4)`. Basically, you can't use the header line to name your field. You should either use the `autoGenerateColumnNames` property or the `columns` property to specify the column names.

**Comment by mohai-kafka** [comment]
I tried autoGenerateColumnNames : true with below config and file content. getting below error.

Config : 
 {
"name": "test123",
"config": {
"cleaner.output.failed.path": "/mnt/nexus-kafka-connect/platform/archive",
"cleaner.output.succeed.path": "/mnt/nexus-kafka-connect/platform/archive",
"connector.class": "io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector",
"filters": "DelimitedRowFilter",
"fs.cleanup.policy.class": "io.streamthoughts.kafka.connect.filepulse.clean.MoveCleanupPolicy",
"fs.scan.directory.path": "${XXXX:/opt/kafka/confluent/secret/filepulse.properties:mount.base.dir}/platform",
"fs.scan.filters": "io.streamthoughts.kafka.connect.filepulse.scanner.local.filter.RegexFileListFilter",
"fs.scan.interval.ms": 300000,
"fs.scanner.class": "io.streamthoughts.kafka.connect.filepulse.scanner.local.LocalFSDirectoryWalker",
"internal.kafka.reporter.bootstrap.servers": "${XXXX:/opt/kafka/confluent/secret/filepulse.properties:bootstrap.servers}",
"internal.kafka.reporter.consumer.sasl.jaas.config": "${XXXX:/opt/kafka/confluent/secret/filepulse.properties:sasl.jaas.config}",
"internal.kafka.reporter.consumer.sasl.mechanism": "${XXXX:/opt/kafka/confluent/secret/filepulse.properties:sasl.mechanism}",
"internal.kafka.reporter.consumer.security.protocol": "${XXXX:/opt/kafka/confluent/secret/filepulse.properties:security.protocol}",
"internal.kafka.reporter.consumer.ssl.endpoint.identification.algorithm": "${XXXX:/opt/kafka/confluent/secret/filepulse.properties:identification.algorithm}",
"internal.kafka.reporter.id": "test123",
"internal.kafka.reporter.producer.sasl.jaas.config": "${XXXX:/opt/kafka/confluent/secret/filepulse.properties:sasl.jaas.config}",
"internal.kafka.reporter.producer.sasl.mechanism": "${XXXX:/opt/kafka/confluent/secret/filepulse.properties:sasl.mechanism}",
"internal.kafka.reporter.producer.security.protocol": "${XXXX:/opt/kafka/confluent/secret/filepulse.properties:security.protocol}",
"internal.kafka.reporter.producer.ssl.endpoint.identification.algorithm": "${XXXX:/opt/kafka/confluent/secret/filepulse.properties:identification.algorithm}",
"internal.kafka.reporter.topic": "devc-connect-file-pulse-status",
"offset.strategy": "name+hash+lastModified",
"skip.headers": 1,
"task.reader.class": "io.streamthoughts.kafka.connect.filepulse.reader.RowFileInputReader",
"tasks.max": 1,
"topic": "sampleTopic",
"filters.DelimitedRowFilter.autoGenerateColumnNames": true,
"filters.DelimitedRowFilter.extractColumnName": "headers",
"filters.DelimitedRowFilter.separator": ",",
"filters.DelimitedRowFilter.trimColumn": true,
"filters.DelimitedRowFilter.type": "io.streamthoughts.kafka.connect.filepulse.filter.DelimitedRowFilter",
"file.filter.regex.pattern":".*\.csv$"
}
}

File content :
a,b,c
1,2,3,4

Error : 

[2021-09-01 17:24:17,038] ERROR [test1234|task-0] Error occurred while executing filter 'DelimitedRowFilter' on record='[name: message, type: STRING, value: 1,2,3,4, name: headers, type: ARRAY, value: [a,b,c]]' (io.streamthoughts.kafka.connect.filepulse.filter.DefaultRecordFilterPipeline:180)
[2021-09-01 17:24:17,038] ERROR [test1234|task-0] Error while processing source file '[name='a.csv', path='/mnt/nexus-kafka-connect/platform', size=14, lastModified=1630466461000, inode=109, hash=1282812824]' (io.streamthoughts.kafka.connect.filepulse.source.KafkaFileStateReporter:120)
io.streamthoughts.kafka.connect.filepulse.filter.FilterException: Error while reading delimited input row. Too large number of fields (4)

**Comment by fhussonnois** [comment]
you should remove the `"filters.DelimitedRowFilter.extractColumnName": "headers"` property.

**Comment by fhussonnois** [comment]
Yes, you have removed the header-line from the CSV file but you still have `"skip.headers": 1`.

**Comment by mohai-kafka** [comment]
@fhussonnois Thanks. But my requirement is i need all the rows including first row. Could you please let me know.

**Comment by fhussonnois** [comment]
Hi @mohai-kafka, if your file content is :

```
first line : a,b,c
second line : x,y,z,a
third line : s,d,f,g
``` 

Then configuration should be : 
```
"task.reader.class": "io.streamthoughts.kafka.connect.filepulse.reader.RowFileInputReader",
"skip.headers": 1,
"filters.DelimitedRowFilter.autoGenerateColumnNames": true,
"filters.DelimitedRowFilter.separator": ",",
"filters.DelimitedRowFilter.trimColumn": true,
"filters.DelimitedRowFilter.type": "io.streamthoughts.kafka.connect.filepulse.filter.DelimitedRowFilter",
```

you will get : 

```
{"column1":"x","column2":"y","column3":"z","column4":"a"}
{"column1":"s","column2":"d","column3":"f","column4":"g"}
```

if `"skip.headers": 0,`

Then, you will get : 

```
{"column1":"a","column2":"b","column3":"c"}
{"column1":"x","column2":"y","column3":"z","column4":"a"}
{"column1":"s","column2":"d","column3":"f","column4":"g"}
```

**Comment by mohai-kafka** [comment]
@fhussonnois Thanks for the input. When i provide "skip.headers":0 I am getting below error.

File Content : 
a,b,c
1,2,3,4

Config : 

    "task.reader.class": "io.streamthoughts.kafka.connect.filepulse.reader.RowFileInputReader",
    "skip.headers": 0,
    "tasks.max": 1,
    "topic": "sampleTopic",
    "filters.DelimitedRowFilter.autoGenerateColumnNames": true,
    "filters.DelimitedRowFilter.separator": ",",
    "filters.DelimitedRowFilter.trimColumn": true,
    "filters.DelimitedRowFilter.type": "io.streamthoughts.kafka.connect.filepulse.filter.DelimitedRowFilter",
    "file.filter.regex.pattern":".*\\.csv$"

Error : 

[2021-09-02 07:37:30,773] ERROR [test-mohaideen|task-0] Error occurred while executing filter 'DelimitedRowFilter' on record='[name: message, type: STRING, value: 1,2,3,4]' (io.streamthoughts.kafka.connect.filepulse.filter.DefaultRecordFilterPipeline:180)
[2021-09-02 07:37:30,774] ERROR [test-mohaideen|task-0] Error while processing source file '[name='a.csv', path='/mnt/nexus-kafka-connect/platform', size=14, lastModified=1630582640000, inode=136, hash=1282812824]' (io.streamthoughts.kafka.connect.filepulse.source.KafkaFileStateReporter:120)
io.streamthoughts.kafka.connect.filepulse.filter.FilterException: Error while reading delimited input row. Too large number of fields (4)
        at io.streamthoughts.kafka.connect.filepulse.filter.DelimitedRowFilter.buildStructForFields(DelimitedRowFilter.java:133)
        at io.streamthoughts.kafka.connect.filepulse.filter.DelimitedRowFilter.apply(DelimitedRowFilter.java:96)
        at io.streamthoughts.kafka.connect.filepulse.filter.DefaultRecordFilterPipeline$FilterNode.apply(DefaultRecordFilterPipeline.java:159)
        at io.streamthoughts.kafka.connect.filepulse.filter.DefaultRecordFilterPipeline.apply(DefaultRecordFilterPipeline.java:131)
        at io.streamthoughts.kafka.connect.filepulse.filter.DefaultRecordFilterPipeline.apply(DefaultRecordFilterPipeline.java:99)
        at io.streamthoughts.kafka.connect.filepulse.source.DefaultFileRecordsPollingConsumer.next(DefaultFileRecordsPollingConsumer.java:169)
        at io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceTask.poll(FilePulseSourceTask.java:127)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:289)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:256)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:185)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:235)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by fhussonnois** [comment]
Hi @mohai-kafka, I've found that the filter only computes  the schema based on the first line.
I released Connect FilePulse 2.4.0 that fixes that issue.

**Comment by mohai-kafka** [comment]
@fhussonnois Thanks for the response. you mean 2.3.0?

**Comment by fhussonnois** [comment]
Hi @mohai-kafka , Yes 2.3.0 sorry for that mistake ^^.
