### ISSUE TITLE
File Pulse Connector is installed but getting error that class not found when adding new connector config from postman .

### ISSUE THREAD

**Issue by bksinha4497** [streamthoughts/kafka-connect-file-pulse#173]
Installed the connector using : 
> confluent-hub install streamthoughts/kafka-connect-file-pulse:2.0.0
Added the  pluigin path in connect-avro-standalone config
> plugin.path=share/java,/opt/emagine/confluent/confluent-service/share/confluent-hub-components

Verified the connector is loading : 

> [2021-09-13 16:39:26,396] INFO Loading plugin from: /opt/emagine/confluent/confluent-service/share/confluent-hub-components/streamthoughts-kafka-connect-file-pulse (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:246)

but getting error : 

Failed to find any class that implements Connector and which name matches io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector, available connectors are: PluginDesc{klass=class io.confluent.connect.jdbc.JdbcSinkConnector, name='io.confluent.connect.jdbc.JdbcSinkConnector', version='10.0.2', encodedVersion=10.0.2, type=sink, typeName='sink', location='file:/opt/emagine/confluent/confluent-service/share/confluent-hub-components/confluentinc-kafka-connect-jdbc/'}, PluginDesc{klass=class io.confluent.connect.jdbc.JdbcSourceConnector, name='io.confluent.connect.jdbc.JdbcSourceConnector', version='10.0.2', encodedVersion=10.0.2, type=source, typeName='source', location='file:/opt/emagine/confluent/confluent-service/share/confluent-hub-components/confluentinc-kafka-connect-jdbc/'}, PluginDesc{klass=class org.apache.kafka.connect.file.FileStreamSinkConnector, name='org.apache.kafka.connect.file.FileStreamSinkConnector', version='6.1.0-ccs', encodedVersion=6.1.0-ccs, type=sink, typeName='sink', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.file.FileStreamSourceConnector, name='org.apache.kafka.connect.file.FileStreamSourceConnector', version='6.1.0-ccs', encodedVersion=6.1.0-ccs, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.mirror.MirrorCheckpointConnector, name='org.apache.kafka.connect.mirror.MirrorCheckpointConnector', version='1', encodedVersion=1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.mirror.MirrorHeartbeatConnector, name='org.apache.kafka.connect.mirror.MirrorHeartbeatConnector', version='1', encodedVersion=1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.mirror.MirrorSourceConnector, name='org.apache.kafka.connect.mirror.MirrorSourceConnector', version='1', encodedVersion=1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockConnector, name='org.apache.kafka.connect.tools.MockConnector', version='6.1.0-ccs', encodedVersion=6.1.0-ccs, type=connector, typeName='connector', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockSinkConnector, name='org.apache.kafka.connect.tools.MockSinkConnector', version='6.1.0-ccs', encodedVersion=6.1.0-ccs, type=sink, typeName='sink', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockSourceConnector, name='org.apache.kafka.connect.tools.MockSourceConnector', version='6.1.0-ccs', encodedVersion=6.1.0-ccs, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.SchemaSourceConnector, name='org.apache.kafka.connect.tools.SchemaSourceConnector', version='6.1.0-ccs', encodedVersion=6.1.0-ccs, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.VerifiableSinkConnector, name='org.apache.kafka.connect.tools.VerifiableSinkConnector', version='6.1.0-ccs', encodedVersion=6.1.0-ccs, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.VerifiableSourceConnector, name='org.apache.kafka.connect.tools.VerifiableSourceConnector', version='6.1.0-ccs', encodedVersion=6.1.0-ccs, type=source, typeName='source', location='classpath'}"

**Comment by fhussonnois** [comment]
Hi @bksinha4497,

Can you confirm that under the path `/opt/emagine/confluent/confluent-service/share/confluent-hub-components` you have a directory named `streamthoughts-kafka-connect-file-pulse` ?

Also, can you copy paste the output of the following command : 

```bash
(cd /opt/emagine/confluent/confluent-service/share/confluent-hub-components;  ls streamthoughts-kafka-connect-file-pulse/lib/ | grep pulse)
```

thanks!

**Comment by bksinha4497** [comment]
Hi @fhussonnois 
Yes under the directory `/opt/emagine/confluent/confluent-service/share/confluent-hub-components` There is a directory `streamthoughts-kafka-connect-file-pulse`

Here is the output of the command : 
`[cloud-user@cvs-autodeploy confluent-hub-components]$ cd /opt/emagine/confluent/confluent-service/share/confluent-hub-components;  ls streamthoughts-kafka-connect-file-pulse/lib/ | grep pulse
kafka-connect-filepulse-amazons3-fs-2.0.0.jar
kafka-connect-file-pulse-api-2.0.0.jar
kafka-connect-filepulse-azure-storage-fs-2.0.0.jar
kafka-connect-filepulse-commons-fs-2.0.0.jar
kafka-connect-file-pulse-expression-2.0.0.jar
kafka-connect-file-pulse-filters-2.0.0.jar
kafka-connect-filepulse-google-cloud-storage-fs-2.0.0.jar
kafka-connect-filepulse-local-fs-2.0.0.jar
kafka-connect-file-pulse-plugin-2.0.0.jar`

**Comment by fhussonnois** [comment]
Ok, it's surprising that Kafka Connect doesn't find the class  `io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector` which should be in `kafka-connect-file-pulse-plugin-2.0.0.jar`.

Did you restart the connect-worker after installing the plugin. Then, did you update all the connect-workers (if you are in distributed mode) ? 

One more thing, could you confirm me that your worker is configured with `plugin.path=share/java,/opt/emagine/confluent/confluent-service/share/confluent-hub-components` ?

**Comment by bksinha4497** [comment]
yes , I did restart the connect=worker after installing the plugin and its running in stand alone mode .

The worker is configured with  `plugin.path=share/java,/opt/emagine/confluent/confluent-service/share/confluent-hub-components`

**Comment by sscots** [comment]
Having the same issue. It worked on version 1.6.3, then moved to 2.0.0 and started getting this error.

**Comment by cgaege** [comment]
Hi @fhussonnois,

I'm having the same issue. I installed FilePulse 2.4 in a custom Kafka `connect` 2.8.1 docker image using `confluent-hub`:

```
root@aa19afeb6633:/opt/kafka# /opt/confluent-hub-client-latest/bin/confluent-hub install streamthoughts/kafka-connect-file-pulse:2.4.0 --component-dir /base-plugins/ --worker-configs /opt/kafka/config/connect-distributed.properties 
 
Component's license: 
The Apache Software License, Version 2.0 
http://www.apache.org/licenses/LICENSE-2.0.txt 
I agree to the software license agreement (yN) y

You are about to install 'kafka-connect-file-pulse' from StreamThoughts, as published on Confluent Hub. 
Do you want to continue? (yN) y

Downloading component Kafka Connect File Pulse 2.4.0, provided by StreamThoughts from Confluent Hub and installing into /base-plugins/ 
Do you want to uninstall existing version 2.4.0? (yN) y

Adding installation directory to plugin path in the following files: 
  /opt/kafka/config/connect-distributed.properties 
 
Completed 
```
But the connector plugin is not listed (after a restart of the `connect` container):

`curl http://connect:8085/connector-plugins | grep FilePulseSourceConnector ` 

`Plugin.path` in `/opt/kafka/config/connect-distributed.properties` seems to be OK:

`plugin.path=/plugins,/base-plugins`

File permission on the plugin directories are set properly.

Best regards,
Christian

**Comment by fhussonnois** [comment]
Hi @cgaege, are you using a confluent base image ? Can you plese check the `plugin.path` property which is logged by the worker when starting ? Maybe there is something related to this issue : https://github.com/confluentinc/cp-docker-images/issues/818 ?

**Comment by cgaege** [comment]
Hi @fhussonnois, actually I'm using self-made Kafka images, based on openjdk and Kafka Connect 2.8.1. We added some of the confluent tooling (like the `confluent-hub-client`) to the `connect` container to simplify the installation of our self-developed connect plugins. Other connect plugins like the [JDBC source connector](https://docs.confluent.io/kafka-connect-jdbc/current/index.html) are working fine without any issues.

The `plugin.path` property in the log seems to be correct:

```
docker logs -f connect | grep plugin.path
plugin.path = [/plugins, /base-plugins]
[2021-11-03 11:37:17,291] WARN The configuration 'plugin.path' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig:380)
[2021-11-03 11:37:19,000] WARN The configuration 'plugin.path' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig:380)
```
However, I'm a bit confused about the warning that `plugin.path` isn't a known config.

**Comment by muchemiphilip** [comment]
I'm also having the same issue. 
Has anyone solved this error? 
If so, kindly assist me.

**Comment by cgaege** [comment]
@muchemiphilip I was not able to solve the issue

**Comment by fhussonnois** [comment]
Hi @muchemiphilip, could you please share some information about your running environment: 

* Connect FilePulse version: ???
* Kafka Connect version: ???
* Plugin Installation mode: ???
** i.e., confluent-hub, confluent-cli with a zip tarball, manual installation (i.e. plugin is manually unzip and install on the connect-workers).

Below is a checklist you can use to ensure that ConnectFilePulse is properly installed:
- [ ] Check that the `plugin.paths` is configured on all Kafka Connect workers. 
- [ ] Check that  the connector was installed on all Kafka Connect workers.
**i.e., a directory named `streamthoughts-kafka-connect-file-pulse` should exist under one of the configured `plugin.paths`
- [ ] Check that there is no missing JARs  : 
```bash
$ (cd /YOUR/PLUGIN/PATHS;  ls streamthoughts-kafka-connect-file-pulse/lib/ | grep pulse)
kafka-connect-filepulse-amazons3-fs-2.x.x.jar
kafka-connect-file-pulse-api-2.x.x.jar
kafka-connect-filepulse-azure-storage-fs-2.x.x.jar
kafka-connect-filepulse-commons-fs-2.x.x.jar
kafka-connect-file-pulse-expression-2.x.x.jar
kafka-connect-file-pulse-filters-2.x.x.jar
kafka-connect-filepulse-google-cloud-storage-fs-2.x.x.jar
kafka-connect-filepulse-local-fs-2.x.x.jar
kafka-connect-file-pulse-plugin-2.x.x.jar
```
- [ ] Check that all JARs installed under the `./kafka-connect-file-pulse/lib/` directory are readable.
- [ ] Check that the plugin is loaded from the Connect Worker logs, you see someting similar to : 
```
INFO Loading plugin from: /usr/local/share/kafka/plugins/streamthoughts-kafka-connect-file-pulse (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
INFO Registered loader: PluginClassLoader{pluginLocation=file:/usr/local/share/kafka/plugins/streamthoughts-kafka-connect-file-pulse/} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
INFO Added plugin 'io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
INFO Added plugin 'io.streamthoughts.kafka.connect.transform.Grok$Value' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
INFO Added plugin 'io.streamthoughts.kafka.connect.transform.Grok$Key' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
....
INFO Added aliases 'FilePulseSourceConnector' and 'FilePulseSource' to plugin 'io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
```
- [ ] Check that plugin is listed from the following Kafka Connect REST endpoint : 
```bash
$ curl http://connect:8085/connector-plugins | grep FilePulseSourceConnector
```

Thanks.

**Comment by ayumin** [comment]
I had similar problem with Java 8, however it looks work well on Java 11.

**Comment by tafsuth** [comment]
Hello @fhussonnois 
I have a similar issue, and I can't easily switch to using java 11. 
Is it possible to make the last release of the connector work with java 8 ?

**Comment by cgaege** [comment]
I can confirm that on Java 11 the connector can be installed without any issues.

**Comment by saberedo** [comment]
Thanks guys. I had similar issue runing on java 8, got resolved when I used java 11.
