### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by mh-github** [streamthoughts/kafka-connect-file-pulse#18]
[INFO] Running io.streamthoughts.kafka.connect.filepulse.source.SourceMetadataTest
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.013 s <<< FAILURE! - in io.streamthoughts.kafka.connect.filepulse.source.SourceMetadataTest
[ERROR] shouldCreateSourceMetadataGivenFile(io.streamthoughts.kafka.connect.filepulse.source.SourceMetadataTest)  Time elapsed: 0.001 s  <<< FAILURE!
java.lang.AssertionError
        at io.streamthoughts.kafka.connect.filepulse.source.SourceMetadataTest.shouldCreateSourceMetadataGivenFile(SourceMetadataTest.java:54)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   SourceMetadataTest.shouldCreateSourceMetadataGivenFile:54
[INFO]
[ERROR] Tests run: 71, Failures: 1, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Kafka Connect Source File Pulse Reactor 1.3.0-SNAPSHOT:
[INFO]
[INFO] Kafka Connect Source File Pulse Reactor ............ SUCCESS [  2.729 s]
[INFO] Kafka Connect Source File Pulse APIs ............... FAILURE [ 14.384 s]
[INFO] Kafka Connect Source File Pulse Filters ............ SKIPPED
[INFO] Kafka Connect Source File Pulse Plugin ............. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  17.763 s
[INFO] Finished at: 2020-01-19T23:21:08+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M3:test (default-test) on project kafka-connect-file-pulse-api: There are test failures.

**Comment by fhussonnois** [comment]
Please, could you provide information about your execution environment (java, maven, OS) ? 

Thank you.

**Comment by mh-github** [comment]
OS = Windows 10
I run my commands in Cmder window.

λ java -version
java version "11.0.6" 2020-01-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.6+8-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.6+8-LTS, mixed mode)

λ mvn --version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: C:\ProgramData\chocolatey\lib\maven\apache-maven-3.6.3\bin\..
Java version: 11.0.6, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-11.0.6
Default locale: en_IN, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

λ git clone https://github.com/streamthoughts/kafka-connect-file-pulse.git
λ cd kafka-connect-file-pulse
λ mvn clean package

**Comment by fhussonnois** [comment]
Thank you, currenlty kafka-connect-file-pulse is not tested under Windows environment.

I've just merge a fix for the test that was failing. Now, you shoud be able to build te project.

If you find any new build issue a recomand to skip the tests on Windows: `mvn clean package -DskipTests`

Thanks to close this issue if the problem is fixed.

**Comment by mh-github** [comment]
Some tests are failing 
[ERROR] Tests run: 38, Failures: 14, Errors: 0, Skipped: 0

But with -DskipTests the project builds fine.
