### ISSUE TITLE
Unable to use it on Confluent Cloud 

### ISSUE THREAD

**Issue by kjang1750** [streamthoughts/kafka-connect-file-pulse#180]
Hi!

I am having some trouble using the Connector via Confluent Cloud. I tried following the guide here https://rmoff.net/2021/03/26/loading-csv-data-into-confluent-cloud-using-the-filepulse-connector/ but I am still unable to have my connector launched. It works well on my on premise when I launch Kafka on my own computer though. My settings are below. 

{
  "config": {
  "connector.class": "io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector",
    "tasks.reader.class": "io.streamthoughts.kafka.connect.filepulse.fs.reader.LocalRowFileInputReader",
  "fs.cleanup.policy.class": "io.streamthoughts.kafka.connect.filepulse.fs.clean.DeleteCleanupPolicy",
  "fs.listing.class": "io.streamthoughts.kafka.connect.filepulse.fs.LocalFSDirectoryListing",
  "fs.listing.directory.path": "/tmp/kafka-connect/examples/",
  "fs.listing.interval.ms": "10000",
  "internal.kafka.reporter.bootstrap.servers": "broker:9092",
  "internal.kafka.reporter.topic": "connect-file-pulse-status",
  "offset.attributes.string": "name+hash",
  "skip.headers": "1",
  "topic": "connect-file-pulse-quickstart-csv",
  "tasks.file.status.storage.bootstrap.servers": "broker:9092",
  "tasks.max": 1,
  "internal.kafka.reporter.producer.security.protocol": "SASL_SSL",
  "internal.kafka.reporter.producer.ssl.endpoint.identification.algorithm": "https",
  "internal.kafka.reporter.producer.sasl.mechanism": "PLAIN",
   "internal.kafka.reporter.producer.sasl.jaas.config": "${azure:kv-kafka-dev-001:kafka-sasl-jaas-config-dev}",
"internal.kafka.reporter.consumer.security.protocol": "SASL_SSL",
"internal.kafka.reporter.consumer.ssl.endpoint.identification.algorithm": "https",
"internal.kafka.reporter.consumer.sasl.mechanism": "PLAIN",
"internal.kafka.reporter.consumer.sasl.jaas.config": "${azure:kv-kafka-dev-001:kafka-sasl-jaas-config-dev}"
  },
  "name": "connect-file-pulse-quickstart-csv"
}

We run our Kafka Connect on Kubernetes using Confluent Operator. Does anyone know what I may be missing in order to successfully have it run?

**Comment by kjang1750** [comment]
Update: The connector has evolved since Robin Moffet's tutorial. The following configurations will allow these configurations to be deployed

{
  "name": "connect-file-pulse-quickstart-csv",
  "config": {
    "connector.class": "io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector",
    "tasks.max": "1",
    "fs.listing.class": "io.streamthoughts.kafka.connect.filepulse.fs.LocalFSDirectoryListing",
    "tasks.reader.class": "io.streamthoughts.kafka.connect.filepulse.fs.reader.LocalRowFileInputReader",
    "topic": "connect-file-pulse-quickstart-csv",
    "fs.listing.interval.ms": "10000",
    "fs.cleanup.policy.class": "io.streamthoughts.kafka.connect.filepulse.fs.clean.DeleteCleanupPolicy",
    "fs.listing.directory.path": "/tmp/kafka-connect/examples/",
    "skip.headers": "1",
    "tasks.file.status.storage.producer.sasl.jaas.config": "${azure:kv-kafka-dev-001:kafka-sasl-jaas-config-dev}",
    "tasks.file.status.storage.consumer.sasl.jaas.config": "${azure:kv-kafka-dev-001:kafka-sasl-jaas-config-dev}",
    "tasks.file.status.storage.consumer.ssl.endpoint.identification.algorithm": "https",
    "tasks.file.status.storage.producer.ssl.endpoint.identification.algorithm": "https",
    "tasks.file.status.storage.bootstrap.servers": "broker:9092",
    "internal.kafka.reporter.topic": "connect-file-pulse-status",
    "offset.attributes.string": "name+hash",
    "tasks.file.status.storage.consumer.security.protocol": "SASL_SSL",
    "tasks.file.status.storage.consumer.sasl.mechanism": "PLAIN",
    "tasks.file.status.storage.producer.security.protocol": "SASL_SSL",
    "tasks.file.status.storage.producer.sasl.mechanism": "PLAIN"
  }
}

**Comment by fhussonnois** [comment]
I close this issue as it has been resolved. Thanks!

**Comment by kjang1750** [comment]
Awesome sounds good! Appreciate it :)
