### ISSUE TITLE
Unable to have it in Running within Azure Blob Storage

### ISSUE THREAD

**Issue by kjang1750** [streamthoughts/kafka-connect-file-pulse#181]
Hey all,

In my File Pulse Connector I have the following configurations. I am using 2.3.0. We use Confluent Cloud and have our Kafka Connect running on Confluent for Kubernetes (CFK). CFK and our Kafka Connect authenticates onto Confluent Cloud. 

   "tasks.reader.class": "io.streamthoughts.kafka.connect.filepulse.fs.AzureBlobStorageConfig",
  "fs.listing.class": "io.streamthoughts.kafka.connect.filepulse.fs.AzureBlobStorageFileSystemListing",

When putting it in the rest API, I am getting the following error 

    "message": "Connector configuration is invalid and contains the following 2 error(s):\nInvalid value io.streamthoughts.kafka.connect.filepulse.fs.AzureBlobStorageFileSystemListing for configuration fs.listing.class: Class io.streamthoughts.kafka.connect.filepulse.fs.AzureBlobStorageFileSystemListing could not be found.\nInvalid value io.streamthoughts.kafka.connect.filepulse.fs.AzureBlobStorageConfig for configuration tasks.reader.class: Class io.streamthoughts.kafka.connect.filepulse.fs.AzureBlobStorageConfig could not be found.\nYou can also find the above list of errors at the endpoint `/connector-plugins/{connectorType}/config/validate`"

I ended up putting an on premise Kafka on my local machine to test things out. 

   "tasks.reader.class": "io.streamthoughts.kafka.connect.filepulse.fs.AzureBlobStorageConfig",
  "fs.listing.class": "io.streamthoughts.kafka.connect.filepulse.fs.AzureBlobStorageFileSystemListing",

I was able to create the connector. 

Compared to our local, on Confluent Cloud, we do have a bunch of other connectors. Meanwhile, on our Confluent Cloud that leverages CFK, we installed it via the confluent-hub CLI whereas on my on premise machine, I simply had the connector built when running the docker compose. 

confluent-hub install streamthoughts/kafka-connect-file-pulse:2.3.0

Has anyone had this issue before? I followed the documentation thoroughly and it seems to be a bit odd.

**Comment by kjang1750** [comment]
Hi  @fhussonnois 

I tried making the adjustments but I am still getting an issue with class not found

{
  "config": {
  "connector.class": "io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector",
   "task.reader.class": "io.streamthoughts.kafka.connect.filepulse.fs.reader.AzureBlobStorageRowFileInputReader",
  "fs.listing.class": "io.streamthoughts.kafka.connect.filepulse.fs.AzureBlobStorageFileSystemListing",
  "fs.cleanup.policy.class": "io.streamthoughts.kafka.connect.filepulse.fs.clean.DeleteCleanupPolicy",
  "fs.listing.recursive.enabled": false,
  "fs.listing.interval.ms": "10000",
    "azure.storage.account.name": "datalakestorageprod",
    "azure.storage.account.key": "<removed>",
    "azure.storage.connection.string": "<removed>",
    "azure.storage.container.name": "apps-logging-prod",
  "offset.attributes.string": "name+hash",
  "skip.headers": "1",
  "topic": "azure",
  "tasks.max": 1,
      "tasks.file.status.storage.class": "io.streamthoughts.kafka.connect.filepulse.state.KafkaFileObjectStateBackingStore",
    "tasks.file.status.storage.bootstrap.servers": "broker:9092",
    "tasks.file.status.storage.topic": "connect-file-pulse-status",
    "tasks.file.status.storage.topic.partitions": 1,
    "tasks.file.status.storage.producer.security.protocol": "SASL_SSL",
    "tasks.file.status.storage.producer.ssl.endpoint.identification.algorithm": "https",
    "tasks.file.status.storage.producer.sasl.mechanism": "PLAIN",
    "tasks.file.status.storage.producer.sasl.jaas.config": "${azure:kv-k8s-dev-001:kafka-sasl-jaas-config-dev}",
    "tasks.file.status.storage.producer.request.timeout.ms": "20000",
    "tasks.file.status.storage.producer.retry.backoff.ms": "500",
    "tasks.file.status.storage.consumer.security.protocol": "SASL_SSL",
    "tasks.file.status.storage.consumer.ssl.endpoint.identification.algorithm": "https",
    "tasks.file.status.storage.consumer.sasl.mechanism": "PLAIN",
    "tasks.file.status.storage.consumer.sasl.jaas.config": "${azure:kv-k8s-dev-001:kafka-sasl-jaas-config-dev}",
    "tasks.file.status.storage.consumer.request.timeout.ms": "20000",
    "tasks.file.status.storage.consumer.retry.backoff.ms": "500"
  },
  "name": "azuresourcestreamthoughtsconnector"
}

Is there anything that I may be doing wrong? In my local on premise Kafka machine that is not secured, running on Docker, I am able to create this connector via the following configs

{
    "config": {
    "connector.class": "io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector",
     "tasks.reader.class": "io.streamthoughts.kafka.connect.filepulse.fs.reader.AzureBlobStorageRowFileInputReader",
    "fs.listing.class": "io.streamthoughts.kafka.connect.filepulse.fs.AzureBlobStorageFileSystemListing",
    "fs.cleanup.policy.class": "io.streamthoughts.kafka.connect.filepulse.fs.clean.DeleteCleanupPolicy",
    "fs.listing.recursive.enabled": false,
    "fs.listing.interval.ms": "10000",
    "internal.kafka.reporter.bootstrap.servers": "broker:29092",
    "internal.kafka.reporter.topic": "connect-file-pulse-status",
      "azure.storage.account.name": "<removed>",
      "azure.storage.account.key": "<removed>",
      "azure.storage.connection.string": "<removed>",
      "azure.storage.container.name": "<removed>",
    "offset.attributes.string": "name+hash",
    "skip.headers": "1",
    "topic": "azure",
    "tasks.file.status.storage.bootstrap.servers": "broker:29092",
    "tasks.file.status.storage.class": "io.streamthoughts.kafka.connect.filepulse.state.KafkaFileObjectStateBackingStore",
    "tasks.max": 1
    },
    "name": "azure-local"
  }

My docker-compose.yml is here

version: '3'
services:
  cp-zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
    - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  cp-broker:
    image: confluentinc/cp-kafka:latest
    hostname: broker
    container_name: broker
    depends_on:
    - cp-zookeeper
    ports:
    - "29092:29092"
    - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker:29092
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'false'

  cp-schema-registry:
    image: confluentinc/cp-schema-registry:6.2.0
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
    - cp-zookeeper
    - cp-broker
    ports:
    - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'

  connect-file-pulse:
    image: streamthoughts/kafka-connect-file-pulse:latest
    container_name: connect
    depends_on:
    - cp-broker
    - cp-schema-registry
    ports:
    - "8083:8083"
    - "8000:8000"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: 'broker:29092'
      CONNECT_REST_ADVERTISED_HOST_NAME: connect
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: compose-connect-group
      CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_FLUSH_INTERVAL_MS: 10000
      CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      # kafka-connect-file-pulse is installed as a confluent-hub component
      CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components/"
      CONNECT_LOG4J_ROOT_LOGLEVEL: "INFO"
      # CONNECT_LOG4J_LOGGERS: io.streamthoughts=DEBUG,org.apache.zookeeper=ERROR,org.I0Itec.zkclient=ERROR,org.reflections=ERROR
      # Uncomment for debugging the connector during development cycle
      # KAFKA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,address=8000,suspend=n"
    volumes:
      - ./connect-data:/tmp/connect-data

**Comment by kjang1750** [comment]
Update: I used two "docker-compose.yml" files. On one instance, I was able to create an Azure Connector while on the other instance, I had the same issue as seen above. 

When using the confluent-hub to install plugins listed below, I am unable to create an Azure Connector with the class not being found below

"message": "Connector configuration is invalid and contains the following 2 error(s):\nInvalid value io.streamthoughts.kafka.connect.filepulse.fs.AzureBlobStorageFileSystemListing for configuration fs.listing.class: Class io.streamthoughts.kafka.connect.filepulse.fs.AzureBlobStorageFileSystemListing could not be found.\nInvalid value io.streamthoughts.kafka.connect.filepulse.fs.AzureBlobStorageConfig for configuration tasks.reader.class: Class io.streamthoughts.kafka.connect.filepulse.fs.AzureBlobStorageConfig could not be found.\nYou can also find the above list of errors at the endpoint `/connector-plugins/{connectorType}/config/validate`"

Configurations include 

  kafka-connect:
    image: confluentinc/cp-kafka-connect-base:6.2.0
    container_name: kafka-connect
    depends_on:
      - broker
      - schema-registry
    ports:
      - 8083:8083
    environment:
      CONNECT_BOOTSTRAP_SERVERS: "broker:29092"
      CONNECT_REST_ADVERTISED_HOST_NAME: "kafka-connect"
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: kafka-connect
      CONNECT_CONFIG_STORAGE_TOPIC: _kafka-connect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: _kafka-connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: _kafka-connect-status
      CONNECT_KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'
      CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_LOG4J_ROOT_LOGLEVEL: "INFO"
      CONNECT_LOG4J_LOGGERS: "org.apache.kafka.connect.runtime.rest=WARN,org.reflections=ERROR"
      CONNECT_LOG4J_APPENDER_STDOUT_LAYOUT_CONVERSIONPATTERN: "[%d] %p %X{connector.context}%m (%c:%L)%n"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_PLUGIN_PATH: '/usr/share/java,/usr/share/confluent-hub-components/,/connectors/'
      # If you want to use the Confluent Hub installer to d/l component, but make them available
      # when running this offline, spin up the stack once and then run : 
      #   docker cp kafka-connect:/usr/share/confluent-hub-components ./connectors
      #   mv ./connectors/confluent-hub-components/* ./connectors
      #   rm -rf ./connectors/confluent-hub-components
    volumes:
      - $PWD/connectors:/connectors
    # In the command section, $ are replaced with $$ to avoid the error 'Invalid interpolation format for "command" option'
    command: 
      - bash 
      - -c 
      - |
        echo "Installing connector plugins"
        # Check latest version here: https://www.confluent.io/hub/confluentinc/kafka-connect-elasticsearch
        confluent-hub install --no-prompt confluentinc/kafka-connect-elasticsearch:11.0.1
        confluent-hub install --no-prompt streamthoughts/kafka-connect-file-pulse:2.3.0 
        #
        echo "Launching Kafka Connect worker"
        /etc/confluent/docker/run & 
        #
        sleep infinity


On the contrary, where I was able to create the File Pulse Source Connector with Azure, I had these configurations when installing the connector in the "docker-compose.yml"

  connect-file-pulse:
    image: streamthoughts/kafka-connect-file-pulse:latest
    container_name: connect
    depends_on:
    - cp-broker
    - cp-schema-registry
    ports:
    - "8083:8083"
    - "8000:8000"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: 'broker:29092'
      CONNECT_REST_ADVERTISED_HOST_NAME: connect
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: compose-connect-group
      CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_FLUSH_INTERVAL_MS: 10000
      CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      # kafka-connect-file-pulse is installed as a confluent-hub component
      CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components/"
      CONNECT_LOG4J_ROOT_LOGLEVEL: "INFO"
      # CONNECT_LOG4J_LOGGERS: io.streamthoughts=DEBUG,org.apache.zookeeper=ERROR,org.I0Itec.zkclient=ERROR,org.reflections=ERROR
      # Uncomment for debugging the connector during development cycle
      # KAFKA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,address=8000,suspend=n"
    volumes:
      - ./connect-data:/tmp/connect-data        


Is there anything that may need to be adjusted when installing the connector from confluent-hub?

**Comment by fhussonnois** [comment]
Hi @kjang1750, it seems that connect file 2.3 available on confluent-hub does not contain the extension for Azure and other could providers, see : https://github.com/streamthoughts/kafka-connect-file-pulse/issues/182

This will be fixed in next version (2.4) that should be released very soon.

**Comment by kjang1750** [comment]
Awesome sounds good!!! Thanks for letting me know @fhussonnois
