### ISSUE TITLE
aws - issue: use the wrong value

### ISSUE THREAD

**Issue by sjeandeaux** [streamthoughts/kafka-connect-file-pulse#184]
Hi,

We are facing an issue using the 2.3.0.

Should it be endpoint instead of url at this following line?

https://github.com/streamthoughts/kafka-connect-file-pulse/blob/d76bac0ed61dc9d727160d63ac019fcc86f61cd9/connect-file-pulse-filesystems/filepulse-amazons3-fs/src/main/java/io/streamthoughts/kafka/connect/filepulse/fs/AmazonS3ClientUtils.java#L75

**Comment by fhussonnois** [comment]
Thank you very much for this issue, I'm sorry for this regression. The fix will be available in Connect FilePulse 2.4 that should be released next-week.
