### ISSUE TITLE
io.streamthoughts.kafka.connect.filepulse.fs.clean.LocalMoveCleanPolicy class not found in 2.3.x version

### ISSUE THREAD

**Issue by ChhatralaNirmal** [streamthoughts/kafka-connect-file-pulse#185]
Hi!, 
As per the documentation steps mentioned [Here](https://streamthoughts.github.io/kafka-connect-file-pulse/docs/archives/v2.3.x/developer-guide/cleaning-completed-files/) ,  when we try to setup LocalMoveCleanPolicy, 
We get class not Found exception in 2.3.X latest version. 

Where could we find this ?

**Comment by fhussonnois** [comment]
Hi @ChhatralaNirmal, the Connect FilePulse 2.3 deployed on confluent-hub seems to be broken. v2.4 will be released very soon. My apologies for this issue.

**Comment by an0nz** [comment]
The documentation for this appears to be wrong for this class as I had to take a look in the code to find the correct name.

The correct working class I found for 2.4 from confluent hub is
io.streamthoughts.kafka.connect.filepulse.fs.clean.LocalMove**Cleanup**Policy
