### ISSUE TITLE
Can't access value from another 3rd party transformation

### ISSUE THREAD

**Issue by sscots** [streamthoughts/kafka-connect-file-pulse#188]
I'm trying to create my own field from the header using this package:
https://jcustenborder.github.io/kafka-connect-documentation/projects/kafka-connect-transform-common/transformations/examples/HeaderToField.headertofield.html

`transforms.AppendServer.type=com.github.jcustenborder.kafka.connect.transform.common.HeaderToField$Value
transforms.AppendServer.header.mappings=connect.hostname:STRING:server`

However if I try to access $value.server in my filepulse filters, I don't get a value.

filters.SetKeyWithTag.type=io.streamthoughts.kafka.connect.filepulse.filter.AppendFilter
filters.SetKeyWithTag.field=$key
filters.SetKeyWithTag.value={{ concat($value.server, '-', $value.vendor, '-', $value.user, '-', $value.host, '-', $value.tag) }}
filters.SetKeyWithTag.overwrite=true

**Comment by fhussonnois** [comment]
Hi @sscots, Connect Transfomers are executed internally by the Kafka Connect framework so after the filter-chain of Connect FilePulse.

**Comment by fhussonnois** [comment]
Hi @sscots, this issue has been resolved (https://github.com/streamthoughts/kafka-connect-file-pulse/issues/189). Kafka Connect FilePulse 2.4.1 is now available.
