### ISSUE TITLE
SSL Support

### ISSUE THREAD

**Issue by dinegri** [streamthoughts/kafka-connect-file-pulse#19]
Hello

Thank you for your amazing project.

I have a kafka cluster using ssl enabled, I tried to configure kafka-connect-file-pulse using ssl, but I am not able to configure properly, I got an error message about describe metadata from a topic. I am wondering if it is a issue related to ssl suport

I did not find anything about ssl suport in documentation. Is it possible to use kafka-connect-file-pulse connector using ssl?

**Comment by fhussonnois** [comment]
Hi @dinegri, could you share your configurationn(without keyspassword) ?

Yes, connect-file-pulse works with SSL. However, this connector uses an internal topic to synchronize tasks and connector. So you have to configure SSL for both internal producer and consumer. For doing this,  you have to specifiy the kafka client properties for SSL prefixed with : 

`internal.kafka.reporter.consumer.` and  `internal.kafka.reporter.producer.`

Hope this help.

**Comment by dinegri** [comment]
Hi @fhussonnois, I followed your suggestion and it  worked perfectly.

Thank you very much
