### ISSUE TITLE
how to run Kafka-connect-file-pulse without schema registry and Zookeeper

### ISSUE THREAD

**Issue by dayawansha** [streamthoughts/kafka-connect-file-pulse#197]
Hi Guys,

I need to run Kafka-connect-file-pulse without schema registry and Zookeeper for our requirement. 
Is it possible? If yes, how? (I am expecting the docker-compose file configurations)
Any assistance in this regard is appreciated.

Thanks and Regards
Dusman

**Comment by muchemiphilip** [comment]
@dayawansha I think this Blog from Robin Moffat will be of help : https://rmoff.net/2021/03/26/loading-csv-data-into-confluent-cloud-using-the-filepulse-connector/

**Comment by dayawansha** [comment]
> @dayawansha I think this Blog from Robin Moffat will be of help : https://rmoff.net/2021/03/26/loading-csv-data-into-confluent-cloud-using-the-filepulse-connector/

Thanks for the suggestion, But I was expecting it with documentation.

**Comment by dayawansha** [comment]
> Hi Guys,
> 
> I need to run Kafka-connect-file-pulse without schema registry and Zookeeper for our requirement. Is it possible? If yes, how? (I am expecting the docker-compose file configurations) Any assistance in this regard is appreciated.
> 
> Thanks and Regards Dusman

**Comment by dayawansha** [comment]
I was able to fix this without using the "Kafka-connect-file-pulse" configuration. 

[KIP-500](https://cwiki.apache.org/confluence/display/KAFKA/KIP-500%3A+Replace+ZooKeeper+with+a+Self-Managed+Metadata+Quorum)

[Docker-compose file for KIP-500](https://github.com/confluentinc/cp-all-in-one/blob/6.2.0-post/cp-all-in-one-kraft/docker-compose.yml)
