### ISSUE TITLE
Timeout Exception

### ISSUE THREAD

**Issue by muchemiphilip** [streamthoughts/kafka-connect-file-pulse#199]
I am trying to run a self managed Filepulse connector..but once i give filepulse the json configuration i get this warning :
2021-11-25 07:57:48,109 WARN [connector-thread-t24-connect-mt103-01] Failed to create topic '(name=connect-file-pulse-status, numPartitions=default, replicationFactor=default, replicasAssignments=null, configs={cleanup.policy=compact})' (io.streamthoughts.kafka.connect.filepulse.state.KafkaFileObjectStateBackingStore)

Then i get this Timeout Exception : 
 java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Call(callName=createTopics, deadlineMs=1637827068107, tries=1, nextAllowedTryMs=1637827068208) timed out at 1637827068108 after 1 attempt(s)

t24-kafka-connect | 2021-11-25 08:01:27,879 INFO [connector-thread-t24-connect-mt103-01] Closed KafkaStateBackingStore (io.streamthoughts.kafka.connect.filepulse.storage.KafkaStateBackingStore)
t24-kafka-connect | 2021-11-25 08:01:27,879 INFO [connector-thread-t24-connect-mt103-01] Closed resources for FilePulse source connector (io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector)
t24-kafka-connect | 2021-11-25 08:01:27,879 ERROR [connector-thread-t24-connect-mt103-01] WorkerConnector{id=t24-connect-mt103-01} Error while starting connector (org.apache.kafka.connect.runtime.WorkerConnector)
t24-kafka-connect | org.apache.kafka.common.errors.TimeoutException: Timeout expired while fetching topic metadata

What could be wrong with this configuration : 

curl -i -X PUT -H "Accept:application/json" \
    -H  "Content-Type:application/json" http://localhost:8083/connectors/t24-connect-mt103-01/config \
    -d '{
        "connector.class"  :  "io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector",
        "task.reader.class"  :  "io.streamthoughts.kafka.connect.filepulse.fs.reader.LocalRowFileInputReader",
        "fs.scan.directory.path"  :  "/home/shemuchemi/t24.KE.SWIFT.MT103/Dample_103",
        "fs.scan.interval.ms"  :  "10000",
        "fs.cleanup.policy.class"  :  "io.streamthoughts.kafka.connect.filepulse.fs.clean.DeleteCleanupPolicy",
        "fs.listing.directory.path"  :  "/home/shemuchemi/t24.KE.SWIFT.MT103/Dample_103",
        "fs.listing.class"  :  "io.streamthoughts.kafka.connect.filepulse.fs.LocalFSDirectoryListing",
        "file.filter.regex.pattern"  :  ".*\\.swf$",
        "offset.strategy"  :  "name",
        "topic"  :  "t24_mt103",
        "value.converter"  :  "org.apache.kafka.connect.json.JsonConverter",
        "value.converter.schemas.enable"  :  "false",
        "key.converter"  :  "org.apache.kafka.connect.storage.StringConverter",
        "key.converter.schemas.enable"  :  "false",
        "tasks.max"  :  "1",
        "tasks.reader.class"  :  "io.streamthoughts.kafka.connect.filepulse.fs.reader.LocalRowFileInputReader",
        "tasks.file.status.storage.class"  :  "io.streamthoughts.kafka.connect.filepulse.state.KafkaFileObjectStateBackingStore",
        "tasks.file.status.storage.bootstrap.servers"  :  $BOOTSTRAP_SERVERS,
        "tasks.file.status.storage.topic"  :  "connect-file-pulse-status",
        "topic.creation.default.replication.factor"  :  "3",
        "topic.creation.default.partitions"  :  "5",
        "internal.kafka.reporter.bootstrap.servers"  :  $BOOTSTRAP_SERVERS,
        "internal.kafka.reporter.topic"  :  "t24-file-pulse-status",
        "internal.kafka.reporter.producer.security.protocol"  :  "SASL_SSL",
        "internal.kafka.reporter.producer.ssl.endpoint.identification.algorithm"  :  "https",
        "internal.kafka.reporter.producer.sasl.mechanism"  :  "PLAIN",
        "internal.kafka.reporter.producer.sasl.jaas.config"  :  $SASL_JAAS_CONFIG,
        "internal.kafka.reporter.consumer.security.protocol"  :  "SASL_SSL",
        "internal.kafka.reporter.consumer.ssl.endpoint.identification.algorithm"  :  "https",
        "internal.kafka.reporter.consumer.sasl.mechanism"  :  "PLAIN",
        "internal.kafka.reporter.consumer.sasl.jaas.config"  :  $SASL_JAAS_CONFIG,
        "internal.kafka.reporter.consumer.request.timeout.ms"  :  "20000",
        "internal.kafka.reporter.consumer.retry.backoff.ms"  :  "500"
    }'

**Comment by fhussonnois** [comment]
Hi @muchemiphilip, it seems the connector failed to create the internal topic `connect-file-pulse-status` for an unknown reason. Could you try to create this topic manually ?

**Comment by muchemiphilip** [comment]
@fhussonnois Thank you for reaching out but I tried to ingest the files in a local Confluent Platform instead of Confluent cloud .The connector is able  to list object files using: LocalFSDirectoryListing and it manages to get the 4 files in my directory but its not writing them to the topic i.e reading each row in a file. The topic is empty.
 Below is my Configurations :
name = source-filepulse-xml-01
connector.class = io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector
tasks.max = 1
key.converter = org.apache.kafka.connect.storage.StringConverter
value.converter = org.apache.kafka.connect.json.JsonConverter
errors.log.enable = true
errors.log.include.messages = true
fs.listing.class = io.streamthoughts.kafka.connect.filepulse.fs.LocalFSDirectoryListing
tasks.reader.class = io.streamthoughts.kafka.connect.filepulse.fs.reader.LocalRowFileInputReader
topic = t24_mt103
tasks.file.status.storage.class = io.streamthoughts.kafka.connect.filepulse.state.KafkaFileObjectStateBackingStore
fs.cleanup.policy.class = io.streamthoughts.kafka.connect.filepulse.fs.clean.DeleteCleanupPolicy
topic.creation.default.partitions = 6
tasks.file.status.storage.topic = connect-file-pulse-status
fs.scan.directory.path = /home/shemuchemi/t24.KE.SWIFT.MT103/Dample_103
fs.scan.interval.ms = 10000
offset.strategy = name
internal.kafka.reporter.topic = t24-file-pulse-status
topic.creation.default.replication.factor = 3
task.reader.class = io.streamthoughts.kafka.connect.filepulse.fs.reader.LocalRowFileInputReader
fs.listing.directory.path = /home/shemuchemi/t24.KE.SWIFT.MT103/Dample_103
tasks.file.status.storage.bootstrap.servers = localhost:9092
key.converter.schemas.enable = false
value.converter.schemas.enable = false
file.filter.regex.pattern = $1SWF

When i read the connect logs using  " confluent local services connect log" This is the information i get:
[2021-12-06 05:36:41,750] INFO [source-filepulse-xml-01|worker] Starting to list object files using: LocalFSDirectoryListing (io.streamthoughts.kafka.connect.filepulse.fs.DefaultFileSystemMonitor:281)
[2021-12-06 05:36:41,752] INFO [source-filepulse-xml-01|worker] Completed object files listing. '4' object files found in 1ms (io.streamthoughts.kafka.connect.filepulse.fs.DefaultFileSystemMonitor:285)
[2021-12-06 05:36:41,752] INFO [source-filepulse-xml-01|worker] Finished lookup for new object files: '0' files can be scheduled for processing (io.streamthoughts.kafka.connect.filepulse.fs.DefaultFileSystemMonitor:330)
[2021-12-06 05:36:41,752] INFO [source-filepulse-xml-01|worker] Completed filesystem monitoring iteration in 323 ms (io.streamthoughts.kafka.connect.filepulse.source.FileSystemMonitorThread:78)

The flat files i am trying to read have an extention of .SWF and look like this:

{1:F01SBICKENXBXXX0615413452}{2:O1031009191204BOTKJPJTAXXX22507796341912040409N}{3:{111:001}{121:9c29e74c-e6cf-4f4a-9dbe-9d832860c193}}{4:
:20:469-3664517
:23B:CRED
:32A:191204USD748858,45
:50K:/469-0033014 (469-0019461)
JAPAN INTERNATIONAL COOPERATION
AGENCY.
NIBANCHO CENTER BLDG.,5-25
NIBANCHO,CHIYODA-KU,TOKYO,JAPAN
:53A:BOTKUS33XXX
:54A:BKTRUS33XXX
:57D:CFC NCBA BANK
WEST YAT BRANCH
NAIROBI, KENYA
:59:/0200000114986
JICA SOUTH SUDAN
PLOT NO. 790, BLOCK 3-K SOUTH, FIRS
T CLASS, HAI THONGPINY, NAIROBI, KE
:70:JICA INTERNAL BUDGET USE ONLY.
:71A:OUR
-}{5:{CHK:2893028D2940}}

**Comment by fhussonnois** [comment]
Hi @muchemiphilip, do you have any exception ? Could you check the content of the `connect-file-pulse-status` topic ?
