### ISSUE TITLE
Disable recursive scan of folders

### ISSUE THREAD

**Issue by SteveGit007** [streamthoughts/kafka-connect-file-pulse#20]
Have a possibility to disable recursvice scan of folders via a config parameter

**Comment by fhussonnois** [comment]
Hi @SteveGit007, sorry for the late reply. 

Currenlty, this is not possible to disable recursive scan but we can work on it. 

Depending on your need, you can implement the interface [`FSDirectoryWalker`](https://github.com/streamthoughts/kafka-connect-file-pulse/blob/master/connect-file-pulse-plugin/src/main/java/io/streamthoughts/kafka/connect/filepulse/scanner/local/FSDirectoryWalker.java) and configure it using the property `fs.scanner.class`

**Comment by SteveGit007** [comment]
Thank you Florian for the fix!
Regards
