### ISSUE TITLE
Bug: Azure SDK adds a redundant slash in URL

### ISSUE THREAD

**Issue by alankan-finocomp** [streamthoughts/kafka-connect-file-pulse#200]
Hi! Just spotted a bug from Azure SDK and I got this simple unit test to reproduce the issue:
```java
public class AzureBlobStorageTest {
    @Test
    public void test_request_with_redundant_slash() {
        // mock by azurite: https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azurite?tabs=docker-hub
        // docker run -e AZURITE_ACCOUNTS=azure:password -p 10000:10000 mcr.microsoft.com/azure-storage/azurite azurite-blob --blobHost 0.0.0.0 --blobPort 10000
        AzureBlobStorageConfig config = new AzureBlobStorageConfig(Map.of(
                AZURE_BLOB_STORAGE_CONNECTION_STRING_CONFIG, "DefaultEndpointsProtocol=http;AccountName=azure;AccountKey=password;BlobEndpoint=http://localhost:10000/azure;",
                AZURE_BLOB_STORAGE_CONTAINER_NAME_CONFIG, "foo"
        ));
        BlobContainerClient client = AzureBlobStorageClientUtils.createBlobContainerClient(config);
        client.createWithResponse(null, null, null, Context.NONE);

        /* Azurite's logs would be:
        10.20.0.1 - - [29/Nov/2021:11:29:55 +0000] "PUT /azure//foo?restype=container HTTP/1.1" 400 -
        Redundant `/`------------------------------------------^
         */
    }
}
```
I have also tested v12.14.2  can fix that issue:
```xml
<azure.storage.blob.version>12.14.2</azure.storage.blob.version>
```

If it makes sense to you about this upgrade also, I hope that's not rude, any plan to release a new version soon?

**Comment by fhussonnois** [comment]
Hi @alankan-finocomp, thank you for opening this issue. Could you please provide a Pull Request (PR) with the version updated ?

I think, it should be possible de release a new version this week.

Thank you very much.

**Comment by alankan-finocomp** [comment]
Thanks @fhussonnois . I cannot assign reviewer there :man_shrugging: . Please have a look when you have time :arrow_up: Thanks again :bow:

**Comment by alankan-finocomp** [comment]
@fhussonnois Thank you for reviewing and merging the PR. Will it be released this week by any chance? Thanks again for everything including building this useful connector  :+1:

**Comment by fhussonnois** [comment]
Hi @alankan-finocomp, Connect FilePulse 2.4.1 is released. The connector should be available to confluent-hub in a couple of days.

**Comment by alankan-finocomp** [comment]
Awesome @fhussonnois . It works with the mock -  Azurite finally! Great work and thanks again!! :bow:
Closing this issue as well~
