### ISSUE TITLE
Parquet FileInputReader

### ISSUE THREAD

**Issue by sponge-b0b** [streamthoughts/kafka-connect-file-pulse#215]
Team,

Is there a roadmap for additional file readers like a Parquet file reader?

Thanks.

**Comment by fhussonnois** [comment]
Hi @sponge-b0b, currently there is no roadmap for adding a Parquet file reader. I would like to invite you to contribute to the project if you are interested.

Thanks

**Comment by dshma** [comment]
Hi there,

We've had a similar requirement some time ago and added support for reading Parquet files. It seems like this request might still be relevant, hence we'd like to contribute and pass it on for further community support.

I see the contributing file which basically suggests creating a new ticket and following the commit message guidelines. @fhussonnois, anything else? Do you see this as relevant? Are you ok with us creating a separate ticket and proposing a PR? Checking before going ahead to avoid procreating "about-the-same" tickets if not needed.

Thanks!

**Comment by fhussonnois** [comment]
Hi @dshma, it would be great if you could contribute to this connector by adding support for Parquet. I can confirm that there are no special requirements. You can open a PR and if everything is OK, I will merge it.

Thank you very much.
