### ISSUE TITLE
File Cleanup Policies

### ISSUE THREAD

**Issue by michaelbacci** [streamthoughts/kafka-connect-file-pulse#218]
In the [doc](https://streamthoughts.github.io/kafka-connect-file-pulse/docs/developer-guide/cleaning-completed-files/) rename `io.streamthoughts.kafka.connect.filepulse.fs.clean.LocalMoveCleanPolicy` to `io.streamthoughts.kafka.connect.filepulse.fs.clean.LocalMoveCleanupPolicy`.  

Using `streamthoughts/kafka-connect-file-pulse:latest` and run:  
```
[root@e39785377436 lib]# jar tf kafka-connect-filepulse-local-fs-2.4.2.jar | grep "clean"
io/streamthoughts/kafka/connect/filepulse/fs/clean/
io/streamthoughts/kafka/connect/filepulse/fs/clean/LocalMoveCleanupPolicy.class
io/streamthoughts/kafka/connect/filepulse/fs/clean/LocalMoveCleanupPolicy$MoveFileCleanerConfig.class
```

**Comment by fhussonnois** [comment]
Thanks for reporting this issue, documantion has been fixed.
