### ISSUE TITLE
internal.kafka.reporter.cluster.bootstrap.servers cannot connect to Confluent Cloud

### ISSUE THREAD

**Issue by LeonardoBonacci** [streamthoughts/kafka-connect-file-pulse#22]
We use a quite common infrastructure for our Kafka ecosystem: the Kafka brokers + schema registry are hosted in/by Confluent Cloud, and we host the Kafka Connect cluster ourselves. All this works well when the Kafka Connect cluster is configured properly: ssl, api-keys, etc. 

We are investigating whether to use kafka-connect-file-pulse connector for file reading. It seems to work well on a local Kafka environment. However, the connector tracks file status on a designated Kafka topic. In order to do so it requires the following settings "internal.kafka.reporter.bootstrap.servers". 

The file pulse connector uses this property to create an extra/internal connection to our Kafka broker. Most probably because doing so requires more than just the bootstrap.server, it fails with this message:
 _[Producer clientId=producer-5] Connection to node -1 (aws.confluent.cloud.hostname:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient:748)_

Is this a common or known issue? Is there a work-around, perhaps another way of status tracking that does not require this property be set?

**Comment by fhussonnois** [comment]
Hi @LeonardoBonacci , maybe this issue can help you #19 . 

The ConnectFilePulse uses an internal topic to synchronize the tasks and the connector instance. For doing this, it creates a dedicated producer/consumer instance. 

Unfortunately (but for security purpose) a connector cannot get access to the worker config. So you also have to configure the internal producer/consumer for the connector.

**Comment by fhussonnois** [comment]
Hi @LeonardoBonacci did you solve your problem? If so, can you close the issue? If not, how can I help you?

**Comment by LeonardoBonacci** [comment]
Hi there! Thanks for you inquiry. We've ended up using the spooldir connector. It covered the functionality required for our simple use case. 
I hereby close the ticket.
