### ISSUE TITLE
Connector will stop parsing files at 20mo

### ISSUE THREAD

**Issue by lucas-dclrcq** [streamthoughts/kafka-connect-file-pulse#222]
I've been using file pulse for a while now and it was working really well for our usecases (many thanks !)

I'm currently encountering an issue with a csv file where it stops sending record at ling 86850 (at about 20 mo)

I have checked the line where it stopped and it is not malformed in any way.

There's no stacktrace in the logs (in fact in goes on about no records being produced).

Just before stopping producing records I have :

A message produced in the connect status topic :

```
{"position":19116435,"rows":86851,"timestamp":1644512304203}
```

And an other in the file pulse status topic :

```json
{
  metadata: {
    uri: "gcs://some_folder/file.csv",
    name: file.csv",
    contentLength: 38342440,
    lastModified: 1644448848831,
    contentDigest: {
      digest: "M47ZqA==",
      algorithm: "CRC32"
    },
    userDefinedMetadata: {
      gcs.blob.bucket: "some_bucket",
      gcs.blob.storageClass: "STANDARD",
      gcs.blob.name: "some_file.csv",
      gcs.blob.createTime: 1644448848831,
      gcs.blob.contentType: "text/csv",
      gcs.blob.etag: "COCm8avh8/UCEAE="
    }
  },
  offset: {
    position: 19115848,
    rows: 86848,
    timestamp: 1644512304200
  },
  status: "READING"
}
```

Any idea about what could be the issue ?

Does filepulse have a limit on the size of the file its parsing ?

Thanks !

**Comment by fhussonnois** [comment]
Hi @lucas-dclrcq, FilePulse does not have a limit on the file size. This problem may be coming from the GCP connection, if you manage to reproduce this problem, it would be interesting to enable the log DEBUG level to see if there is a network problem.
