### ISSUE TITLE
Graceful stop of task error, tasks changes from running to unassigned state and scheduled files are not processed

### ISSUE THREAD

**Issue by vltgft** [streamthoughts/kafka-connect-file-pulse#223]
Hi, 

We have built and installed this connect plugin via confluent-hub install for reading xml files from Azure Blob Storage. The version we used for the plugin is 2.4.1 and 2.4.2.

Our config is this:

{
    "connector.class": "io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector",
    "tasks.reader.class": "io.streamthoughts.kafka.connect.filepulse.fs.reader.AzureBlobStorageXMLFileInputReader",
    "azure.storage.connection.string": "DefaultEndpointsProtocol=xxxxxx",
    "azure.storage.account.name": "<storage_acc_name>",
    "azure.storage.account.key": "<key>",
    "azure.storage.container.name": ">container_name>",
    "azure.storage.blob.prefix": "Gestiones",
    "fs.listing.class": "io.streamthoughts.kafka.connect.filepulse.fs.AzureBlobStorageFileSystemListing",
    "reader.xpath.expression":"/gestiones/gestion",
    "file.filter.regex.pattern": ".*xml$",
    "topic": "sgc.operations.load",
    "fs.cleanup.policy.class": "io.streamthoughts.kafka.connect.filepulse.fs.clean.LogCleanupPolicy",
    "tasks.file.status.storage.bootstrap.servers": "confluent.cloud:9092",
    "tasks.file.status.storage.topic": "connect-filepulse-status",
    "tasks.file.status.storage.producer.security.protocol": "SASL_SSL",
    "tasks.file.status.storage.producer.sasl.jaas.config": "<secret>",
    "tasks.file.status.storage.producer.ssl.endpoint.identification.algorithm": "https",
    "tasks.file.status.storage.producer.sasl.mechanism": "PLAIN",
    "tasks.file.status.storage.producer.request.timeout.ms": "20000",
    "tasks.file.status.storage.consumer.security.protocol": "SASL_SSL",
    "tasks.file.status.storage.consumer.sasl.jaas.config": "<secret>",
    "tasks.file.status.storage.consumer.ssl.endpoint.identification.algorithm": "https",
    "tasks.file.status.storage.consumer.sasl.mechanism": "PLAIN",
    "tasks.file.status.storage.consumer.request.timeout.ms": "20000",
    "tasks.max": 4,
    "errors.log.enable": true,
    "filters":"setKey",
    "filters.setKey.type": "io.streamthoughts.kafka.connect.filepulse.filter.AppendFilter",
    "filters.setKey.field": "$key",
    "filters.setKey.value": "{{ uuid() }}",
    "value.converter.schemas.enable":false
}

Our kakfa cluster is on Confluent Cloud.

However, it stops working an it fails to be restarted/stopped gracefully with logs as below.

[INFO] 2022-02-07 14:24:49,011 [DistributedHerder-connect-1-1] io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector taskConfigs - Creating new tasks configurations (maxTasks=4)
[INFO] 2022-02-07 14:24:49,011 [DistributedHerder-connect-1-1] io.streamthoughts.kafka.connect.filepulse.fs.DefaultFileSystemMonitor listFilesToSchedule - Preparing next scheduling using the object files found during last iteration (attempt=1/3).
[INFO] 2022-02-07 14:24:49,011 [DistributedHerder-connect-1-1] io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector lambda$taskConfigs$4 - Created config for task_id=0 with '5' object files (task_config_gen=1).
[INFO] 2022-02-07 14:24:49,011 [DistributedHerder-connect-1-1] io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector lambda$taskConfigs$4 - Created config for task_id=1 with '5' object files (task_config_gen=1).
[INFO] 2022-02-07 14:24:49,012 [DistributedHerder-connect-1-1] io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector lambda$taskConfigs$4 - Created config for task_id=2 with '5' object files (task_config_gen=1).
[INFO] 2022-02-07 14:24:49,012 [DistributedHerder-connect-1-1] io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector lambda$taskConfigs$4 - Created config for task_id=3 with '5' object files (task_config_gen=1).
[INFO] 2022-02-07 14:24:49,095 [KafkaBasedLog Work Thread - confluent.connect-filepulse-blob-storage-configs] org.apache.kafka.connect.runtime.distributed.DistributedHerder onTaskConfigUpdate - [Worker clientId=connect-1, groupId=confluent.connect-filepulse-blob-storage] Tasks [filepulse-source-blob-storage-1, filepulse-source-blob-storage-2, filepulse-source-blob-storage-3, filepulse-source-blob-storage-0] configs updated
[INFO] 2022-02-07 14:24:49,099 [DistributedHerder-connect-1-1] org.apache.kafka.connect.runtime.distributed.DistributedHerder processTaskConfigUpdatesWithIncrementalCooperative - [Worker clientId=connect-1, groupId=confluent.connect-filepulse-blob-storage] Handling task config update by restarting tasks [filepulse-source-blob-storage-1, filepulse-source-blob-storage-2, filepulse-source-blob-storage-3, filepulse-source-blob-storage-0]
[INFO] 2022-02-07 14:24:49,100 [DistributedHerder-connect-1-1] org.apache.kafka.connect.runtime.Worker stopTask - Stopping task filepulse-source-blob-storage-1
[INFO] 2022-02-07 14:24:49,100 [DistributedHerder-connect-1-1] org.apache.kafka.connect.runtime.Worker stopTask - Stopping task filepulse-source-blob-storage-2
[INFO] 2022-02-07 14:24:49,100 [DistributedHerder-connect-1-1] org.apache.kafka.connect.runtime.Worker stopTask - Stopping task filepulse-source-blob-storage-3
[INFO] 2022-02-07 14:24:49,100 [DistributedHerder-connect-1-1] org.apache.kafka.connect.runtime.Worker stopTask - Stopping task filepulse-source-blob-storage-0
[ERROR] 2022-02-07 14:24:54,100 [DistributedHerder-connect-1-1] org.apache.kafka.connect.runtime.Worker awaitStopTask - Graceful stop of task filepulse-source-blob-storage-1 failed.
[INFO] 2022-02-07 14:24:54,101 [pool-3-thread-31] org.apache.kafka.clients.producer.KafkaProducer close - [Producer clientId=connector-producer-filepulse-source-blob-storage-1] Closing the Kafka producer with timeoutMillis = 0 ms.
[INFO] 2022-02-07 14:24:54,101 [pool-3-thread-31] org.apache.kafka.clients.producer.KafkaProducer close - [Producer clientId=connector-producer-filepulse-source-blob-storage-1] Proceeding to force close the producer since pending requests could not be completed within timeout 0 ms.[ERROR] 2022-02-07 14:24:54,101 [DistributedHerder-connect-1-1] org.apache.kafka.connect.runtime.Worker awaitStopTask - Graceful stop of task filepulse-source-blob-storage-2 failed.
[INFO] 2022-02-07 14:24:54,102 [pool-3-thread-32] org.apache.kafka.clients.producer.KafkaProducer close - [Producer clientId=connector-producer-filepulse-source-blob-storage-2] Closing the Kafka producer with timeoutMillis = 0 ms.
[INFO] 2022-02-07 14:24:54,102 [pool-3-thread-32] org.apache.kafka.clients.producer.KafkaProducer close - [Producer clientId=connector-producer-filepulse-source-blob-storage-2] Proceeding to force close the producer since pending requests could not be completed within timeout 0 ms.[ERROR] 2022-02-07 14:24:54,104 [DistributedHerder-connect-1-1] org.apache.kafka.connect.runtime.Worker awaitStopTask - Graceful stop of task filepulse-source-blob-storage-3 failed.

We also see in logs errors of heartbeat timeout and a rediscovery is launched and a successfully join. However after this the tasks are not running (unassigned state) and rest of batch files are not processed:

[INFO] 2022-02-07 14:25:26,194 [kafka-coordinator-heartbeat-thread | confluent.connect-filepulse-blob-storage] org.apache.kafka.connect.runtime.distributed.WorkerCoordinator markCoordinatorUnknown - [Worker clientId=connect-1, groupId=confluent.connect-filepulse-blob-storage] Group coordinator confluent.cloud:9092 (id: 2147483643 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response.isDisconnected: false. Rediscovery will be attempted.
[INFO] 2022-02-07 14:25:44,978 [DistributedHerder-connect-1-1] org.apache.kafka.connect.runtime.distributed.WorkerCoordinator handle - [Worker clientId=connect-1, groupId=confluent.connect-filepulse-blob-storage] Successfully joined group with generation Generation{generationId=29, memberId='connect-1-25b24998-06be-4271-b663-6472e735fc6c', protocol='sessioned'}
[INFO] 2022-02-07 14:25:44,987 [SourceTaskOffsetCommitter-1] io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceTask commit - Committed offset for file: [uri=https://blob.core.windows.net/container/Gestiones-5k-256.xml, name='Gestiones-5k-256.xml', contentLength=13964468, lastModified=1644243884000, contentDigest=null, userDefinedMetadata={azure.blob.storage.contentType=text/xml, azure.blob.storage.creationTime=1644243884000, azure.blob.storage.blobUrl=https://blob.core.windows.net/container/Gestiones-5k-256.xml, azure.blob.storage.account=}]
[INFO] 2022-02-07 14:25:44,988 [SourceTaskOffsetCommitter-1] org.apache.kafka.connect.runtime.WorkerSourceTask commitOffsets - WorkerSourceTask{id=filepulse-source-blob-storage-2} Either no records were produced by the task since the last offset commit, or every record has been filtered out by a transformation or dropped due to transformation or conversion errors.
[INFO] 2022-02-07 14:25:44,988 [DistributedHerder-connect-1-1] org.apache.kafka.connect.runtime.distributed.WorkerCoordinator handle - [Worker clientId=connect-1, groupId=confluent.connect-filepulse-blob-storage] Successfully synced group in generation Generation{generationId=29, memberId='connect-1-25b24998-06be-4271-b663-6472e735fc6c', protocol='sessioned'}
[INFO] 2022-02-07 14:25:44,989 [DistributedHerder-connect-1-1] org.apache.kafka.connect.runtime.distributed.DistributedHerder onAssigned - [Worker clientId=connect-1, groupId=confluent.connect-filepulse-blob-storage] Joined group at generation 29 with protocol version 2 and got assignment: Assignment{error=0, leader='connect-1-25b24998-06be-4271-b663-6472e735fc6c', leaderUrl='http://connect-filepulse-blob-storage-0.connect-filepulse-blob-storage.confluent.svc.cluster.local:8083/', offset=1200, connectorIds=[filepulse-source-blob-storage], taskIds=[filepulse-source-blob-storage-1, filepulse-source-blob-storage-2, filepulse-source-blob-storage-3, filepulse-source-blob-storage-0], revokedConnectorIds=[], revokedTaskIds=[], delay=0} with rebalance delay: 0
[INFO] 2022-02-07 14:25:44,989 [DistributedHerder-connect-1-1] org.apache.kafka.connect.runtime.distributed.DistributedHerder startWork - [Worker clientId=connect-1, groupId=confluent.connect-filepulse-blob-storage] Starting connectors and tasks using config offset 1200
[INFO] 2022-02-07 14:25:44,989 [DistributedHerder-connect-1-1] org.apache.kafka.connect.runtime.distributed.DistributedHerder startWork - [Worker clientId=connect-1, groupId=confluent.connect-filepulse-blob-storage] Finished starting connectors and tasks
[INFO] 2022-02-07 14:25:44,999 [SourceTaskOffsetCommitter-1] io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceTask commit - Committed offset for file: [uri=https://blob.core.windows.net/container/Gestiones-5k-259.xml, name='Gestiones-5k-259.xml', contentLength=13968472, lastModified=1644243885000, contentDigest=null, userDefinedMetadata={azure.blob.storage.contentType=text/xml, azure.blob.storage.creationTime=1644243885000, azure.blob.storage.blobUrl=https://blob.core.windows.net/container/Gestiones-5k-259.xml, azure.blob.storage.account=}]
[INFO] 2022-02-07 14:25:45,000 [SourceTaskOffsetCommitter-1] org.apache.kafka.connect.runtime.WorkerSourceTask commitOffsets - WorkerSourceTask{id=filepulse-source-blob-storage-0} Either no records were produced by the task since the last offset commit, or every record has been filtered out by a transformation or dropped due to transformation or conversion errors.
[INFO] 2022-02-07 14:25:45,003 [SourceTaskOffsetCommitter-1] io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceTask commit - Committed offset for file: [uri=https://blob.core.windows.net/container/Gestiones-5k-243.xml, name='Gestiones-5k-243.xml', contentLength=13968472, lastModified=1644243882000, contentDigest=null, userDefinedMetadata={azure.blob.storage.contentType=text/xml, azure.blob.storage.creationTime=1644243882000, azure.blob.storage.blobUrl=https://blob.core.windows.net/container/Gestiones-5k-243.xml, azure.blob.storage.account=}]
[INFO] 2022-02-07 14:25:54,854 [FileSystemMonitorThread] io.streamthoughts.kafka.connect.filepulse.fs.DefaultFileSystemMonitor updateFiles - Scheduled files still being processed: 8. Skip filesystem listing while waiting for tasks completion
[INFO] 2022-02-07 14:25:54,855 [FileSystemMonitorThread] io.streamthoughts.kafka.connect.filepulse.source.FileSystemMonitorThread run - Completed filesystem monitoring iteration in 1 ms
[INFO] 2022-02-07 14:25:54,930 [SourceTaskOffsetCommitter-1] org.apache.kafka.connect.runtime.WorkerSourceTask commitOffsets - WorkerSourceTask{id=filepulse-source-blob-storage-3} Either no records were produced by the task since the last offset commit, or every record has been filtered out by a transformation or dropped due to transformation or conversion errors.
[INFO] 2022-02-07 14:25:55,121 [SourceTaskOffsetCommitter-1] org.apache.kafka.connect.runtime.WorkerSourceTask commitOffsets - WorkerSourceTask{id=filepulse-source-blob-storage-1} Either no records were produced by the task since the last offset commit, or every record has been filtered out by a transformation or dropped due to transformation or conversion errors.
[INFO] 2022-02-07 14:25:55,137 [SourceTaskOffsetCommitter-1] org.apache.kafka.connect.runtime.WorkerSourceTask commitOffsets - WorkerSourceTask{id=filepulse-source-blob-storage-2} Either no records were produced by the task since the last offset commit, or every record has been filtered out by a transformation or dropped due to transformation or conversion errors.
[ERROR] 2022-02-07 14:26:04,242 [SourceTaskOffsetCommitter-1] org.apache.kafka.connect.runtime.WorkerSourceTask commitOffsets - WorkerSourceTask{id=filepulse-source-blob-storage-2} Timed out waiting to flush offsets to storage; will try again on next flush interval with latest offsets
[ERROR] 2022-02-07 14:26:04,247 [SourceTaskOffsetCommitter-1] org.apache.kafka.connect.runtime.SourceTaskOffsetCommitter commit - WorkerSourceTask{id=filepulse-source-blob-storage-2} Failed to commit offsets

We have also implemented the confluent cluster in a local environment inside our AKS for discarding network problems and the result is the same.

Thank you for your help in advance.

**Comment by fhussonnois** [comment]
Hi @vltgft, I'm not sure if the issue came from FilePulse because your worker failed to commit its offsets : 

`[ERROR] 2022-02-07 14:26:04,247 [SourceTaskOffsetCommitter-1] org.apache.kafka.connect.runtime.SourceTaskOffsetCommitter commit - WorkerSourceTask{id=filepulse-source-blob-storage-2} Failed to commit offsets`

I suggest to you to double check the configuration of your connect cluster. In addition, start FilePulse with a single task to help investigating the issue.

**Comment by vltgft** [comment]
Hi @fhussonnois 

thanks for the feedback. We have checked many times the configuration of our connection with the cluster, that's why we implementing it locally in our AKS with the same result. 

Config connect:

admin.bootstrap.servers=confluent.cloud:9092
admin.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="${file:/mnt/secrets/cloud-plain/plain.txt:username}" password="${file:/mnt/secrets/cloud-plain/plain.txt:password}";
admin.sasl.mechanism=PLAIN
admin.security.protocol=SASL_SSL
bootstrap.servers=confluent.cloud:9092
config.providers=file
config.providers.file.class=org.apache.kafka.common.config.provider.FileConfigProvider
config.storage.replication.factor=3
config.storage.topic=confluent.connect-filepulse-blob-storage-configs
confluent.topic.replication.factor=3
consumer.bootstrap.servers=confluent.cloud:9092
consumer.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="${file:/mnt/secrets/cloud-plain/plain.txt:username}" password="${file:/mnt/secrets/cloud-plain/plain.txt:password}";
consumer.sasl.mechanism=PLAIN
consumer.security.protocol=SASL_SSL
group.id=confluent.connect-filepulse-blob-storage
key.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schema.registry.basic.auth.credentials.source=USER_INFO
key.converter.schema.registry.basic.auth.user.info=${file:/mnt/secrets/cloud-sr-access/basic.txt:username}:${file:/mnt/secrets/cloud-sr-access/basic.txt:password}
key.converter.schema.registry.url=https://azure.confluent.cloud
key.converter.schemas.enable=false
listeners=http://0.0.0.0:8083
offset.flush.interval.ms=10000
offset.storage.replication.factor=3
offset.storage.topic=confluent.connect-filepulse-blob-storage-offsets
plugin.path=/usr/share/java,/usr/share/confluent-hub-components,/mnt/plugins
producer.bootstrap.servers=confluent.cloud:9092
producer.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="${file:/mnt/secrets/cloud-plain/plain.txt:username}" password="${file:/mnt/secrets/cloud-plain/plain.txt:password}";
producer.sasl.mechanism=PLAIN
producer.security.protocol=SASL_SSL
request.timeout.ms=20000
rest.advertised.listener=http
retry.backoff.ms=500
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="${file:/mnt/secrets/cloud-plain/plain.txt:username}" password="${file:/mnt/secrets/cloud-plain/plain.txt:password}";
sasl.mechanism=PLAIN
security.protocol=SASL_SSL
status.storage.replication.factor=3
status.storage.topic=confluent.connect-filepulse-blob-storage-status
value.converter=org.apache.kafka.connect.json.JsonConverter
value.converter.schema.registry.basic.auth.credentials.source=USER_INFO
value.converter.schema.registry.basic.auth.user.info=${file:/mnt/secrets/cloud-sr-access/basic.txt:username}:${file:/mnt/secrets/cloud-sr-access/basic.txt:password}
value.converter.schema.registry.url=https://confluent.cloud
value.converter.schemas.enable=false

Thanks.

**Comment by fhussonnois** [comment]
Hi @vltgft, we juste find an issue due to a change is the threading-model of Kafka Connect [KAFKA-10792](https://issues.apache.org/jira/browse/KAFKA-10792). I will release a new version as soon as possible. Maybe this will fix your issue.
