### ISSUE TITLE
Compressed files repeatedly decompressed when purged

### ISSUE THREAD

**Issue by markns** [streamthoughts/kafka-connect-file-pulse#225]
Hi, firstly, thanks for the project - it should be quite useful for us. 

I'm looking into using the framework for loading encrypted and compressed files to Kafka. Decrypting the files is relatively expensive, and the decompressed files take up a decent amount of storage space. Therefore, I would like to be able to decrypt the files once, and purge the decompressed file after it has been successfully processed.

My problem is, as a test I've been playing around with the quickstart-musics-dataset.zip example, and it appears the zip file will be decompressed each time the `FileSystemListing.listEligibleFiles` method is run (if the previously decompressed file is deleted), even when the contents of the zip file have been processed.

Is there a way to control this behavious perhaps?

**Comment by fhussonnois** [comment]
Hi @markns, currently decompression is handle by this class [CodecHandlerUtils](https://github.com/streamthoughts/kafka-connect-file-pulse/blob/9194b9b67e279fbedd16e1f4c2bed67ba55f62e0/connect-file-pulse-filesystems/filepulse-local-fs/src/main/java/io/streamthoughts/kafka/connect/filepulse/fs/codec/CodecHandlerUtils.java). The connector create a container directory used for decompressing an input ZIP file. Basically, decompression will be executed if that directory is empty. The connector does not keep any state about which file have been already decompressed.
