### ISSUE TITLE
Ignore blank values during DelimitedRowFilter type conversion

### ISSUE THREAD

**Issue by markns** [streamthoughts/kafka-connect-file-pulse#228]
Hi, another day another question :)

Is it possible to tell the `DelimitedRowFilter` to ignore blank values during conversions? 

For example, with the following CSV

```
A|B|C
x|1|x
y||y
z|2|z
```

and the config 

```
filters.ParseDelimitedRow.type=io.streamthoughts.kafka.connect.filepulse.filter.DelimitedRowFilter
filters.ParseDelimitedRow.columns=A:STRING;B:INTEGER;C:STRING
filters.ParseDelimitedRow.trimColumn=true
filters.ParseDelimitedRow.separator=\\|
```

I get an exception when processing the second line. 

I know I can handle this in a `ConvertFilter` such as:

```
filters.BConverter.type=io.streamthoughts.kafka.connect.filepulse.filter.ConvertFilter
filters.BConverter.if={{ is_empty($.B) }}
filters.BConverter.invert=true
filters.BConverter.field=B
filters.BConverter.to=FLOAT
```

but that gets onerous quickly when dealing with tens/hundreds of columns.

**Comment by fhussonnois** [comment]
Hi @markns, thank you for opening this issue. We will provide a fix for that :)
