### ISSUE TITLE
[QUESTION] Is there a way to ignore unprocessed files on errors ?

### ISSUE THREAD

**Issue by igorng** [streamthoughts/kafka-connect-file-pulse#232]
I am running the connector v2.4.3 on Azure to source avro files. It may happen that loading a file throws an error (say for example one file which is not in expected Avro format), the processing then just stay blocked with the following message:

`INFO Scheduled files still being processed: 1. Skip filesystem listing while waiting for tasks completion (io.streamthoughts.kafka.connect.filepulse.fs.DefaultFileSystemMonitor:271)`

Is there a way to just ignore files loading/processing failures and continue the processing?
Thanks.

**Comment by fhussonnois** [comment]
Hi @igorng, which reader are you using? Normally, even if an exception occurs while processing a file, it should be marked as FAIL and it should not block further files.
