### ISSUE TITLE
Process files in directory in lexicographic order

### ISSUE THREAD

**Issue by markns** [streamthoughts/kafka-connect-file-pulse#233]
Hi,
Simple question - is it possible to make file-pulse process files in lexicographic ordering. 

so given the directory tree:

```
2022/01/01/file.csv
2022/01/02/file.csv
2022/02/01/file.csv
2022/02/02/file.csv
```

the data would end up in Kafka in chronological order.

Thanks

**Comment by fhussonnois** [comment]
Hi @markns, well currently this is not possible because files are ordered based on their timestamp not path. But, we could make this behaviour configurable in next release.

**Comment by markns** [comment]
Hey Florian, thanks for the reply. Tbh, I wrote this issue before realising the files are sorted by last-modified (the test data I was using had filenames with datestamps that didn't reflect when they would actually have been produced in production). Please feel free to close this issue if you prefer.

**Comment by fhussonnois** [comment]
Hi @markns, thanks for your feedback. The new FilePulse v2.5.0 release now supports a new connector's config `tasks.file.processing.order.by`  that accepts the following values : `LAST_MODIFIED`, `URI`, `CONTENT_LENGTH`, `CONTENT_LENGTH_DESC`
