### ISSUE TITLE
[Question]: Constant Binary Data from File

### ISSUE THREAD

**Issue by CorsinSauber** [streamthoughts/kafka-connect-file-pulse#237]
I am trying to read data which is constantly written to a binary file (tdms) and transfer it to kafka. But as a result I get something strange which I can't do anything with. 
Do I have an error in my configuration of the connector?

Output: (python Consumer)
b'Struct{message=TDSm\x0e\x00\x00\x00h\x12\x00\x00\xef\xbf\xbd\x00\x00\x00\x00\x00\x00\x00\xef\xbf\xbd\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x01\x00\x00\x00/\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\x02\x00\x00\x00\x05\x00\x00\x00prop1 \x00\x00\x00\x03\x00\x00\x00foo\x05\x00\x00\x00prop2\x03\x00\x00\x00\x03\x00\x00\x00}'

Source Connector Configuration:
         "connector.class":"io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector",
        "fs.listing.class":"io.streamthoughts.kafka.connect.filepulse.fs.LocalFSDirectoryListing",
        "fs.listing.directory.path":"C:/Users/test",
         "fs.scan.interval.ms":"10000",
        "topic":"testTopic",
        "internal.kafka.reporter.bootstrap.servers": "localhost:9092",
        "tasks.max": 1,
        "tasks.reader.class":"io.streamthoughts.kafka.connect.filepulse.fs.reader.LocalRowFileInputReader",
        "fs.cleanup.policy.class":"io.streamthoughts.kafka.connect.filepulse.fs.clean.LogCleanupPolicy",
        "fs.scanner.class":"io.streamthoughts.kafka.connect.filepulse.scanner.local.LocalFSDirectoryWalker",        
        "tasks.file.status.storage.bootstrap.servers": "localhost:9092",
        "key.converter":"org.apache.kafka.connect.storage.StringConverter",
        "value.converter":"org.apache.kafka.connect.storage.StringConverter",
        "read.max.wait.ms":"15000",
        "allow.tasks.reconfiguration.after.timeout.ms":"1600",
        "offset.strategy":"name"

**Comment by fhussonnois** [comment]
Hi @CorsinSauber, You are using the `LocalRowFileInputReader` so FilePulse create a Struct object with a field `message` containing the actual row. Because, you are using `value.converter":"org.apache.kafka.connect.storage.StringConverter` is not serialized correctly. 

If your need is to only get the row value as part of the message you should use Kafka Connect Transformer (SMT) : 

Example : 

```json
"transforms": "ExtractMessageToValue",
"transforms.ExtractMessageToValue.type": "org.apache.kafka.connect.transforms.ExtractField$Value",
"transforms.ExtractMessageToValue.fields": "message"

```

**Comment by CorsinSauber** [comment]
Hi @fhussonnois, Thanks for the quick reply!
Can it be that "transforms.ExtractMessageToValue.fields" has one "s" too much at the end? --> ".field"

And one more question, can i specify what kind of data to transfer? In my case binary data from a tdms file.
if i don't specify anything not all data will be transferred correctly.

i tried to specify it with the attribute "file.encoding", however this does not seem to work correctly for me. 

Output Consumer:
`TDSm   h  �       �             /����      prop1       foo   prop2      
   /'group_1'����      prop1
   ��n���?   prop2!       /'group_1'/'channel_1'   
...`

**Comment by fhussonnois** [comment]
Hi @CorsinSauber, I think ou also need to configure the encoding for those properties : 

```
"key.converter":"org.apache.kafka.connect.storage.StringConverter"
"value.converter":"org.apache.kafka.connect.storage.StringConverter"
```

Thus you need to specify the additional properties : `key.serializer.encoding` and `value.serializer.encoding`

Hope this will resolve your problem.
