### ISSUE TITLE
Support for AWS S3 Move Clean up policy For completed and failed files

### ISSUE THREAD

**Issue by niraveen** [streamthoughts/kafka-connect-file-pulse#238]
Any idea whether this clean policy can be supported in the near time?

**Comment by fhussonnois** [comment]
Hi @niraveen, thank you for your feature proposiion. The new policy should be available next week in the master branch and on docker-hub with the `master` tag so that you could try it before next release.

**Comment by niraveen** [comment]
I think it can be as simple as LocalFSDirectoryListing.
cleaner.output.failed.path
cleaner.output.succeed.path
Both paths can be defined in the same bucket with paths defined completely even though prefix is used for reading files.

**Comment by niraveen** [comment]
@fhussonnois any update on this feature? Thanks

**Comment by fhussonnois** [comment]
Hi @niraveen, this feature is still in development. This new feature is still under development. I didn't have time to work on it last week. I hope to merge on the master next week.

**Comment by niraveen** [comment]
Thank you @fhussonnois for working on this. I am sure other developers will find this feature very useful.

**Comment by fhussonnois** [comment]
Hi @niraveen, this new feature has been merged on master (not release yet), so you should be able to try it.

* Docs: `https://streamthoughts.github.io/kafka-connect-file-pulse/docs/developer-guide/cleaning-completed-files/#cleanup-policies-amazon` 
* Docker Hub : streamthoughts/kafka-connect-file-pulse:master

**Comment by niraveen** [comment]
@fhussonnois I tried and I think I found an issue. we created folders for separate failure, success and new files. when the first file is tried and Kafka connect file pulse gets an error due to some serialization issue (when the schema is used either be JSON or Avro). the feature doesn't move the file to the failure folder.

Can you tell us, what kind of failures are captured, that a file will be moved to failure folder?
