### ISSUE TITLE
error when trying to connect to s3 on aws msk

### ISSUE THREAD

**Issue by cvk8789** [streamthoughts/kafka-connect-file-pulse#242]
we are currently trying to use FilePulse Source Connector to read s3 bucket but keep getting these errors

    org.apache.kafka.common.errors.TimeoutException: Call(callName=fetchMetadata,.... 
    Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting to send the call. Call: fetchMetadata

any pointers will be great

here is our config

```
connector.class=io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector
fs.cleanup.policy.class=io.streamthoughts.kafka.connect.filepulse.fs.clean.DeleteCleanupPolicy
fs.listing.class=io.streamthoughts.kafka.connect.filepulse.fs.AmazonS3FileSystemListing
aws.s3.region=eu-central-1
aws.s3.bucket.name=<<s3 bucket name>>
aws.access.key.id=<<aws key id>>
aws.secret.access.key=<<aws key>>
fs.listing.filters=io.streamthoughts.kafka.connect.filepulse.fs.filter.RegexFileListFilter
fs.listing.interval.ms=1000
file.filter.regex.pattern=.*\\.json$
topic=prove_material_flow
tasks.reader.class=io.streamthoughts.kafka.connect.filepulse.fs.reader.AmazonS3RowFileInputReader
tasks.file.status.storage.class=io.streamthoughts.kafka.connect.filepulse.state.KafkaFileObjectStateBackingStore
tasks.file.status.storage.bootstrap.servers=<<broker 1>>:9094,<<broker 2>>:9094
tasks.file.status.storage.security.protocol=ssl
tasks.file.status.storage.topic=connect-file-pulse-status
tasks.file.status.storage.topic.partitions=10
tasks.file.status.storage.topic.replication.factor=1
tasks.max=4
```

**Comment by niraveen** [comment]
hmm working for me.. did you check whether Kafka is running or not? try to give one Kafka broker in the bootstrap server?

**Comment by cvk8789** [comment]
@niraveen yes did try and finished with same error, it appears the connector is trying to connect as plaintext but we only have ssl enabled for the brokers

**Comment by cvk8789** [comment]
@niraveen is your broker enabled for PLAINTEXT protocol? and if you don't mind what does your config look like please?

**Comment by fhussonnois** [comment]
Hi @cvk8789, how did you configure your Kafka Connect worker ?

**Comment by langan** [comment]
Getting the same error @fhussonnois 

`Invalid S3 bucket name. Bucket does not exist, or an error happens while connecting to Amazon service`

Works locally but not on MSK 🤔

**Comment by tooptoop4** [comment]
@cvk8789 did u solve?

**Comment by cvk8789** [comment]
> @cvk8789 did u solve?

no

**Comment by humam-nameer-10p** [comment]
works on unauthorized msk but not SASL (Scram/IAM)
