### ISSUE TITLE
RegexFileFilter FileSystem Listing in AzureBlobStorage

### ISSUE THREAD

**Issue by bsvicente** [streamthoughts/kafka-connect-file-pulse#244]
does RegexFileFilter work with azure blob storage?
It looks like the package has been moved class.

**Comment by fhussonnois** [comment]
Hi @bsvicente, you should be able to use the ` io.streamthoughts.kafka.connect.filepulse.fs.filter.RegexFileListFilter` with any FileSystemListening.
