### ISSUE TITLE
Provide CSV processing filter

### ISSUE THREAD

**Issue by bradydean** [streamthoughts/kafka-connect-file-pulse#249]
**Is your feature request related to a problem? Please describe.**

`DelimitedRowFilter` uses a regex to find delimiters in each line, but it is difficult to parse lines which contain string-enclosed values.

See: https://github.com/streamthoughts/kafka-connect-file-pulse/issues/96

**Describe the solution you'd like**

A CSV processing filter which takes into account different separators, and handles either `"` or `'` enclosed values. These quotes should not be included in the output values. It should also support the same config options as `DelimitedRowFilter` (with the exception that `separator` could just be a single character instead of a regex).

**Describe alternatives you've considered**

I've tried different regexes, including the ones mentioned in the above issue, but none are satisfactory. The ones that "work" tend to leave the enclosing quotes in the value instead of being striped out, eg `",(?=([^\"]*\"[^\"]*\")*[^\"]*$)"`

**Comment by jesperbagge** [comment]
Hi @fhussonnois ! When will this be available on confluent hub?
