### ISSUE TITLE
KafkaException: Could not instantiate class

### ISSUE THREAD

**Issue by dmarupov** [streamthoughts/kafka-connect-file-pulse#25]
Hello, 
I am trying to setup File Pulse for the first time. I have a distributed Kafka with three workers running and I was successful at using the default Java FileStreamSourceConnector. But when I try to start the File Pulse connector I keep getting the following error: 
{
    "name": "file-pulse-connector",
    "connector": {
        "state": "FAILED",
        "worker_id": "my.ip.address:8085",
        "trace": "org.apache.kafka.common.KafkaException: Could not instantiate class io.streamthoughts.kafka.connect.filepulse.scanner.local.LocalFSDirectoryWalker\n\tat org.apache.kafka.common.utils.Utils.newInstance(Utils.java:325)\n\tat org.apache.kafka.common.config.AbstractConfig.getConfiguredInstance(AbstractConfig.java:370)\n\tat io.streamthoughts.kafka.connect.filepulse.config.ConnectorConfig.directoryScanner(ConnectorConfig.java:81)\n\tat io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector.start(FilePulseSourceConnector.java:100)\n\tat org.apache.kafka.connect.runtime.WorkerConnector.doStart(WorkerConnector.java:111)\n\tat org.apache.kafka.connect.runtime.WorkerConnector.start(WorkerConnector.java:136)\n\tat org.apache.kafka.connect.runtime.WorkerConnector.transitionTo(WorkerConnector.java:196)\n\tat org.apache.kafka.connect.runtime.Worker.startConnector(Worker.java:252)\n\tat org.apache.kafka.connect.runtime.distributed.DistributedHerder.startConnector(DistributedHerder.java:1079)\n\tat org.apache.kafka.connect.runtime.distributed.DistributedHerder.access$1300(DistributedHerder.java:117)\n\tat org.apache.kafka.connect.runtime.distributed.DistributedHerder$11.call(DistributedHerder.java:797)\n\tat org.apache.kafka.connect.runtime.distributed.DistributedHerder$11.call(DistributedHerder.java:783)\n\tat org.apache.kafka.connect.runtime.distributed.DistributedHerder.tick(DistributedHerder.java:296)\n\tat org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:245)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\nCaused by: java.lang.reflect.InvocationTargetException\n\tat sun.reflect.GeneratedConstructorAccessor19.newInstance(Unknown Source)\n\tat sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)\n\tat java.lang.reflect.Constructor.newInstance(Constructor.java:423)\n\tat org.apache.kafka.common.utils.Utils.newInstance(Utils.java:321)\n\t... 18 more\nCaused by: java.lang.NoClassDefFoundError: org/apache/commons/compress/archivers/tar/TarArchiveInputStream\n\tat io.streamthoughts.kafka.connect.filepulse.scanner.local.codec.CodecManager.<init>(CodecManager.java:44)\n\tat io.streamthoughts.kafka.connect.filepulse.scanner.local.LocalFSDirectoryWalker.<init>(LocalFSDirectoryWalker.java:67)\n\tat io.streamthoughts.kafka.connect.filepulse.scanner.local.LocalFSDirectoryWalker.<init>(LocalFSDirectoryWalker.java:56)\n\t... 22 more\nCaused by: java.lang.ClassNotFoundException: org.apache.commons.compress.archivers.tar.TarArchiveInputStream\n\tat java.net.URLClassLoader.findClass(URLClassLoader.java:382)\n\tat java.lang.ClassLoader.loadClass(ClassLoader.java:418)\n\tat org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:104)\n\tat java.lang.ClassLoader.loadClass(ClassLoader.java:351)\n\t... 25 more\n"
    },
    "tasks": [],
    "type": "source"
}

Please help, I am not sure if this is because of the source code or because of the configuration. I would really appreciate any help.

Thank you.

**Comment by fhussonnois** [comment]
Hi @dmarupov , could you tell me how did you install connect-file-pulse ? 

It seems that the `LocalFSDirectoryWalker` cannot be instantiated because of a missing class `org.apache.commons.compress.archivers.tar.TarArchiveInputStream`. This can be due to a library version collision between ConnectFilePulse and Kafka Connect. 

Plugins should be installed into a directory configured with the Kafka Connect `plugin.path` property to ensure classloading isolation (cf. [documentation](https://docs.confluent.io/current/connect/managing/install.html)).

Also, could you give me the Kafka Connect version you are running ? 

Thanks

**Comment by dmarupov** [comment]
Hi @fhussonnois.
I downloaded the ZIP file from Confluent. Then I unzipped it and copied it to the same machine where my Kafka is running in the filepath ../Downloads/streamthoughts-kafka-connect-file-pulse-1.2.1
I also added that filepath: ../Downloads/streamthoughts-kafka-connect-file-pulse-1.2.1 to the plugin.path=../Downloads/streamthoughts-kafka-connect-file-pulse-1.2.1 in my distributed connect configuration file.
I believe my Kafka version is 2.3 based on this: kafka_2.12-2.3.0.jar
Thanks for the quick response.

**Comment by dmarupov** [comment]
> Hi @dmarupov , could you tell me how did you install connect-file-pulse ?
> 
> It seems that the `LocalFSDirectoryWalker` cannot be instantiated because of a missing class `org.apache.commons.compress.archivers.tar.TarArchiveInputStream`. This can be due to a library version collision between ConnectFilePulse and Kafka Connect.
> 
> Plugins should be installed into a directory configured with the Kafka Connect `plugin.path` property to ensure classloading isolation (cf. [documentation](https://docs.confluent.io/current/connect/managing/install.html)).
> 
> Also, could you give me the Kafka Connect version you are running ?
> 
> Thanks

Also to clarify, my Kafka path is ../User/Kafka
and the filepulse is sitting at ../User/Downloads/streamthoughts-kafka-connect-file-pulse-1.2.1
In case if it matters.

**Comment by fhussonnois** [comment]
Ok its seems the connector actually has a dependency on commons-compress which is not included in the lib directory. 

Could you download that Jar : https://mvnrepository.com/artifact/org.apache.commons/commons-compress/1.20 and add it to the `./streamthoughts-kafka-connect-file-pulse-1.2.1/lib directory ` ?

If that work I will push a bugfix release. Thanks

**Comment by dmarupov** [comment]
Awesome thanks @fhussonnois. The error for the missing file but now I get a different error. Should I submit a separate issue for that?

Thanks again.

**Comment by fhussonnois** [comment]
Please, submit a new issue. I close this one when providing a bugfix.

Thanks
