### ISSUE TITLE
filters.ParseDelimitedRow.columns 

### ISSUE THREAD

**Issue by GreenplumDB** [streamthoughts/kafka-connect-file-pulse#253]
Hello, what I want to ask is about the usage of the columns key under DelimitedRowFilter in Processing Filters. There is no example of this parameter in your document.

**Comment by fhussonnois** [comment]
Hi @GreenplumDB, the `columns` property can be used for specifying both the name and type of each column. 
For example, if your row record is  `"LivingRoom,Temperature,20.0,Celcius"` and `columns`property is setted to `sensor:STRING,measurement:STRING, value:DOUBLE,unit:STRING` then your parsed record will be : 

```json
{
  "sensor": "LivingRoom",
  "measurement": "Temperature",
  "value": 20.0,
  "unit": "Celcius"
}
```
