### ISSUE TITLE
DataException when using the JSONFilter type with an empty array. 

### ISSUE THREAD

**Issue by pri-naik5** [streamthoughts/kafka-connect-file-pulse#254]
Hi! Thank you for a great connector! But has this fix been released - https://github.com/streamthoughts/kafka-connect-file-pulse/issues/109? I see that even in the latest version i.e 2.6.0 I get the error -

`io.streamthoughts.kafka.connect.filepulse.data.DataException: Failed to merge schemas for field 'field3'. at io.streamthoughts.kafka.connect.filepulse.data.StructSchema$StructSchemaMerger.apply(StructSchema.java:341) at io.streamthoughts.kafka.connect.filepulse.data.StructSchema.merge(StructSchema.java:260) at io.streamthoughts.kafka.connect.filepulse.data.LazyArraySchema.valueSchema(LazyArraySchema.java:55) at io.streamthoughts.kafka.connect.filepulse.filter.JSONFilter.apply(JSONFilter.java:90) at io.streamthoughts.kafka.connect.filepulse.filter.AbstractMergeRecordFilter.apply(AbstractMergeRecordFilter.java:43) at io.streamthoughts.kafka.connect.filepulse.filter.DefaultRecordFilterPipeline$FilterNode.apply(DefaultRecordFilterPipeline.java:162) at io.streamthoughts.kafka.connect.filepulse.filter.DefaultRecordFilterPipeline.apply(DefaultRecordFilterPipeline.java:134) at io.streamthoughts.kafka.connect.filepulse.filter.DefaultRecordFilterPipeline.apply(DefaultRecordFilterPipeline.java:102) at io.streamthoughts.kafka.connect.filepulse.source.DefaultFileRecordsPollingConsumer.next(DefaultFileRecordsPollingConsumer.java:176) at io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceTask.poll(FilePulseSourceTask.java:199) at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:304) at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:248) at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:188) at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:243) at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) at java.base/java.lang.Thread.run(Thread.java:829) Caused by: io.streamthoughts.kafka.connect.filepulse.data.DataException: Cannot infer value type because LIST is empty at io.streamthoughts.kafka.connect.filepulse.data.LazyArraySchema.valueSchema(LazyArraySchema.java:49) at io.streamthoughts.kafka.connect.filepulse.data.ArraySchema.merge(ArraySchema.java:89) at io.streamthoughts.kafka.connect.filepulse.data.StructSchema.merge(StructSchema.java:255) at io.streamthoughts.kafka.connect.filepulse.data.ArraySchema.merge(ArraySchema.java:86) at io.streamthoughts.kafka.connect.filepulse.data.StructSchema$StructSchemaMerger.apply(StructSchema.java:338)`

My configuration:
`fs.scan.interval.ms: "10000"
    fs.scan.filters: "io.streamthoughts.kafka.connect.filepulse.scanner.local.filter.RegexFileListFilter"
    file.filter.regex.pattern: ".*\\.json$"
    tasks.reader.class: "io.streamthoughts.kafka.connect.filepulse.fs.reader.LocalBytesArrayInputReader"
    topic: "filepulse-avro-v3"
    internal.kafka.reporter.topic: "connect-file-pulse-status"
    fs.cleanup.policy.class: "io.streamthoughts.kafka.connect.filepulse.fs.clean.LogCleanupPolicy"
    fs.listing.class: "io.streamthoughts.kafka.connect.filepulse.fs.LocalFSDirectoryListing"
    fs.listing.directory.path: "/tmp/jsonexamples/"
    filters: "ParseJSON, ExcludeFieldMessage"
    filters.ParseJSON.type: "io.streamthoughts.kafka.connect.filepulse.filter.JSONFilter"
    filters.ParseJSON.source: "message"
    filters.ParseJSON.merge: "true"
    filters.ParseJSON.explode.array: "true"
    filters.ExcludeFieldMessage.type: "io.streamthoughts.kafka.connect.filepulse.filter.ExcludeFilter"
    filters.ExcludeFieldMessage.fields: "message"`

Json Example:

`[
  {
    "field1": "test1",
    "field2" : "test5",
    "field3": [
      {
        "field3_a": "test",
        "field3_b": "test2",
        "field3_c": "test3"
      }
    ],
    "field4": {
      "field4a": "",
      "field4b": "",
      "field4c": "",
      "field4d": "",
      "field4e": "",
      "field4f": "",
      "field4g": "",
      "field4h": [
        {
          "field4ha": "",
          "field4hb": "",
          "field4hc": ""
        }
      ]
    }
  },
  {
    "field1": "test1",
    "field2" : "test5",
    "field3": [],
    "field4": {
      "field4a": "",
      "field4b": "",
      "field4c": "",
      "field4d": "",
      "field4e": "",
      "field4f": "",
      "field4g": "",
      "field4h": [
        {
          "field4ha": "",
          "field4hb": "",
          "field4hc": ""
        }
      ]
    }
  }
]`

Thanks!

**Comment by fhussonnois** [comment]
Hi @pri-naik5, thank your for reporting this issue. I will investigate to try to reproduce your error.

**Comment by pri-naik5** [comment]
Hi @fhussonnois, thanks. Is there a possible workaround I could do for this without needing to preprocess the files externally? We have a host of files which can have such empty arrays.

**Comment by fhussonnois** [comment]
Hi @pri-naik5, sorry for the late reply. Could you try the version from the master branch ?  I pushed a commit(https://github.com/streamthoughts/kafka-connect-file-pulse/commit/82c3597bf02666f903312c78384c340722241e72) that should fix this issue. You should be able to test it using the docker image :  

     docker pull streamthoughts/kafka-connect-file-pulse:master

**Comment by pri-naik5** [comment]
Hi @fhussonnois Thanks! I think I need a zip file as I am running this on Strimzi and I need to add all the dependencies to a docker file
