### ISSUE TITLE
Files are not being processed when more records are added

### ISSUE THREAD

**Issue by dmarupov** [streamthoughts/kafka-connect-file-pulse#27]
I have a file pulse connector running and it is processing the files when I initially start the connector. But after the initial processing, I am manually adding more data into the file and at this point it is not being processed. Is this normal or expected? If so, is there a way to change.configure it so that everytime there is a new data added to the file it is processed near real-time?

Thank you in advance for your help.

**Comment by fhussonnois** [comment]
First, you can consume the internal topic configured using the property `internal.kafka.reporter.topic` to see if you file is considered `COMPLETED` or not.

Secondly, the `RowFileInputReader` can be configured to wait for more bytes. Try to configure the property : 

* `read.max.wait.ms` : Maximum time to wait in milliseconds for more bytes after hitting end of file.

**Comment by dmarupov** [comment]
Using read.max.wait.ms worked but I am still running into the same issue of the file being COMPLETED after the time for read.max.wait.ms runs out. Is there a way to configure it to have the file COMPLETED only if there is a new file created? Or if there is another/next file to process?
Thank you.

**Comment by dmarupov** [comment]
I just tested it again. I set the read.max.wait.ms=600000 and added a file to the directory specified with 10 lines of records in it. When I first start the connector it reads it fine. Then I went ahead and added another 10 records to the file but nothing happened. 10 minutes passed and the file just got COMPLETED without processing the newly added records. It seems that it is not able to process records real-time. Only batch processing the files once, but when new records are added to the file it is not able to process the newly added data.

**Comment by dmarupov** [comment]
One more thing to note is that when I restart the connector it does pickup those newly added records but for some reason it can't process the data as they are being written to the file. Is this an expected behavior?

**Comment by dmarupov** [comment]
Update: I installed the new version of the Connect File Pulse, 1.3.0 to be precise and it seemed to fix some of the issues. For testing purposes I "read.max.wait.ms=120000", which is 2 minutes. Now I am able to process files every 2 minutes. However, this still marks the file COMPLETED after waiting for 2 minutes. For example, if there were no new records written in the file for period of 2 minutes, then the file gets COMPLETED. This works well but at the same time it is introducing another issue. Even if there are new records being written into the file they get processed every only every 2 minutes. 
Is there a way to configure file pulse in such a way that it will wait to listen for more records being written into a file but at the same time read records as they are being written? According to my testing this is not the case at the moment or at least with my configuration. I want to be able to read records from file line by line as they are being written without waiting for "read.max.wait.ms". Is it possible? 
Thank you.

**Comment by fhussonnois** [comment]
Hi @dmarupov, I will try to reproduce that issue. The expected behavior is that the connector should check every 100ms if new data is written to the input file. A file should be completed if no new data is added to the file for more than `read.max.wait.ms`.

**Comment by dmarupov** [comment]
I think it is checking every 10 seconds or so if the new data is written to the input file but it is not processing the data until the "read.max.wait.ms" time runs out.

**Comment by fhussonnois** [comment]
Hi @dmarupov, I figured out how to reproduce the problem. I'm currently testing a patch that should be available this week.

**Comment by dmarupov** [comment]
Hi @fhussonnois,
Is this solution added to the filepulse 1.5.0 release?

Thank you.

**Comment by fhussonnois** [comment]
Hi @dmarupov, yes your problem should be solved usin the last available version 1.5.4.
