### ISSUE TITLE
Record as string

### ISSUE THREAD

**Issue by pradeepsh2203** [streamthoughts/kafka-connect-file-pulse#306]
How can I get a row of CSV files as a String rather than a struct or record? for example
My file is :
a,b,c
d,e,f

I want the records to look like 
a,b,c
d,e,f
and not like
{schema:{"type":"struct","fields":[{"type":"string","field":"message"}]}, payload:{message:"a,b,c"}}
{schema:{"type":"struct","fields":[{"type":"string","field":"message"}]}, payload:{message:"d,e,f"}}

**Comment by bsvicente** [comment]
Hey @pradeepsh2203 
try to set value.converter.schemas.enable: false
