### ISSUE TITLE
SASL_SSL Support

### ISSUE THREAD

**Issue by mohai-kafka** [streamthoughts/kafka-connect-file-pulse#32]
Very good connector. We are using Confluent cloud and it support SASL_SSL. I am not seeing any reference in document. Can you let me know is this connector support SASL_SSL if yes can you provide implementation reference. 

Thanks in advance.

**Comment by fhussonnois** [comment]
Hi @mohai-kafka, Yes this answer should help you : https://github.com/streamthoughts/kafka-connect-file-pulse/issues/19

**Comment by mohai-kafka** [comment]
Thanks for your response. We configure following way from java. Samething need to do it in connector configuration?

bootstrap.servers=XXXX:9092
security.protocol=SASL_SSL
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule   required username="{{ CLUSTER_API_KEY }}"   password="{{ CLUSTER_API_SECRET }}";
ssl.endpoint.identification.algorithm=https
sasl.mechanism=PLAIN

**Comment by fhussonnois** [comment]
Connect File Pulse uses an internal topic to synchronize the Connector instances and Tasks. You have to configure the producer/consumer that are internally created by the connector. To do that you have to duplicate your security configuration with that prefixes : 

* `internal.kafka.reporter.consumer.` 
* ` internal.kafka.reporter.producer.`

**Comment by mohai-kafka** [comment]
That works. Thanks for your help.
