### ISSUE TITLE
well-formed error

### ISSUE THREAD

**Issue by mohai-kafka** [streamthoughts/kafka-connect-file-pulse#33]
When i read XML file using pulse connector i am getting following error. 

 ERROR Error while processing source file '[name='Sample_Member_Enrollment_Status_File-3.xml', path='/opt/kafka/confluent/tmp', size=1681, lastModified=1590085242000, inode=5097008, hash=1839052428]' (io.streamthoughts.kafka.connect.filepulse.source.KafkaFileStateReporter:118)
io.streamthoughts.kafka.connect.filepulse.reader.ReaderException: Unexpected error happened while initializing 'XMLFileInputIterator'
        at io.streamthoughts.kafka.connect.filepulse.reader.XMLFileInputReader$XMLFileInputIterator.<init>(XMLFileInputReader.java:111)
        at io.streamthoughts.kafka.connect.filepulse.reader.XMLFileInputReader.newIterator(XMLFileInputReader.java:75)
        at io.streamthoughts.kafka.connect.filepulse.reader.AbstractFileInputReader.newIterator(AbstractFileInputReader.java:55)
        at io.streamthoughts.kafka.connect.filepulse.source.FileInputIterable.open(FileInputIterable.java:66)
        at io.streamthoughts.kafka.connect.filepulse.source.DefaultFileRecordsPollingConsumer.openAndGetIteratorOrNullIfInvalid(DefaultFileRecordsPollingConsumer.java:278)
        at io.streamthoughts.kafka.connect.filepulse.source.DefaultFileRecordsPollingConsumer.next(DefaultFileRecordsPollingConsumer.java:156)
        at io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceTask.poll(FilePulseSourceTask.java:127)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:270)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:237)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:184)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:234)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.xml.sax.SAXParseException; lineNumber: 14; columnNumber: 26; The content of elements must consist of well-formed character data or markup.
        at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
        at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
        at io.streamthoughts.kafka.connect.filepulse.reader.XMLFileInputReader$XMLFileInputIterator.<init>(XMLFileInputReader.java:96)
        ... 15 more

My configuration is 

{
  "config": {
    "connector.class": "io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector",
    "fs.cleanup.policy.class": "io.streamthoughts.kafka.connect.filepulse.clean.LogCleanupPolicy",
    "fs.scanner.class": "io.streamthoughts.kafka.connect.filepulse.scanner.local.LocalFSDirectoryWalker",
    "fs.scan.directory.path": "/opt/kafka/confluent/tmp/",
    "fs.scan.interval.ms": "5000",
    "offset.strategy": "name",
    "read.max.wait.ms": "5000",
    "task.reader.class": "io.streamthoughts.kafka.connect.filepulse.reader.XMLFileInputReader",
    "topic": "sampleTopic",
    "tasks.max": 1,
    "internal.kafka.reporter.bootstrap.servers": "XXXXX",
    "internal.kafka.reporter.id": "connect-file-pulse-xml",
    "internal.kafka.reporter.topic": "connect-file-pulse-status",
    "internal.kafka.reporter.consumer.security.protocol":"SASL_SSL",
    "internal.kafka.reporter.consumer.sasl.jaas.config":"org.apache.kafka.common.security.plain.PlainLoginModule required username='XXXXX' password='XXXXXX",
    "internal.kafka.reporter.consumer.ssl.endpoint.identification.algorithm":"https",
    "internal.kafka.reporter.consumer.sasl.mechanism":"PLAIN",
    "internal.kafka.reporter.producer.security.protocol":"SASL_SSL",
    "internal.kafka.reporter.producer.sasl.jaas.config":"org.apache.kafka.common.security.plain.PlainLoginModule required username='XXXXXXXX' password='XXXXXX",
    "internal.kafka.reporter.producer.ssl.endpoint.identification.algorithm":"https",
    "internal.kafka.reporter.producer.sasl.mechanism":"PLAIN",
    "xpath.expression":"/Members/Member[1]"	
  },
  "name": "connect-file-pulse-quickstart-XML"
}

XML file content is 

<?xml version="1.0" encoding="utf-8"?>
<Members>
 <Member xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <Hicn></Hicn>
    <PlanName></PlanName>
    <MemberLastName></MemberLastName>
    <MemberFirstName></MemberFirstName>
    <AppId></AppId>
<Member>
<Members>

**Comment by mohai-kafka** [comment]
I think XML content is missing. Below.

<?xml version="1.0" encoding="utf-8"?>
<Members>
 <Member xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <Hicn></Hicn>
    <PlanName></PlanName>
    <MemberLastName></MemberLastName>
    <MemberFirstName></MemberFirstName>
    <AppId></AppId>
<Member>
<Members>

**Comment by mohai-kafka** [comment]
"\<?xml version="1.0" encoding="utf-8"?>
\<Members>
 \<Member xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  \<Hicn></Hicn>
  \<PlanName></PlanName>
 \<MemberLastName></MemberLastName>
 \<MemberFirstName></MemberFirstName>
 \<AppId></AppId>
\</Member>
\</Members>"

**Comment by fhussonnois** [comment]
Hi @mohai-kafka, could you tell me which FilePulse connector version you are using ?

**Comment by mohai-kafka** [comment]
streamthoughts-kafka-connect-file-pulse-1.2.1.

I changed my XML and xpath now i am not seeing error but i am not getting any message in my destination topic. 

XML is
\<?xml version="1.0" encoding="UTF-8"?>
\<beans xmlns="http://www.springframework.org/schema/beans" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-4.1.xsd">
\<bean id="acc" class="org.spring.tutorials.part1.Account"/>
\</beans>

My xpath is :  "xpath.expression":"/beans/bean[1]"	

Message in internal.kafka.reporter.topic is
{"metadata":{"name":"new3.xml","path":"/opt/kafka/confluent/tmp","size":478,"lastModified":1590525169000,"inode":7046333,"hash":1850816250},"offset":{"position":-1,"rows":0,"timestamp":1590527367573},"status":"READING","props":{"hostname":"ip"}}

**Comment by fhussonnois** [comment]
Ok, the `XMLFileInputReader` has an issue in 1.2.1 that should be resolved in more recent versions.
Could you installed FilePulse Connector 1.3 from : https://github.com/streamthoughts/kafka-connect-file-pulse/releases/tag/v1.3.0

You can use the confluent-hub CLI to install the downloaded zip file.

```bash
$ confluent-hub install --no-prompt streamthoughts-kafka-connect-file-pulse-1.3.0.zip
```

**Comment by mohai-kafka** [comment]
I applied new version still i am not getting message in my destination topic. internal status topic message bellow.

{"metadata":{"name":"new3.xml","path":"/opt/kafka/confluent/tmp","size":478,"lastModified":1590525169000,"inode":5097033,"hash":1850816250},"offset":{"position":-1,"rows":0,"timestamp":1590529322828},"status":"SCHEDULED","props":{"hostname":"ip-10-136-132-222"}}
{"metadata":{"name":"new3.xml","path":"/opt/kafka/confluent/tmp","size":478,"lastModified":1590525169000,"inode":5097033,"hash":1850816250},"offset":{"position":-1,"rows":0,"timestamp":1590529323240},"status":"STARTED","props":{"hostname":"ip-10-136-132-222"}}
{"metadata":{"name":"new3.xml","path":"/opt/kafka/confluent/tmp","size":478,"lastModified":1590525169000,"inode":5097033,"hash":1850816250},"offset":{"position":-1,"rows":0,"timestamp":1590529323240},"status":"COMPLETED","props":{"hostname":"ip-10-136-132-222"}}
{"metadata":{"name":"new3.xml","path":"/opt/kafka/confluent/tmp","size":478,"lastModified":1590525169000,"inode":5097033,"hash":1850816250},"offset":{"position":-1,"rows":0,"timestamp":1590529323240},"status":"CLEANED","props":{"hostname":"ip-10-136-132-222"}}

**Comment by fhussonnois** [comment]
Does an exception occurred while processing the files ?Did you try to configure the `xpath.expression` to `//beans/bean[1]` ?

**Comment by fhussonnois** [comment]
Could you share me an XML file sample to investigate your problem ?

**Comment by mohai-kafka** [comment]
There is no error. yes I tried above xpath expression also.

My xml is 

\<?xml version="1.0" encoding="UTF-8"?>
\<beans xmlns="http://www.springframework.org/schema/beans" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-4.1.xsd">
\<bean id="acc" class="org.spring.tutorials.part1.Account"/>
\<bean id="acc1" class="org.spring.tutorials.part1.Account"/>
\<bean id="acc2" class="org.spring.tutorials.part1.Account"/>
\</beans>

**Comment by fhussonnois** [comment]
This XPath should work `//*[local-name()='bean']`

**Comment by mohai-kafka** [comment]
Works perfectly. Thanks for your help.
