### ISSUE TITLE
decode BytesArray from S3

### ISSUE THREAD

**Issue by arnitolog** [streamthoughts/kafka-connect-file-pulse#353]
Hello,

I'm trying to use file-pulse connector to parse emails, stored on S3. each email is a separate multiline file. The problem is when I use AmazonS3RowFileInputReader I get a message for every line and then it is unclear how to join them back into the one document. On the other hand, when I use AmazonS3BytesArrayInputReader I have the whole document in one message with the following format:
`{"message":"<bytesarray>"}`
And I have not found the way to decode the <bytesarray> to apply some processing filters on it (like matches to filter for the specific recipient, or some keywords)
I also tried to set `value.converter: "org.apache.kafka.connect.converters.ByteArrayConverter"` but got an error:
`org.apache.kafka.connect.errors.DataException: Invalid schema type for ByteArrayConverter: STRUCT`
Is there a way to do what I want with the file-plus connector?

**Comment by fhussonnois** [comment]
Hi @arnitolog, I'm not sure to understand why would you like to regroup all lines into a single message. But, you can maybe try to use the [filter chain mecansim](https://streamthoughts.github.io/kafka-connect-file-pulse/docs/developer-guide/filters-chain-definition/) with the following filters: 

* https://streamthoughts.github.io/kafka-connect-file-pulse/docs/developer-guide/filters/#grokfilter : to parse email
* https://streamthoughts.github.io/kafka-connect-file-pulse/docs/developer-guide/filters/#multirowfilter : to group rows based on a pattern;

**Comment by tiphdousset** [comment]
Hey @arnitolog I've a similar problem and also look for a solution to convert back the BytesArray generated by the AmazonS3BytesArrayInputReader into the original String.
Did you find a solution/workaround to your problem that you could share with me?
Thanks!
