### ISSUE TITLE
fileName as part of Kafka messge

### ISSUE THREAD

**Issue by mohandarsi** [streamthoughts/kafka-connect-file-pulse#355]
Is it possible to include filename as part of message.
I have configured the connect file with one of the example configuration,
I am processing several hundred files But at receiver side, i receive messages with just file content without any origin details.
And this doesnot make any sense for us to look into detail without knowing the source filename.

Is there any configuration item which i can specify to include filename as part of message??

If not, is it possible to provide the feature.

Thank you

**Comment by fhussonnois** [comment]
Hi @mohandarsi, by default all file metadata are added to the Kafka record headers. In addition, if you want to get those metadata part of the record-value you can still use the processor filter chain mecanism.

Here are some documentation: 
- https://streamthoughts.github.io/kafka-connect-file-pulse/docs/developer-guide/accessing-data-and-metadata
- https://streamthoughts.github.io/kafka-connect-file-pulse/docs/developer-guide/filters/
