### ISSUE TITLE
Cannot find RegexFileFilter

### ISSUE THREAD

**Issue by akhileshacc** [streamthoughts/kafka-connect-file-pulse#37]
I wanted to filter out files except for .txt using 
```
fs.scan.filters=io.streamthoughts.kafka.connect.filepulse.scanner.local.filter.RegexFileFilter
file.filter.regex.pattern="\\.txt$"
```
But it seems like there is not class in repo.
Do you plan to add it ?

**Comment by fhussonnois** [comment]
Hi @akhileshacc, he documentation is not correct, the class name is `io.streamthoughts.kafka.connect.filepulse.scanner.local.filter.RegexFileListFilter`

**Comment by akhileshacc** [comment]
Got it, Thanks 👍
