### ISSUE TITLE
How to specify config fields for file readers

### ISSUE THREAD

**Issue by akhileshacc** [streamthoughts/kafka-connect-file-pulse#38]
I am using row file reader, as 
```
task.reader.class=io.streamthoughts.kafka.connect.filepulse.reader.RowFileInputReader
```
It has configs like skip.headers, etc.
How do i specify these configs in properties file ?

**Comment by fhussonnois** [comment]
Hi @akhileshacc, you can simply add `skip.headers` as it is in your properties file or json config.

**Comment by akhileshacc** [comment]
Thanks 👍
