### ISSUE TITLE
LocalPropertiesFileInputReaderTest failing in master

### ISSUE THREAD

**Issue by lucarosellini** [streamthoughts/kafka-connect-file-pulse#381]
**Describe the bug**
`LocalPropertiesFileInputReaderTest.should_load_record_given_input_properties_file` fails in master when executing a build with maven.

**To Reproduce**
Execute: `mvn package`

**Expected behavior**
All tests should pass successfully.

**Additional context**
The test tries to load test resource `datasets/local.properties` which is missing in `kafka-connect-filepulse-local-fs` subproject. As a matter of fact, `kafka-connect-filepulse-local-fs` does not even contain a `src/test/resources` folder.
The missing file might not have been committed by mistake since root `.gitignore` contains a `local.properties` entry.

**Comment by fhussonnois** [comment]
Hi @lucarosellini, thank you for reporting this issue. The project has been fixed.
