### ISSUE TITLE
what about the performance of FilePulse comparing with other solution, is it slower?

### ISSUE THREAD

**Issue by nickel-fang** [streamthoughts/kafka-connect-file-pulse#383]
In our case, we need to send many csv files to Kafka. I use spoolDir and FilePulse to test the performance.

The test environments are the same, and I generate 50 csv files, every file contains 500,000 records.

The test result is
send all the records to Kafka need 203 seconds when using spoolDir
`start time: 2023-02-12 10:08:52,120
end time: 2023-02-12 10:12:15,942
duration: 203 seconds`

and it need 598 seconds when using FilePulse
`start time: 2023-02-12 10:41:34,252
end time: 2023-02-12 10:51:32,941
duration: 598 seconds`

The connector config are as below
`{
    "name": "CsvSpoolDir",
    "config": {
        "tasks.max": "10",
        "connector.class": "com.github.jcustenborder.kafka.connect.spooldir.SpoolDirCsvSourceConnector",
        "input.path": "/data/confluent/data/unprocessed",
        "input.file.pattern": ".*\\.csv",
        "error.path": "/data/confluent/data/error",
        "finished.path": "/data/confluent/data/finished",
        "halt.on.error": "false",
        "cleanup.policy": "DELETE",
        "topic": "usage-mediation-raw-perf",
        "empty.poll.wait.ms": "30000",
        "csv.first.row.as.header": "true",
        "key.schema": "{\"name\":\"com.zuora.usage.TransactionKey\",\"type\":\"STRUCT\",\"isOptional\":false,\"fieldSchemas\":{\"transaction_id\":{\"type\":\"STRING\",\"isOptional\":false}}}",
        "value.schema": "{\"name\":\"com.zuora.usage.Transaction\",\"type\":\"STRUCT\",\"isOptional\":false,\"fieldSchemas\":{\"transaction_id\":{\"type\":\"STRING\",\"isOptional\":false},\"event_id\":{\"type\":\"STRING\",\"isOptional\":true},\"account_id\":{\"type\":\"STRING\",\"isOptional\":true},\"tenant_id\":{\"type\":\"STRING\",\"isOptional\":true},\"subscription_id\":{\"type\":\"STRING\",\"isOptional\":true},\"charge_id\":{\"type\":\"STRING\",\"isOptional\":true},\"github_product\":{\"type\":\"STRING\",\"isOptional\":true},\"github_item_id\":{\"type\":\"STRING\",\"isOptional\":true},\"github_owner_id\":{\"type\":\"STRING\",\"isOptional\":true},\"uom\":{\"type\":\"STRING\",\"isOptional\":true},\"qty\":{\"type\":\"FLOAT32\",\"isOptional\":true},\"clock\":{\"type\":\"INT64\",\"isOptional\":true}}}"
    }
}`

`{
    "name": "CsvFilePulse",
    "config": {
        "connector.class": "io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector",
        "filters": "ParseCSVLine,SetKey",
        "filters.ParseCSVLine.extract.column.name": "headers",
        "filters.ParseCSVLine.trim.column": "true",
        "filters.ParseCSVLine.seperator": ",",
        "filters.ParseCSVLine.type": "io.streamthoughts.kafka.connect.filepulse.filter.CSVFilter",
        "filters.ParseCSVLine.columns": "transaction_id:STRING;event_id:STRING;account_id:STRING;tenant_id:STRING;subscription_id:STRING;charge_id:STRING;github_product:STRING;github_item_id:STRING;github_owner_id:STRING;uom:STRING;qty:FLOAT32;clock:INT64",
        "filters.SetKey.type":"io.streamthoughts.kafka.connect.filepulse.filter.AppendFilter",
        "filters.SetKey.field": "$key",
        "filters.SetKey.value": "$value.transaction_id",
        "fs.cleanup.policy.class": "io.streamthoughts.kafka.connect.filepulse.fs.clean.LocalMoveCleanupPolicy",
        "cleaner.output.failed.path":"/data/confluent/data/error",
        "cleaner.output.succeed.path":"/data/confluent/data/finished",
        "fs.cleanup.policy.triggered.on": "COMMITTED",
        "fs.listing.class": "io.streamthoughts.kafka.connect.filepulse.fs.LocalFSDirectoryListing",
        "fs.listing.directory.path": "/data/confluent/data/unprocessed/",
        "fs.listing.filters": "io.streamthoughts.kafka.connect.filepulse.fs.filter.RegexFileListFilter",
        "fs.listing.interval.ms": "30000",
        "file.filter.regex.pattern": ".*\\.csv$",
        "offset.policy.class": "io.streamthoughts.kafka.connect.filepulse.offset.DefaultSourceOffsetPolicy",
        "offset.attributes.string": "name",
        "skip.headers": "1",
        "topic": "usage-mediation-raw-perf",
        "tasks.reader.class": "io.streamthoughts.kafka.connect.filepulse.fs.reader.LocalRowFileInputReader",
        "tasks.file.status.storage.class": "io.streamthoughts.kafka.connect.filepulse.state.KafkaFileObjectStateBackingStore",
        "tasks.file.status.storage.bootstrap.servers": "kafka.kafka.svc.cluster.local:9092",
        "tasks.file.status.storage.topic": "connect-file-pulse-status",
        "tasks.file.status.storage.topic.partitions": 5,
        "tasks.file.status.storage.topic.replication.factor": 2,
        "tasks.max": 10
    }
}`

**Comment by fhussonnois** [comment]
Hi @nickel-fang, thank you very much for your question. 

First, SpoolDir and FilePulse don't use the same design at all. By default, FilePulse will create a dedicated java thread to scan the configured input directory and configure the list of files that must be proceed by tasks. This thread is managed directly by the connector instance. When new files are detected the connector instance triggers a new reconfiguration of tasks leading to a rebalance of the connector's tasks. This may have an impact on performance when running such a test.

In contrast, SpoolDir delegates the input directory scan to all connect tasks. However, you can configure FilePulse with `fs.listing.task.delegation.enabled=true` to get a similar mecanism. 

In addition, you must configure `fs.cleanup.policy.triggered.on=COMPLETED` to have the same cleanup guarentee than SpoolDir. Therefore, a file will be cleaned once all its records has been published without waiting for the kafka producer aknowlegment.

Final thoughts, I think FilePulse may be slower as it uses its own internal data model to manage records' schema dynamically, and this data model needs to be converted to connect data model before publishing data.

I hope this helps you to understand your result better. Please feel free to share your results if you run new tests.

**Comment by nickel-fang** [comment]
@fhussonnois Thank you for your prompt reply.
I modified the configuration according to your suggestion, but it didn't get any improvement.
I share you a document. There are three pics which show the message producing rate in Kafka.
https://docs.google.com/document/d/1EO8Z4Wm4iOGyjIRZ3yRaYwnC13N2sz1iGaP6Nj20l1I/edit?usp=sharing

**Comment by nickel-fang** [comment]
@fhussonnois thanks for you help.
It seemly doesn't get much more improvement. Pls see the last pic in the doc
https://docs.google.com/document/d/1EO8Z4Wm4iOGyjIRZ3yRaYwnC13N2sz1iGaP6Nj20l1I/edit?usp=sharing
