### ISSUE TITLE
Support for reading files from Aliyun OSS

### ISSUE THREAD

**Issue by sunxiaojian** [streamthoughts/kafka-connect-file-pulse#386]
Support for reading files from Aliyun OSS

**Comment by LeeMo2K10** [comment]
Don't see aliyun oss related jars and configurations? Are you sure to support it now?

**Comment by fhussonnois** [comment]
🎉 This issue has been resolved in `v2.13.0` ([Release Notes](https://github.com/streamthoughts/kafka-connect-file-pulse/releases/tag/v2.13.0))
