### ISSUE TITLE
Disappear in Confluent Hub

### ISSUE THREAD

**Issue by alankan-finocomp** [streamthoughts/kafka-connect-file-pulse#419]
The link to Confluent Hub on [this page](https://streamthoughts.github.io/kafka-connect-file-pulse/docs/developer-guide/installation/) is broken. Tried also searching **streamthoughts** or **kafka-connect-file-pulse** but still couldn't find any...
e.g. https://www.confluent.io/hub/#streamthoughts

**Comment by nghia71** [comment]
I don't see it either, have to download manually and install it into connect.

**Comment by alankan-finocomp** [comment]
Funny enough...Confluent Hub has two different ways to be viewed...

https://www.confluent.io/hub/streamthoughts/kafka-connect-file-pulse
