### ISSUE TITLE
Not recognizing the new file after processing the first one

### ISSUE THREAD

**Issue by dmarupov** [streamthoughts/kafka-connect-file-pulse#43]
I have File Pulse finish processing a "file1.JSON" (about 110MB in size) and added a second "file2.JSON" (about 170MB in size) and the File Pulse is not picking up the second file.
Things I have tried:
When I Copy and Paste multiple files into the Directory that File Pulse is watching it works fine and gets processed with no issues.

When I use a C# app to write files into that Directory then the File Pulse will process the first file successfully but not the second one.
I tried to create a new "file2.JSON" with a C# app in the Directory that File Pulse is watching and started writing data into the newly created "file2.CLOG". I monitored the connect-file-pulse-status topic and nothing changed. In other words the connect-file-pulse-status did not produce any new info.

My guess is that the File Pulse is somehow not picking up additional files (after the first file is finished processing) that are being added/written in the Directory that is being watched by File Pulse.

I am using the filepulse 1.3.1 release.

Is there anything else I can try? Any configuration I am missing?

Please help me solve this issue. I would be happy to provide more details if necessary. Thank you.

**Comment by fhussonnois** [comment]
Hi @dmarupov, Normally, the connector should detect and process the second file. Did you observe that log info message "Remaining in progress scheduled files: . Skip directory scan while waiting for tasks completion." ?

**Comment by dmarupov** [comment]
Hi @fhussonnois ,
Where can I see this log info message? The only two places I have been looking at so far are connect-file-pulse-status and kafka-connect-status topics. I am attaching the screenshot of what I got. The connect-file-pulse-status shows the first file process and then nothing else after that. 

![filepulse-process](https://user-images.githubusercontent.com/46696879/88202041-ebbe9b80-cc0d-11ea-9ea5-1797c38e6548.PNG)

**Comment by fhussonnois** [comment]
Hi @dmarupov, I was talking about the Connect worker application logs

**Comment by dmarupov** [comment]
Hi @fhussonnois,
Thank you for your prompt response. The file names are always different when written (we are appending a timestamp at the end of each file when created). I will try to rerun this process and check the Connect worker application log and will post it on here. I can also share the FilePulse config if needed.
Our connect config is pasted below:

bootstrap.servers=https://my.domain.com:9193,https://my.domain.com:9194,https://my.domain.com:9195

security.protocol=SSL

listeners=https://my.ip:8185
rest.advertised.listener=https
rest.advertised.host.name=my.domain.com
rest.advertised.host.port=8185

ssl.truststore.location=/home/user/kafka/ssld/server.truststore.jks
ssl.truststore.password=somepassword
ssl.keystore.location=/home/user/kafka/ssld/server.keystore.jks
ssl.keystore.password=somepassword
ssl.key.password=somepassword

producer.bootstrap.servers=https://my.domain.com:9193,https://my.domain.com:9194,https://my.domain.com:9195
producer.security.protocol=SSL
producer.ssl.truststore.location=/home/user/kafka/sslclient/client.truststore.jks
producer.ssl.truststore.password=somepassword

consumer.bootstrap.servers=https://my.domain.com:9193,https://my.domain.com:9194,https://my.domain.com:9195
consumer.security.protocol=SSL
consumer.ssl.truststore.location=/home/user/kafka/sslclient/client.truststore.jks
consumer.ssl.truststore.password=somepassword

# unique name for the cluster, used in forming the Connect cluster group. Note that this must not conflict with consumer group IDs
group.id=kafka-connect-cluster

# The converters specify the format of data in Kafka and how to translate it into Connect data. Every Connect user will
# need to configure these based on the format they want their data in when loaded from or stored into Kafka
key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter

# Converter-specific settings can be passed in by prefixing the Converter's setting with the converter we want to apply
# it to
key.converter.schemas.enable=true
value.converter.schemas.enable=true

# Topic to use for storing offsets. This topic should have many partitions and be replicated and compacted.
# Kafka Connect will attempt to create the topic automatically when needed, but you can always manually create
# the topic before starting Kafka Connect if a specific topic configuration is needed.
# Most users will want to use the built-in default replication factor of 3 or in some cases even specify a larger value.
# Since this means there must be at least as many brokers as the maximum replication factor used, we'd like to be able
# to run this example on a single-broker cluster and so here we instead set the replication factor to 1.
offset.storage.topic=kafka-connect-offsets
offset.storage.replication.factor=3
offset.storage.partitions=50

# Topic to use for storing connector and task configurations; note that this should be a single partition, highly replicated,
# and compacted topic. Kafka Connect will attempt to create the topic automatically when needed, but you can always manually create
# the topic before starting Kafka Connect if a specific topic configuration is needed.
# Most users will want to use the built-in default replication factor of 3 or in some cases even specify a larger value.
# Since this means there must be at least as many brokers as the maximum replication factor used, we'd like to be able
# to run this example on a single-broker cluster and so here we instead set the replication factor to 1.
config.storage.topic=kafka-connect-configs
config.storage.replication.factor=3

# Topic to use for storing statuses. This topic can have multiple partitions and should be replicated and compacted.
# Kafka Connect will attempt to create the topic automatically when needed, but you can always manually create
# the topic before starting Kafka Connect if a specific topic configuration is needed.
# Most users will want to use the built-in default replication factor of 3 or in some cases even specify a larger value.
# Since this means there must be at least as many brokers as the maximum replication factor used, we'd like to be able
# to run this example on a single-broker cluster and so here we instead set the replication factor to 1.
status.storage.topic=kafka-connect-status
status.storage.replication.factor=3
status.storage.partitions=10

# Flush much faster than normal, which is useful for testing/debugging
offset.flush.interval.ms=10000

# plugin.path=/usr/local/share/java,/usr/local/share/kafka/plugins,/opt/connectors,
plugin.path=/home/user/downloads/file-pulse-1.3.1

**Comment by dmarupov** [comment]
I have recreated this scenario of writing multiple files into the source folder. Each file is being created by a C# App. Once the file is created the C# App started writing to a file line-by-line. After the first file is done writing it starts the next file. I did this with 3 files and all three files were created and written into the source folder as shown in the screenshot.
![Test3FilesLineByLine](https://user-images.githubusercontent.com/46696879/88598377-c6c39180-d02e-11ea-950b-f0f3e1665236.PNG)
 
Below is the result of what I get from **_connect-file-pulse-status_** topic:
{"metadata":{"name":"Test18_20200727_045615.JSON","path":"/mnt/filepulse","size":839238,"lastModified":1595886978000,"inode":36591746974999992,"hash":539398661},"offset":{"position":1062566,"rows":768,"timestamp":1595887091595},"status":"CLEANED","props":{"hostname":"my.domain"}}

Below is the log info from **_connect.log_** file:
[2020-07-27 16:58:17,494] WARN Received cleaned status but no file currently scheduled for partition : '{"name":"Test18_20200727_045615.JSON","hash":"539398661"}', this warn should only occurred during recovering step (io.streamthoughts.kafka.connect.filepulse.scanner.LocalFileSystemScanner:143)
[2020-07-27 16:58:17,996] INFO Finished cleaning all completed source files (io.streamthoughts.kafka.connect.filepulse.scanner.LocalFileSystemScanner:215)
[2020-07-27 16:58:17,996] INFO Remaining in progress scheduled files: 1. Skip directory scan while waiting for tasks completion. (io.streamthoughts.kafka.connect.filepulse.scanner.LocalFileSystemScanner:238)
[2020-07-27 16:58:17,996] INFO Waiting 9494 ms to scan for new files. (io.streamthoughts.kafka.connect.filepulse.source.FileSystemMonitorThread:87)
[2020-07-27 16:58:18,765] INFO WorkerSourceTask{id=FilePulseConnector-0} Committing offsets (org.apache.kafka.connect.runtime.WorkerSourceTask:424)
[2020-07-27 16:58:18,765] INFO WorkerSourceTask{id=FilePulseConnector-0} flushing 0 outstanding messages for offset commit (org.apache.kafka.connect.runtime.WorkerSourceTask:441)
[2020-07-27 16:58:27,490] INFO Remaining in progress scheduled files: 1. Skip directory scan while waiting for tasks completion. (io.streamthoughts.kafka.connect.filepulse.scanner.LocalFileSystemScanner:238)
[2020-07-27 16:58:27,490] INFO Waiting 10000 ms to scan for new files. (io.streamthoughts.kafka.connect.filepulse.source.FileSystemMonitorThread:87)

**Comment by dmarupov** [comment]
Hi @fhussonnois, 
One thing I have noticed is that 

> `**Remaining in progress scheduled files: 1. Skip directory scan while waiting for tasks completion.**`

 Always showing 1 file remaining. Could this be the issue?

**Comment by dmarupov** [comment]
Hi @fhussonnois,
Is there any update on this? Sorry to keep asking about this. It's just that we are behind schedule with our deployment and we were really hoping for this to work. 
Please let me know if I can do anything on my side. I'd be happy to do anything I can to help solve this issue.
Thank you.

**Comment by fhussonnois** [comment]
Hi @dmarupov, sorry for late reply. I will have more time this week to work onyour issue.

Thanks for the application logs and configuration. I may have identified the problem, could you please send multiple lines from the `connect-file-pulse-status` topic ? Also could you confirm me that you  run the connector with its default configuration ? 

* `offset.strategy`=`name+hash`
* `fs.cleanup.policy.class` = ``

Here are what I've noticed :

* The first file has been read as a whole and the `FilePulseSourceTask` has been completed :

`[2020-07-27 16:58:12,098] INFO Orphan task detected - all scheduled files are now completed - waiting for new reconfiguration. (io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceTask:119)`

* The `LocalFileSystemScanner` failed to find a corresponding scheduled file (hence no file is removed from the list of scheduled files) : 

`WARN Received cleaned status but no file currently scheduled for partition : '{"name":"Test18_20200727_045615.JSON","hash":"539398661"}', this warn should only occurred during recovering step`

* Because the file failed to be cleanup (see previous point), the `LocalFileSystemScanner` doesn't start a new scan : 

`[2020-07-27 16:58:17,996] INFO Remaining in progress scheduled files: 1. Skip directory scan while waiting for tasks completion. (io.streamthoughts.kafka.connect.filepulse.scanner.LocalFileSystemScanner:238)`.

I think the problem is that between the time the file is scheduled and the time it is successfully processed its hash changes. However, the file is uniuely identify using `name+hash`. So could, you try to set `offset.strategy`=`path` ?

**Comment by dmarupov** [comment]
Hi @fhussonnois,

Here is the config we are using for Filepulse connector:
```
connector.class=io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector
errors.retry.timeout=3
filters=Drop
filters.Drop.if={{ matches($value.message, .*"File": "(BIKE|VEHICLE|BOAT|SCOOTER)".*) }}
filters.Drop.invert=true
filters.Drop.type=io.streamthoughts.kafka.connect.filepulse.filter.DropFilter
fs.cleanup.policy.class=io.streamthoughts.kafka.connect.filepulse.clean.LogCleanupPolicy
fs.scan.directory.path=/mnt/filepulse
header.converter=org.apache.kafka.connect.storage.StringConverter
internal.kafka.reporter.bootstrap.servers=my.ip.address:9093,my.ip.address:9094,my.ip.address:9095
key.converter=org.apache.kafka.connect.storage.StringConverter
name=FilePulseConnector
offset.strategy=name+hash
read.max.wait.ms=30000
tasks.max=3
topic=mytopicname
value.converter=org.apache.kafka.connect.storage.StringConverter
```

We are using `fs.cleanup.policy.class=io.streamthoughts.kafka.connect.filepulse.clean.LogCleanupPolicy` because it is a required field but we are not really doing anything with the cleanup policy at this point. I tried to set `fs.cleanup.policy.class=''` and `fs.cleanup.policy.class=""` and `fs.cleanup.policy.class=null` but these are throwing an error for us. 

Here is the log from `connect-file-pulse-status` topic with `offset.strategy=path` (this time there were two files `Test19` and `Test25` but only the first file got processed):

```
{"metadata":{"name":"Test19_20200805_094436.JSON","path":"/mnt/filepulse","size":1062566,"lastModified":1596638682000,"inode":902971725287796316,"hash":1232421340},"offset":{"position":-1,"rows":0,"timestamp":1596638689167},"status":"SCHEDULED","props":{"hostname":"my-domain"}}
{"metadata":{"name":"Test19_20200805_094436.JSON","path":"/mnt/filepulse","size":1062566,"lastModified":1596638682000,"inode":902971725287796316,"hash":1232421340},"offset":{"position":0,"rows":0,"timestamp":1596638689401},"status":"STARTED","props":{"hostname":"my-domain"}}
{"metadata":{"name":"Test19_20200805_094436.JSON","path":"/mnt/filepulse","size":1062566,"lastModified":1596638682000,"inode":902971725287796316,"hash":1232421340},"offset":{"position":144256,"rows":199,"timestamp":1596638699006},"status":"READING","props":{"hostname":"my-domain"}}
{"metadata":{"name":"Test19_20200805_094436.JSON","path":"/mnt/filepulse","size":1062566,"lastModified":1596638682000,"inode":902971725287796316,"hash":1232421340},"offset":{"position":294238,"rows":386,"timestamp":1596638709052},"status":"READING","props":{"hostname":"my-domain"}}
{"metadata":{"name":"Test19_20200805_094436.JSON","path":"/mnt/filepulse","size":1062566,"lastModified":1596638682000,"inode":902971725287796316,"hash":1232421340},"offset":{"position":339575,"rows":418,"timestamp":1596638710564},"status":"READING","props":{"hostname":"my-domain"}}
{"metadata":{"name":"Test19_20200805_094436.JSON","path":"/mnt/filepulse","size":1062566,"lastModified":1596638682000,"inode":902971725287796316,"hash":1232421340},"offset":{"position":339575,"rows":418,"timestamp":1596638710564},"status":"READING","props":{"hostname":"my-domain"}}
{"metadata":{"name":"Test19_20200805_094436.JSON","path":"/mnt/filepulse","size":1062566,"lastModified":1596638682000,"inode":902971725287796316,"hash":1232421340},"offset":{"position":339575,"rows":418,"timestamp":1596638710564},"status":"READING","props":{"hostname":"my-domain"}}
{"metadata":{"name":"Test19_20200805_094436.JSON","path":"/mnt/filepulse","size":1062566,"lastModified":1596638682000,"inode":902971725287796316,"hash":1232421340},"offset":{"position":1062566,"rows":768,"timestamp":1596638741649},"status":"READING","props":{"hostname":"my-domain"}}
{"metadata":{"name":"Test19_20200805_094436.JSON","path":"/mnt/filepulse","size":1062566,"lastModified":1596638682000,"inode":902971725287796316,"hash":1232421340},"offset":{"position":1062566,"rows":768,"timestamp":1596638741649},"status":"READING","props":{"hostname":"my-domain"}}
{"metadata":{"name":"Test19_20200805_094436.JSON","path":"/mnt/filepulse","size":1062566,"lastModified":1596638682000,"inode":902971725287796316,"hash":1232421340},"offset":{"position":1062566,"rows":768,"timestamp":1596638741649},"status":"READING","props":{"hostname":"my-domain"}}
{"metadata":{"name":"Test19_20200805_094436.JSON","path":"/mnt/filepulse","size":1062566,"lastModified":1596638682000,"inode":902971725287796316,"hash":1232421340},"offset":{"position":1062566,"rows":768,"timestamp":1596638771649},"status":"COMPLETED","props":{"hostname":"my-domain"}}
{"metadata":{"name":"Test19_20200805_094436.JSON","path":"/mnt/filepulse","size":1062566,"lastModified":1596638682000,"inode":902971725287796316,"hash":1232421340},"offset":{"position":1062566,"rows":768,"timestamp":1596638771649},"status":"CLEANED","props":{"hostname":"my-domain"}}
{"metadata":{"name":"Test19_20200805_094436.JSON","path":"/mnt/filepulse","size":1062566,"lastModified":1596638682000,"inode":902971725287796316,"hash":1232421340},"offset":{"position":-1,"rows":0,"timestamp":1596642146698},"status":"SCHEDULED","props":{"hostname":"my-domain"}}
{"metadata":{"name":"Test19_20200805_094436.JSON","path":"/mnt/filepulse","size":1062566,"lastModified":1596638682000,"inode":902971725287796316,"hash":1232421340},"offset":{"position":1062566,"rows":768,"timestamp":1596638741649},"status":"COMPLETED","props":{"hostname":"my-domain"}}
{"metadata":{"name":"Test19_20200805_094436.JSON","path":"/mnt/filepulse","size":1062566,"lastModified":1596638682000,"inode":902971725287796316,"hash":1232421340},"offset":{"position":1062566,"rows":768,"timestamp":1596638741649},"status":"CLEANED","props":{"hostname":"my-domain"}}
```

Here is the log for Kafka Connect for this test run with `offset.strategy=path` :
```
[2020-08-05 09:53:47,599] INFO Scanning local file system directory '/mnt/filepulse' (io.streamthoughts.kafka.connect.filepulse.scanner.LocalFileSystemScanner:222)
[2020-08-05 09:53:47,609] INFO Completed scanned, number of files detected '2'  (io.streamthoughts.kafka.connect.filepulse.scanner.LocalFileSystemScanner:224)
[2020-08-05 09:53:47,900] INFO Finished lookup for new files : '0' files selected (io.streamthoughts.kafka.connect.filepulse.scanner.LocalFileSystemScanner:229)
[2020-08-05 09:53:47,900] INFO Waiting 9699 ms to scan for new files. (io.streamthoughts.kafka.connect.filepulse.source.FileSystemMonitorThread:87)
[2020-08-05 09:53:49,169] INFO WorkerSourceTask{id=FilePulseConnector-0} Committing offsets (org.apache.kafka.connect.runtime.WorkerSourceTask:424)
[2020-08-05 09:53:49,169] INFO WorkerSourceTask{id=FilePulseConnector-0} flushing 0 outstanding messages for offset commit (org.apache.kafka.connect.runtime.WorkerSourceTask:441)
[2020-08-05 09:53:57,599] INFO Scanning local file system directory '/mnt/filepulse' (io.streamthoughts.kafka.connect.filepulse.scanner.LocalFileSystemScanner:222)
[2020-08-05 09:53:57,607] INFO Completed scanned, number of files detected '2'  (io.streamthoughts.kafka.connect.filepulse.scanner.LocalFileSystemScanner:224)
[2020-08-05 09:53:57,895] INFO Finished lookup for new files : '0' files selected (io.streamthoughts.kafka.connect.filepulse.scanner.LocalFileSystemScanner:229)
[2020-08-05 09:53:57,895] INFO Waiting 9704 ms to scan for new files. (io.streamthoughts.kafka.connect.filepulse.source.FileSystemMonitorThread:87)
[2020-08-05 09:53:59,169] INFO WorkerSourceTask{id=FilePulseConnector-0} Committing offsets (org.apache.kafka.connect.runtime.WorkerSourceTask:424)
[2020-08-05 09:53:59,170] INFO WorkerSourceTask{id=FilePulseConnector-0} flushing 0 outstanding messages for offset commit (org.apache.kafka.connect.runtime.WorkerSourceTask:441)
[2020-08-05 09:54:07,600] INFO Scanning local file system directory '/mnt/filepulse' (io.streamthoughts.kafka.connect.filepulse.scanner.LocalFileSystemScanner:222)
[2020-08-05 09:54:07,609] INFO Completed scanned, number of files detected '2'  (io.streamthoughts.kafka.connect.filepulse.scanner.LocalFileSystemScanner:224)
[2020-08-05 09:54:07,920] INFO Finished lookup for new files : '0' files selected (io.streamthoughts.kafka.connect.filepulse.scanner.LocalFileSystemScanner:229)
[2020-08-05 09:54:07,920] INFO Waiting 9680 ms to scan for new files. (io.streamthoughts.kafka.connect.filepulse.source.FileSystemMonitorThread:87)
[2020-08-05 09:54:09,170] INFO WorkerSourceTask{id=FilePulseConnector-0} Committing offsets (org.apache.kafka.connect.runtime.WorkerSourceTask:424)
[2020-08-05 09:54:09,170] INFO WorkerSourceTask{id=FilePulseConnector-0} flushing 0 outstanding messages for offset commit (org.apache.kafka.connect.runtime.WorkerSourceTask:441)
```

I have noticed that `Completed scanned, number of files detected '2'  (io.streamthoughts.kafka.connect.filepulse.scanner.LocalFileSystemScanner:224)` is showing 2 file detected but `Finished lookup for new files : '0' files selected (io.streamthoughts.kafka.connect.filepulse.scanner.LocalFileSystemScanner:229)` shows 0 files selected.

**Comment by fhussonnois** [comment]
Hi @dmarupov, I'm sorry, it's my bad. Could you please retry with  `offset.strategy=name`. The strategy `path` is identifying each file with there parent absolute path which is in your context `/mnt/filepulse`. 

But, I don't understand why you didn't get an exception on the first scan. Normally, the connector throw an exception if it scans two files that generate the same offset identifier. Were both files present in the input directory when the connector was started ?

**Comment by dmarupov** [comment]
Hi @fhussonnois,

Regarding your second question the answer is no. We created the files one after another with 1 minute wait time interval between each file creation.
I will test the `offset.strategy=name` and submit result as soon as I am done.

Thank you

**Comment by dmarupov** [comment]
After using `offset.strategy=name` the second created file did get processed. I will do some more test and let you know for sure.

Thank you.

**Comment by fhussonnois** [comment]
Hi @dmarupov, could you close this issue if your problem is resolved ? Thanks.

**Comment by dmarupov** [comment]
Hi @fhussonnois,

We were able to process over 50 files with no issues so far. We used `offset.strategy=name` to make it work when processing records line by line from files as the records are being written.

Thank you for your time and help.
