### ISSUE TITLE
Does AmazonS3FileSystemListing support GZipped files?

### ISSUE THREAD

**Issue by loquisgon** [streamthoughts/kafka-connect-file-pulse#444]
I don't think it does since I cannot see it in the code and my runs in msk are not unzipping the files. I was led astray from the `LocalFSDirectoryListing ` into believing that the functionality was across the file systems but it does not seem to be. :(

**Comment by fhussonnois** [comment]
Hi @loquisgon, unfortunately AmazonS3FileSystemListing does not allow to automatically decompress files (at least a gzip file will be seen as a single file). I don't know how challenging it could be to add this functionnality with minical cost on network egress and s3 storage.

**Comment by loquisgon** [comment]
I think rather than decompressing the file first (like the local readers are doing) I would look into streaming out the gzip file, i.e. decompressing on the fly.
