### ISSUE TITLE
xml files not recognized

### ISSUE THREAD

**Issue by hirsche** [streamthoughts/kafka-connect-file-pulse#46]
Hi,
I'd like to ingest XML files using your connector, however, xml files are not recognized/found. Here is my json config

```bash
{
  "config": {
    "connector.class": "io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector",
    "fs.scanner.class": "io.streamthoughts.kafka.connect.filepulse.scanner.local.LocalFSDirectoryWalker",
    "fs.scan.directory.path": "/tmp/kafka-connect/examples/",
    "fs.scan.interval.ms": "10000",
    "fs.scan.filters": "io.streamthoughts.kafka.connect.filepulse.scanner.local.filter.RegexFileListFilter",
    "fs.cleanup.policy.class": "io.streamthoughts.kafka.connect.filepulse.clean.LogCleanupPolicy",
    "file.filter.regex.pattern": "\\.xml$",
    "internal.kafka.reporter.bootstrap.servers": "broker:29092",
    "internal.kafka.reporter.topic": "xmlfile-connect",
    "offset.strategy": "name+hash",
    "task.reader.class": "io.streamthoughts.kafka.connect.filepulse.reader.XMLFileInputReader",
    "topic": "xmlfile-connect",
    "tasks.max": 1
  },
  "name": "xmlfile-connect"
}
```
The output of connect log says:
```log
connect  | 2020-07-24 09:15:13,505 INFO [FileSystemMonitorThread] Completed scanned, number of files detected '0'  (io.streamthoughts.kafka.connect.filepulse.scanner.LocalFileSystemScanner)
connect  | 2020-07-24 09:15:13,951 INFO [FileSystemMonitorThread] Finished lookup for new files : '0' files selected (io.streamthoughts.kafka.connect.filepulse.scanner.LocalFileSystemScanner)
connect  | 2020-07-24 09:15:13,952 INFO [FileSystemMonitorThread] Waiting 9553 ms to scan for new files. (io.streamthoughts.kafka.connect.filepulse.source.FileSystemMonitorThread)
```

although the file `sample-review.xml` exists in the directory `/tmp/kafka-connect/examples/` of the connect container of your docker-compose [example](https://raw.githubusercontent.com/streamthoughts/kafka-connect-file-pulse/master/docker-compose.yml). Could you kindly assist why files are not found? Could you maybe also provide me an XML example for your reader, because I haven't found anything. This would be really a big help.

Many Thanks
Eduard

**Comment by fhussonnois** [comment]
Hi @hirsche, update the `file.filter.regex.pattern` to `"^.*\\.xml$"`. In addition, you have to add the property `xpath.expression` to indicate the nodes to select in your XML Files.

Also, please do not configure the `internal.kafka.reporter.topic` to the same topic than your output topic.

**Comment by hirsche** [comment]
@fhussonnois thanks for your help. Some of your hints I could resolve by myself already, however, e.g. the reporter topic had been still an issue! FYI: [Here](https://streamthoughts.github.io/kafka-connect-file-pulse/docs/developer-guide/scanning-files/#regexfilefilter) at your documentation, I guess, you are missing the  "^.*" part for the regexp as well.

There would be one more question: if I am matching elements (including sub-elements) using an xpath query, would it be possible to map the resulting entities together with their properties (sub-elements) to avro-classes (taken from kafak schema-registry) and then post it to a topic?

Many Thank for your help,
Eduard
