### ISSUE TITLE
is this connector dead?

### ISSUE THREAD

**Issue by miramar-labs** [streamthoughts/kafka-connect-file-pulse#476]
I haven't seen much activity on it for a couple of years....
2.12.0 doesn't work with Avro blob storage
Are there any known complete examples for listing blob storage container folders/files and getting file metadata ONLY?
thanks

**Comment by fhussonnois** [comment]
Hi @miramar-labs, thank for your question, and no this connector is not dead! But unfortunately I don't work on it permanently and I do what I can to make it evolve and maintain it. I'm not paid to work on it, that's the beauty of open source 😊. I apologize if, unfortunately, it may take a few weeks for questions to be answered. 

I will try to work on your issue regaing Azure Blob Storage as soon as possible.

By the way, any contribution are welcomed.

**Comment by miramar-labs** [comment]
Hi Florian! Thanks for replying! So glad to hear it's not dead ! :)
So I was able to get the AVRO working by downgrading to a lower version and making a patch to one file .. I will fork and submit a PR ..
