### ISSUE TITLE
How can i just deploy filepulse without docker or confluent hub

### ISSUE THREAD

**Issue by in-tandem** [streamthoughts/kafka-connect-file-pulse#48]
Hi 
I have been following the document https://streamthoughts.github.io/kafka-connect-file-pulse/docs/getting-started/ for installing

However is there no way to deploy filepulse without using docker/confluent hub? I am trying to give the jar file path in the plugin.path? will that not work

thank you.

**Comment by hirsche** [comment]
I am also new to that project, but I think the command "confluent-hub" together with the zip file do also copies/updates a couple of config files. Just quickly check out what happens during/after the install with confluent-hub then you'll see what is happening.
But why don't you use just docker or install the [command line tool](https://docs.confluent.io/current/connect/managing/confluent-hub/client.html)?

**Comment by fhussonnois** [comment]
Hi @in-tandem, the confluent command-line tool can help to install a connector. Honestly, I think it's a good idea to use it. 

But, you should be able to install the connector manually by unzip the distribution package under one of the directories you have configured (`plugin.paths`) : https://streamthoughts.github.io/kafka-connect-file-pulse/docs/developer-guide/installation/

**Comment by in-tandem** [comment]
i manually unzipped the plugin and updated the plugin.path.it is working now. is there any article somewhere which can point me to preffered mode of deployment in production. for consuming say 25000 >1.5gb CSV files throughout the day. the files come in in bunches.

**Comment by fhussonnois** [comment]
Hi @in-tandem, in production should deploy Kafka Connect in distributed mode. File Pulse can works in distributed mode (ie: with many connect work deployed across multiple hosts) if for example you mount the shared volume that contains all files on each host. Then, configure as many tasks you need to process files in parallel.

**Comment by fhussonnois** [comment]
Hi @in-tandem, could you please close this issue if your problem is resolved. Thanks.

**Comment by alecomputacao** [comment]
Hi people.

Anyone make the configuration of archive .properties inside config dir to filepulse? 

If anybody had a example please...

Thanks a lot.
