### ISSUE TITLE
Can not find kafka-connect-filepulse-api 2.12.0 on maven-central

### ISSUE THREAD

**Issue by matthkoch** [streamthoughts/kafka-connect-file-pulse#488]
Hi there.
we are extending FilePulse by implementing a RecordFilter for the kafka-connect-filepulse connector, which works great.
In our code we therefore have a maven dependency on kafka-connect-filepulse-api.
We would like to use the latest version 2.12.0.
The last version on maven central seems to be 2.8.0.
Do we miss out on something?
Did you move away from maven central?
The dependency we're using is:
```
<dependency>
	<groupId>io.streamthoughts</groupId>
	<artifactId>kafka-connect-filepulse-api</artifactId>
	<version>2.12.0</version>
	<scope>provided</scope>
</dependency>
```
Thanks

**Comment by dbuerkle-averbis** [comment]
Hi guys,
any news on this one?
We would like to move to confluent-platform 7 so we're blocked here.
Thank you

**Comment by fhussonnois** [comment]
Hi, thank you for reporting this issue. Version 2.12.2 should now be available on Maven Central.

**Comment by dbuerkle-averbis** [comment]
That's awesome, thanks.

**Comment by dbuerkle-averbis** [comment]
Next problem: now I cannot get streamthoughts/kafka-connect-file-pulse:2.12.0 from confluent-hub. 
Do you plan to publish it there?
2.10.0 is available in confluent-hub, but is not available on maven-central.
