### ISSUE TITLE
Faster AWS S3 objects scanning

### ISSUE THREAD

**Issue by bjarosze** [streamthoughts/kafka-connect-file-pulse#490]
**Is your feature request related to a problem? Please describe.**
AWS S3 files scanning can take some time if there is a lot of objects in the bucket. For 10000 objects it can take more than 5 minutes (tested using self hosted storage - min.io). This is because for every object in bucket there is request for metadata.

**Describe the solution you'd like**
Maybe there is no need to call for metadata? Most of the data required for listing is available in `S3ObjectSummary` object. The only missing one is contenMD5. But is it really needed? Could ETAG be used?

**Comment by bjarosze** [comment]
I've opened PR that solves this problem: https://github.com/streamthoughts/kafka-connect-file-pulse/pull/491
I've replaced MD5 with ETAG. Not sure if it's correct. Can we pass any digest algorithm here like ETAG?

**Comment by fhussonnois** [comment]
🎉 This issue has been resolved in `v2.13.0` ([Release Notes](https://github.com/streamthoughts/kafka-connect-file-pulse/releases/tag/v2.13.0))
