### ISSUE TITLE
Feature request: send file metadata and process status to configurable topic

### ISSUE THREAD

**Issue by dertin** [streamthoughts/kafka-connect-file-pulse#521]
I find it helpful that you can configure the sending of file metadata to a topic. 
This includes the file's name, dates, line count, size, target topic and more. 
When the connector has fully processed the file, a new status is recorded as 'completed' in the metadata topic.

```json
"fs.metadata.topic": "connect-file-pulse-metadata-csv"
```

**Comment by fhussonnois** [comment]
Hi @dertin, I'm not sure to understand what new feature you would like to see in Filepulse ? File metadata are already sent into a Kafka Topic (default `connect-file-pulse-status`) : https://streamthoughts.github.io/kafka-connect-file-pulse/docs/developer-guide/tracking-files-status/.

The name of the topic can be changed using the `tasks.file.status.storage.topic` property.

I think the documentation can be improved on that part.

**Comment by dertin** [comment]
Thank you, this is useful to me.
