### ISSUE TITLE
JSONFilter doesn't support JSON  array payload

### ISSUE THREAD

**Issue by fhussonnois** [streamthoughts/kafka-connect-file-pulse#56]

**Comment by bwinchester** [comment]
@fhussonnois, Did you end up getting this to work? Finding the same issue where empty arrays are causing a nullpointer exception. Did you just give up and write something to remove arrays?

**Comment by fhussonnois** [comment]
Hi @bwinchester , the JSONFIlter currently supports Array (https://github.com/streamthoughts/kafka-connect-file-pulse/issues/47) but yes there is a bug when input file contains empty arrays, i.e., `[]`. I've just opened a new issue : https://github.com/streamthoughts/kafka-connect-file-pulse/issues/109

**Comment by fhussonnois** [comment]
Hi @bwinchester, I've just pushed a new bugfix release 1.6.2 that fix the issue #109

**Comment by bwinchester** [comment]
> Hi @bwinchester, I've just pushed a new bugfix release 1.6.2 that fix the issue #109

Thank you so much! We’re going to try it out. This is awesome!
