### ISSUE TITLE
Ouestion: Send only file details

### ISSUE THREAD

**Issue by thecontinium** [streamthoughts/kafka-connect-file-pulse#57]
Hi 

I am dealing with large files and don't want to push them all through Kafka but I do want to send the file details when they change of are new; name etc. 

Can this connector just send the file details alone in one Kafka message rather than the contents ?

Cheers

**Comment by fhussonnois** [comment]
Hi @thecontinium, currently the File Pulse has no reader for doing that but this is an easy to add feature. So for example, for each source file, the connector will send one message like this : 

```json
{
  "name":"kafka-connect.log",
  "path":"/var/log/kafka",
  "size":172559,
  "lastModified":1560772525000,
  "inode":1705406,
  "hash":661976312
}
``` 

Is that what you want ?

**Comment by fhussonnois** [comment]
Hi @thecontinium, I've just release File Pulse 1.4.1 which include the new reader  [FileInputMetadataReader](https://streamthoughts.github.io/kafka-connect-file-pulse/docs/developer-guide/file-readers/#fileinputmetadatareader) that you can configure for achieving what illustrated in my previous message.

**Comment by thecontinium** [comment]
Great! I’ll give that a go. Thanks for following up Florian.


On 12 August 2020 at 16:48:27, Florian Hussonnois (notifications@github.com<mailto:notifications@github.com>) wrote:

Hi @thecontinium<https://github.com/thecontinium>, I've just release File Pulse 1.4.1 which include the new reader FileInputMetadataReader<https://streamthoughts.github.io/kafka-connect-file-pulse/docs/developer-guide/file-readers/#fileinputmetadatareader> that you can configure for achieving what illustrated in my previous message.

**Comment by fhussonnois** [comment]
Hi could you please close this issue if your need is resolved. Thanks.

**Comment by thecontinium** [comment]
Resolved. Thanks.
