### ISSUE TITLE
Create new FileFilter to automatically filter out files tracked by "file status"

### ISSUE THREAD

**Issue by mingfang** [streamthoughts/kafka-connect-file-pulse#72]
since files are tracked by
https://streamthoughts.github.io/kafka-connect-file-pulse/docs/developer-guide/tracking-files-status/

it would be a great feature to automatically filter those files when scanning
https://streamthoughts.github.io/kafka-connect-file-pulse/docs/developer-guide/scanning-files/

This effectively creates a one way sync from local fs to Kafka that can automatically handle new files.

**Comment by fhussonnois** [comment]
Hi @mingfang, I'm sorry for the late response. In fact, the input files are already filtered based on the topic `connect-file-pulse-state`. So files that have been cleaned up should not be rescheduled.

**Comment by mingfang** [comment]
@fhussonnois Thanks for the update. Closing.
