### ISSUE TITLE
RowFileInputReader does not tail log files

### ISSUE THREAD

**Issue by shinlim** [streamthoughts/kafka-connect-file-pulse#81]
I am a big fan of the work you have done on FilePulse and need to use the log file streaming functionality that is mentioned in the [FAQ](https://streamthoughts.github.io/kafka-connect-file-pulse/docs/faq/) and [this](https://medium.com/streamthoughts/kafka-connect-filepulse-one-connector-to-ingest-them-all-faed018a725c) medium.com article.

When I tested it using the following config, I observed the feature doesn't work:

```
{
  "name": "tail-log",
  "config": {
    "connector.class": "io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector",
    "fs.scanner.class": "io.streamthoughts.kafka.connect.filepulse.scanner.local.LocalFSDirectoryWalker",
    "fs.cleanup.policy.class": "io.streamthoughts.kafka.connect.filepulse.clean.LogCleanupPolicy ",
    "cleaner.output.failed.path": "/var/log/event/failed",
    "cleaner.output.succeed.path": "/var/log/event/success",
    "fs.scan.directory.path": "/var/log/event",
    "fs.scan.interval.ms": "5000",
    "fs.scan.filters": "io.streamthoughts.kafka.connect.filepulse.scanner.local.filter.RegexFileListFilter",
    "file.filter.regex.pattern":  ".*\\.log$",
    "fs.recursive.scan.enable": "false",
    "internal.kafka.reporter.bootstrap.servers": "localhost:9092",
    "internal.kafka.reporter.topic": "tail-log-status",
    "offset.strategy": "path+name+hash",
    "read.max.wait.ms": "10000",
    "task.reader.class": "io.streamthoughts.kafka.connect.filepulse.reader.RowFileInputReader",
    "topic": "EventLog",
    "tasks.max": 1
  }
}
```

The connector considers the file successfully processed after reading the last line and does not process any lines appended later. It seems this feature is supported by the Confluent FileSource [Connector](https://docs.confluent.io/current/connect/filestream_connector.html) but that connector isn't recommended for production.

Please can you advise if I have configured my connector incorrectly or if this is a bug.

Thank you
Shin

**Comment by fhussonnois** [comment]
Hi @shinlim, thank you for your message. Which version of Connect FilePulse are you using ?

Also, change the `offset.strategy` property to either "path+name" or "inode". But don't use hash because it will change over time.

The most important configuration is `read.max.wait.ms` which is how long you would like to wait for more data to be written to the file before considering the file completed. Currently you are only waiting for 10 seconds maybe this is your issue.

**Comment by shinlim** [comment]
Thank you for your quick reply! We will try this out and post back the result.

**Comment by shinlim** [comment]
Thank you so much for your advice. I corrected my configuration on your recommendation and it seems to produce the intended result.

Once again, kudos on the very powerful plugin you have developed!

For info, I am using File Pulse v1.5.4
