### ISSUE TITLE
RowFileInputReader for writing lines to Kafka as Strings and not structs

### ISSUE THREAD

**Issue by shinlim** [streamthoughts/kafka-connect-file-pulse#82]
RowFileInputReader is writing out struct data for log files I want to write out as-is to Kafka.

### FilePulse configuration:

```
{
  "name": "tail-logger",
  "config": {
    "connector.class": "io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector",
    "fs.scanner.class": "io.streamthoughts.kafka.connect.filepulse.scanner.local.LocalFSDirectoryWalker",
    "fs.cleanup.policy.class": "io.streamthoughts.kafka.connect.filepulse.clean.LogCleanupPolicy ",
    "cleaner.output.failed.path": "/var/log/event/failed",
    "cleaner.output.succeed.path": "/var/log/event/success",
    "fs.scan.directory.path": "/var/log/event",
    "fs.scan.interval.ms": "5000",
    "fs.scan.filters": "io.streamthoughts.kafka.connect.filepulse.scanner.local.filter.RegexFileListFilter",
    "file.filter.regex.pattern":  ".*\\.log$",
    "fs.recursive.scan.enable": "false",
    "internal.kafka.reporter.bootstrap.servers": "localhost:9092",
    "internal.kafka.reporter.topic": "tail-logger-status",
    "offset.strategy": "path+name+hash",
    "read.max.wait.ms": "10000",
    "task.reader.class": "io.streamthoughts.kafka.connect.filepulse.reader.RowFileInputReader",
    "topic": "EventLog",
    "tasks.max": 1
  }
}
```

### Test data that must be written to Kafka as-is
```
Line 1
Line 2
Line 3
```
### Data actually written to Kafka topic by FilePulse

```
{"schema":{"type":"struct","fields":[{"type":"string","optional":true,"field":"message"}],"optional":true},"payload":{"message":"Line 1"}}
{"schema":{"type":"struct","fields":[{"type":"string","optional":true,"field":"message"}],"optional":true},"payload":{"message":"Line 2"}}
{"schema":{"type":"struct","fields":[{"type":"string","optional":true,"field":"message"}],"optional":true},"payload":{"message":"Line 3"}}
```

How can I resolve this issue please?

Thanks in advance.
Shin

**Comment by fhussonnois** [comment]
Hi @shinlim, Yes FilePulse will create a structured record with a field `message` containing the row. To only send the row string you should : 

* Configure the StringConverter as `"value.converter": "org.apache.kafka.connect.storage.StringConverter"`
* Use a KafkaConnect Transfomer to extract the raw from the field `message`: https://docs.confluent.io/current/connect/transforms/extractfield.html#extractfield

**Comment by shinlim** [comment]
Thank you for your quick reply! We will try this out and post back the result 👍

**Comment by shinlim** [comment]
Thank you so much for your advice. I corrected my configuration on your recommendation and it seems to produce the intended result. I was able to develop my use case using filter chaining and the very powerful AppendFilter.

Once again, kudos on the very powerful plugin you have developed!

For info, I am using File Pulse v1.5.4
