### ISSUE TITLE
CREATE  Error Handling and Dead Letter Queues

### ISSUE THREAD

**Issue by juancamilosalazar** [streamthoughts/kafka-connect-file-pulse#84]
Hi, I am trying to do error handling and dead message queue handling, as shown in this confluent example: [https://www.confluent.io/blog/kafka-connect-deep-dive-error-handling-dead-letter-queues/](url), My question is if I can do something similar with kc file pulse, is there any way to be able to send the records that do not comply with a specific structure or that come with errors to an error topic?, On the other hand, how can I throw an error when a record does not meet a valid structure, I am trying to throw an error when the example3 field does not exist: 

>  "filters.ParseLine.columns":"example1:string;example2:string;example3:string",
    "filters.SetKey.field": "$key",
    "filters.SetKey.value": "$value.example1",
    "filters.ValorToNull.type": "io.streamthoughts.kafka.connect.filepulse.filter.FailFilter",
    "filters.ValorToNull.if": "{{ exists($value, 'example3') }}",
    "filters.ValorToNull.invert": true,
    "filters.ValorToNull.message": "Invalid row, example3 is empty : {{ $value }}"

I do not know if I am misusing the "exists" soon, I would appreciate your help too.

This is the data I'm reading:

> 12313112-453543-45334
23313112-153233-13324

and this is my config.

> {
    "connector.class": "io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector",
    "fs.scan.directory.path": "/tmp/kafka-connect/examples/",
    "fs.scan.interval.ms": "10000",
    "fs.scan.filters": "io.streamthoughts.kafka.connect.filepulse.scanner.local.filter.RegexFileListFilter",
    "file.filter.regex.pattern": ".*\\.txt$",
    "task.reader.class": "io.streamthoughts.kafka.connect.filepulse.reader.RowFileInputReader",
    "offset.strategy": "name",
    "topic": "example-topic",
    "internal.kafka.reporter.bootstrap.servers": "kafka1-service:9092",
    "internal.kafka.reporter.topic": "streaming.kc-file-pulse-price.connect-status",
    "tasks.max": 1,
    "filters": "ParseLine,SetKey,ValorToNull",
    "filters.ParseLine.trimColumn": "true",
    "filters.ParseLine.separator": "-",
    "value.converter": "org.apache.kafka.connect.json.JsonConverter",
    "value.converter.schemas.enable": "false",
    "filters.ParseLine.type": "io.streamthoughts.kafka.connect.filepulse.filter.DelimitedRowFilter",
    "fs.cleanup.policy.class": "io.streamthoughts.kafka.connect.filepulse.clean.MoveCleanupPolicy",
    "cleaner.output.succeed.path": "/tmp/kafka-connect/examples/succes",
    "cleaner.output.failed.path": "/tmp/kafka-connect/examples/failed",
    "filters.ParseLine.autoGenerateColumnNames": false,
    "filters.ParseLine.columns":"example1:string;example2:string;example3:string",
    "filters.SetKey.field": "$key",
    "filters.SetKey.value": "$value.example1",
    "filters.ValorToNull.type": "io.streamthoughts.kafka.connect.filepulse.filter.FailFilter",
    "filters.ValorToNull.if": "{{ exists($value, 'example3') }}",
    "filters.ValorToNull.invert": true,
    "filters.ValorToNull.message": "Invalid row, example3 is empty : {{ $value }}"
}

**Comment by juancamilosalazar** [comment]
Hello, is it possible to implement something like this? Or am I looking for other alternatives? Thank you

**Comment by fhussonnois** [comment]
Hi @juancamilosalazar, the Dead Letter Queue is a mechanism which is part of Kafka Connect, but only supported for Sink Connectors only, i.e., you cannot use it with Connect File Pulse.

But, YES it should be possible to implement something similar. 

The `io.streamthoughts.kafka.connect.filepulse.filter.FailFilter` will throw an exception and the file will be marked as FAILED. So, I think this is not the right Filter to use. Instead of that try to use the [ `AppendFilter`](https://streamthoughts.github.io/kafka-connect-file-pulse/docs/developer-guide/filters/#appendfilter).

You should be able to do something like this : 

```
"filters":" CheckMissingField, SetDLQ"
"filters.CheckMissingField.type": "io.streamthoughts.kafka.connect.filepulse.filter.AppendFilter",
"filters.CheckMissingField.if": "{{ exists($value, 'example3') }}",
"filters.CheckMissingField.invert": true,
"filters.CheckMissingField.field": "error",
"filters.CheckMissingField.value": "Invalid row, example3 is empty : {{ $value }}",
"filters.SetDLQ.type": "io.streamthoughts.kafka.connect.filepulse.filter.AppendFilter",
"filters.SetDLQ.if":"{{ exists($value, 'error') }}",
"filters.SetDLQ.field":"$topic",
"filters.SetDLQ.value":"dql-topic"
```

**Comment by juancamilosalazar** [comment]
Oh thank you very much, you just saved my life, I had not thought of using the AppendFilter, really thank you very much, greetings.
