### ISSUE TITLE
File  Pulse connector - Not picking files from local directory

### ISSUE THREAD

**Issue by NaN-7** [streamthoughts/kafka-connect-file-pulse#90]
I need to push XML files from local directory to kafka topic . Connector is detecting the files in the directory as tasks but not processing them to topic.

There is no error in log.
[Connector.txt](https://github.com/streamthoughts/kafka-connect-file-pulse/files/5535864/Connector.txt)

**Comment by fhussonnois** [comment]
Hi @NaN-7, which version of File Pulse are you using ? Also, could you share your connector's configuration ?

**Comment by NaN-7** [comment]
"config":
{"connector.class":"io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector",
"fs.scan.directory.path":"/confluent/confluent-5.5.0/bin/Test/",
"fs.scan.interval.ms":"10000",
"fs.scan.filters":"io.streamthoughts.kafka.connect.filepulse.reader.XMLFileListFilter ",
"file.filter.regex.pattern":".*\\.xml$",
"task.reader.class":"io.stresmthoughts.kafka.connect.filepulse.reader.XMLFileInputReader"
"internal.kafka.reporter.bootstrap.servers": "broker:9092",
"internal.kafka.reporter.topic": "connect-file-pulse-status",
"topic": "test-xml",
"tasks.max": 1,
"fs.cleanup.policy.class": "io.streamthoughts.kafka.connect.filepulse.clean.LogCleanupPolicy",
 "offset.strategy": "name",
"fs.scanner.class": "io.streamthoughts.kafka.connect.filepulse.scanner.local.LocalFSDirectoryWalker",
}

Hi @fhussonnois  , above is the connector config.
Version is 1.5.0

Thanks for the reply.

**Comment by fhussonnois** [comment]
Could you please try to use the latest version 1.6.0 which is not yet available on confluent-hub : https://github.com/streamthoughts/kafka-connect-file-pulse/releases/tag/v1.6.0

You can download the `.zip` file and install it using : `confluent-hub install --no-prompt streamthoughts-kafka-connect-file-pulse-1.6.0.zip`

**Comment by NaN-7** [comment]
Sadly , even after upgrading to 1.6.0 it didn't work . Task is not getting assigned to connector.
If there is any other way?

Thank You.

**Comment by fhussonnois** [comment]
Hi @NaN-7, could you share me the connector application logs ? The connector should log informations while scanning the input directories. Also, is there any messages in the `connect-file-pulse-status` topic ?

**Comment by NaN-7** [comment]
I am attaching pictures for logs and connect-file-pulse-status topic logs, can't attach as a file as restricted by company policy.
Kafka topic name is "sangam_test_source". Please see if it could be of any help.
![connect-Filepulse topic logs](https://user-images.githubusercontent.com/41438298/99451106-b752b600-2947-11eb-8487-b2fd469ce797.jpg)
![Connector logs](https://user-images.githubusercontent.com/41438298/99451163-ccc7e000-2947-11eb-9125-4ee83ff46708.jpg)

**Comment by fhussonnois** [comment]
Hi @NaN-7, the file `t.xml` has been processed but with status `FAILED`. Once a file has been processed by the connector successfully or unsuccessfully, it is automatically ignored in the next scans (even if you restart the connector). The connector may have thrown an exception during the first run.

Try to rename your file so that it will be pickup again by the connector and watch the log file to see the error.

**Comment by NaN-7** [comment]
Hi @fhussonnois fhussonnois,
I have changed the name and added new files too ,created a new connector(with same configs) and ran again, still the same logs are coming (scheduled , failed  , cleaned).

Also on a separate note could you suggest a way to get XML files to a Kafka topic from a "middleware" kind of (don't have the exact details right now) server where are files are coming in real time through another API call(but not getting stored anywhere in middleware server) , using "filepulse" connector or some other resource.

Thanks in advance.

**Comment by NaN-7** [comment]
Hi @fhussonnois , Each Line in input XML is coming as a separate message, could you please suggest a way past that?
