### ISSUE TITLE
Convert CSV to JON

### ISSUE THREAD

**Issue by bob-tran-goldenowl** [streamthoughts/kafka-connect-file-pulse#92]
how to i can convert csv to json?

**Comment by fhussonnois** [comment]
Hi @bob-tran-goldenowl, The conversion to JSON or any other format is not performed directly by Connect File Pulse. This is done by the Kafka Connect Converters.  I suggest to you to read this article from Confluent : https://www.confluent.fr/blog/kafka-connect-deep-dive-converters-serialization-explained/

Basically, if you configure the JSONConverter then the records parses from CSV by FilePulse will be converted to JSON.
