### ISSUE TITLE
How to parse a multiple key/value row source

### ISSUE THREAD

**Issue by stuarthrichardson** [streamthoughts/kafka-connect-file-pulse#94]
Hi

I am new to this, I need help configuring the file pulse to parse a multiple key/value  source row and transform to a Json row.

Import row format
```
<133>Id= "8adce0c9-2e65-11eb-8397-a08869f17097" Type="2" Name="Joe Smith" Application="java.exe" AsAtDateTime="24/11/2020 15:30:48".....
<133>Id= "c3a1a26d-2e66-11eb-8443-50eb71384220" Type="2" Name="Joe Bloggs" Application="java.exe" AsAtDateTime="24/11/2020 15:30:48".....
<133>Id= "ce144420-2e68-11eb-9235-106530e5ad2a" Type="10" Name="Joe Bloggs" Application="outlook.exe" AsAtDateTime="24/11/2020 15:30:48".....
```

Output row format
```
{ "Id": "8adce0c9-2e65-11eb-8397-a08869f17097", "Type": "2", "Name": "Joe Smith", "Application": "java.exe", "AsAtDateTime": "24/11/2020 15:30:48"..... }
{ "Id": "c3a1a26d-2e66-11eb-8443-50eb71384220", "Type": "2", "Name": "Joe Bloggs", "Application": "java.exe", "AsAtDateTime": "24/11/2020 15:30:48"..... }
{ "Id": "ce144420-2e68-11eb-9235-106530e5ad2a", "Type": "10", "Name": "Joe Bloggs", "Application": "outlook.exe", "AsAtDateTime": "24/11/2020 15:30:48"..... }
```

I can deal with the fixing the date/times, as I have seen the an example for this.

I am assuming this is done by configurating the filtering, is there a way to do this?

By the way, the pulse file is an awesome source connector and I have been able using the examples create configuration for the csv, json and xml sources files.

**Comment by fhussonnois** [comment]
Hi @stuarthrichardson, thank you very much for your feedback.

First you need to configure the  Reader : 
`"task.reader.class": "io.streamthoughts.kafka.connect.filepulse.reader.RowFileInputReader"`

Then, to parse each row it should be possible to chain:
1.  One [AppendFilter](https://streamthoughts.github.io/kafka-connect-file-pulse/docs/developer-guide/filters/#appendfilter) with an expression to split each elements : {{ split($.message, ' ') }}
2. One [AppendFilter](https://streamthoughts.github.io/kafka-connect-file-pulse/docs/developer-guide/filters/#appendfilter) for each column with an expression like : {{ extarct_array($.message, 0)}}

Or, you can also use the [GrokFilter](https://streamthoughts.github.io/kafka-connect-file-pulse/docs/developer-guide/filters/#grokfilter) to parse and extract each field using a single filter. The GrokFilter is equivalent to the Grok expressions of [Logstash](https://www.elastic.co/guide/en/logstash/current/plugins-filters-grok.html).

Connect File Pulse already contains a lot of expressions which are automatically loaded when the filter is used: https://github.com/streamthoughts/kafka-connect-file-pulse/tree/master/connect-file-pulse-filters/src/main/resources/patterns

If you write your own expression, you can use this tool to test your Grok expressions: http://grokdebug.herokuapp.com/

For example, you can create a local file with you expression : 

```bash
$ cat <<EOF > /tmp/grok-patterns/custom.patern
MY_GROK_EXPR=%{DATA:id} %{INT:type}  %{DATA:name} ...
EOF
```

And use it like this:

```bash
"filters.ParseLine.type": "io.streamthoughts.kafka.connect.filepulse.filter.GrokFilter",
"filters.ParseLine.match": "%{MY_GROK_EXPR}",
"filters.ParseLine.overwrite": "message",
"filters.ParseLine.source": "message",
"filters.ParseLine.ignoreFailure": "true",
"filters.ParseLine.patternsDir": "/tmp/grok-patterns"
```

NOTE: It could be useful to use an AppendFilter first to remove all double-quotes. The grok expression will be simpler.

**Comment by stuarthrichardson** [comment]
I decided to go with the Grok expression, I have not been able to get this to work.  The Grok expression I am using works fine using the Grok expression test tool.

This Grok expression works with the test tool 
`<133>Id= "%{DATA:id}" Type="%{INT:type}" Name="%{DATA:name}" Application="%{DATA:application}" AsAtDateTime="%{DATA:asatdatetime}".....`

I have tried
`MY_GROK_EXPR=<133>Id= "%{DATA:id}" Type="%{INT:type}" Name="%{DATA:name}" Application="%{DATA:application}" AsAtDateTime="%{DATA:asatdatetime}".....`
and
`MY_GROK_EXPR <133>Id= "%{DATA:id}" Type="%{INT:type}" Name="%{DATA:name}" Application="%{DATA:application}" AsAtDateTime="%{DATA:asatdatetime}".....`


Below is the output I am getting
`{"message":"<133>Id= "8adce0c9-2e65-11eb-8397-a08869f17097" Type="2" Name="Joe Smith" Application="java.exe" AsAtDateTime="24/11/2020 15:30:48"..... " }`

Not sure what is going wrong, any ideas?

**Comment by stuarthrichardson** [comment]
Ok, I have set the the filters.ParseLine.match property to the Grok expression

`"filters.ParseLine.match": "<133>Id=\"%{DATA:id}\" Type=\"%{INT:type}\" Name=\"%{DATA:name}\" Application=\"%{DATA:application}\" AsAtDateTime=\"%{DATA:asatdatetime}\"....."`

Now getting the following output

`{"message":"<133>Id= "8adce0c9-2e65-11eb-8397-a08869f17097" Type="2" Name="Joe Smith" Application="java.exe" AsAtDateTime="24/11/2020 15:30:48"..... "  "id":"8adce0c9-2e65-11eb-8397-a08869f17097", "type":"2", "name":"Joe Smith" "application":"java.exe","asatdatetime":"24/11/2020 15:30:48".... }`

That is good except the "message" element, how do I remove the "message" element?

**Comment by stuarthrichardson** [comment]
Ok, using ExcludeFilter to remove the element.  You are seeing my learning curve....

**Comment by fhussonnois** [comment]
Hi @stuarthrichardson , good to see you finally a solution to your problem. I'm just curious why the grok expression was not working using the external file. Did the Kafka Connect worker had access to your file ?
