### ISSUE TITLE
In Version 1.6, function normalizeSchemaName() breaks if key name starts with underscore

### ISSUE THREAD

**Issue by akhileshacc** [streamthoughts/kafka-connect-file-pulse#95]
I have created a custom xml reader, which has key named "_id". I see that connector started to break on upgrading to version 1.6 from 1.3.
So, i tested the function locally, it seems to be breaking.

https://github.com/streamthoughts/kafka-connect-file-pulse/blob/999b906b724cfbc0cea968a3aa1aa094ae50a64f/connect-file-pulse-api/src/main/java/io/streamthoughts/kafka/connect/filepulse/source/internal/ConnectSchemaMapper.java#L52

**Comment by fhussonnois** [comment]
Hi @akhileshacc, could you confirm me that you get an `java.lang.StringIndexOutOfBoundsException: begin 0, end 1, length 0` ? 
Does the `_id` field a Struct ?

**Comment by akhileshacc** [comment]
Yes I got the above error and `_id` is a field in my TypedStruct.

**Comment by fhussonnois** [comment]
Ok thanks, I will provide a fix for this issue.
