### ISSUE TITLE
Column definition with DelimitedRowFilter

### ISSUE THREAD

**Issue by jbandy67** [streamthoughts/kafka-connect-file-pulse#97]
I just started testing this connector to ingest log files and I can't seem to get my reader configuration quite right.  I can get the examples to work but when I try to read a delimited log file with no headers I'm getting an error when I try to manually define the columns.

According to the documentation the DelimitedRowFilter columns configuration is defined as _The list of comma-separated column names in order they appear in each row. columns must be in the form of NAME:TYPE_

My JSON configuration file contains the following section of configuration for the DelimitedRowFilter:
    "connector.class": "io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector",
    "filters": "ParseDelimitedRow",
    "filters.ParseDelimitedRow.columns": "messagedate:date,messagetype:string,messagenum:int,message:string",
    "filters.ParseDelimitedRow.separator": "[|*]",
    "filters.ParseDelimitedRow.trimColumn": "true",
    "filters.ParseDelimitedRow.type": "io.streamthoughts.kafka.connect.filepulse.filter.DelimitedRowFilter",

I'm either doing the definition wrong or the connector is grouping them incorrectly.  However, if I use the option **autoGenerateColumnNames** the files are processed and I get four string columns in the topic.  But the schema registry shows a definition of one string field.  The error I'm getting is below.

Caused by: io.streamthoughts.kafka.connect.filepulse.data.DataException: Cannot find corresponding **Type for name : DATE,MESSAGETYPE**
        at io.streamthoughts.kafka.connect.filepulse.data.Type.forName(Type.java:198)
        at io.streamthoughts.kafka.connect.filepulse.config.DelimitedRowFilterConfig.schema(DelimitedRowFilterConfig.java:89)
        at io.streamthoughts.kafka.connect.filepulse.filter.DelimitedRowFilter.isMandatoryConfigsMissing(DelimitedRowFilter.java:72)
        at io.streamthoughts.kafka.connect.filepulse.filter.DelimitedRowFilter.configure(DelimitedRowFilter.java:59)
        at io.streamthoughts.kafka.connect.filepulse.config.TaskConfig.filters(TaskConfig.java:152)

**Comment by jbandy67** [comment]
The record in the topic when column names are auto generated:
{
  "column1": {
    "string": "2020-11-22 04:39:03.8271"
  },
  "column2": {
    "string": "INFO"
  },
  "column3": {
    "string": "1"
  },
  "column4": {
    "string": "Provider name"
  }
}

Schema registry definition with auto generated columns:
[
  "null",
  {
    "type": "record",
    "name": "ConnectDefault",
    "namespace": "io.confluent.connect.avro",
    "fields": [
      {
        "name": "column1",
        "type": [
          "null",
          "string"
        ],
        "default": null
      }
    ]
  }
]

**Comment by fhussonnois** [comment]
Hi @jbandy67, columns must be separated using a semicolon, there is an error in the documentation. 
```
messagedate:STRING;messagetype:STRING;messagenum:INTEGER;message:STRING
```

Also, there is no `DATE` type.

But you can use the [AppendFilter ](https://streamthoughts.github.io/kafka-connect-file-pulse/docs/developer-guide/filters/#appendfilter )with the [convert ](https://streamthoughts.github.io/kafka-connect-file-pulse/docs/developer-guide/accessing-data-and-metadata/#builtin-functions ) function to parse the field.

**Comment by jbandy67** [comment]
Thanks @fhussonnois.  I have it working now.  I used a string for the date, I think I'm going to just convert it on the consumer end.  Appreciate the quick response.
