### ISSUE TITLE
Stream content file into topic

### ISSUE THREAD

**Issue by LGouellec** [streamthoughts/kafka-connect-file-pulse#98]
Hi, 

I want to stream content XML file into a Kafka topic. I check a folder, and for each xml file, I want create a message with key = null and value = content of file. 

So I use this configuration in a local connect (Plugin File Pulse used : 1.5.0)
``` json

{
    "config": {
      "connector.class": "io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector",
      "fs.cleanup.policy.class": "io.streamthoughts.kafka.connect.filepulse.clean.DeleteCleanupPolicy",
      "fs.scanner.class": "io.streamthoughts.kafka.connect.filepulse.scanner.local.LocalFSDirectoryWalker",
      "fs.scan.directory.path": "/data",
      "fs.scan.filters": "io.streamthoughts.kafka.connect.filepulse.scanner.local.filter.RegexFileListFilter",
      "file.filter.regex.pattern": ".*\\.xml$",
      "fs.scan.interval.ms": "5000",
      "internal.kafka.reporter.bootstrap.servers": "broker:9092",
      "internal.kafka.reporter.topic": "connect-file-pulse-status",
      "offset.strategy": "name",
      "read.max.wait.ms": "5000",
      "task.reader.class": "io.streamthoughts.kafka.connect.filepulse.reader.BytesArrayInputReader",
      "topic": "notification-raw",
      "tasks.max": 1,
      "key.converter": "org.apache.kafka.connect.converters.ByteArrayConverter",
      "value.converter": "org.apache.kafka.connect.converters.ByteArrayConverter"
    },
    "name": "connect-file-pulse-test"
  }
```

I just want the content file in my topic. That's why I use your  BytesArrayInputReader. 
But in my topic, the value of my message is just the toString() method of your object, in my opinion :
![image](https://user-images.githubusercontent.com/3295357/101832107-31392200-3b37-11eb-9a83-eb132329fc15.png)

So my question : 
What is the best method to spool dir files,  and for each file create a message in topic with the content from scratch as value ?

**Comment by fhussonnois** [comment]
Hi @LGouellec, in FilePulse each reader create a basic `Struct` with a field `message`.  You can use the `ExtractField` transformer to extract the message field and replace the value : https://docs.confluent.io/platform/current/connect/transforms/extractfield.html

**Comment by LGouellec** [comment]
Oh yeah, great ! 
I hadn't thought about it. Thank you for support. 

So I close this issue.
